/*
; K210_clint.
; ===========

; SPDX-License-Identifier: MIT

;------------------------------------------------------------------------
; Author:	Edo. Franzi		The 2025-01-01
; Modifs:
;
; Project:	uKOS-X
; Goal:		K210_clint equates.
;
;   (c) 2025-2026, Edo. Franzi
;   --------------------------
;                                              __ ______  _____
;   Edo. Franzi                         __  __/ //_/ __ \/ ___/
;   5-Route de Cheseaux                / / / / ,< / / / /\__ \
;   CH 1400 Cheseaux-Noréaz           / /_/ / /| / /_/ /___/ /
;                                     \__,_/_/ |_\____//____/
;   edo.franzi@ukos.ch
;
;   Description: Lightweight, real-time multitasking operating
;   system for embedded microcontroller and DSP-based systems.
;
;   Permission is hereby granted, free of charge, to any person
;   obtaining a copy of this software and associated documentation
;   files (the "Software"), to deal in the Software without restriction,
;   including without limitation the rights to use, copy, modify,
;   merge, publish, distribute, sublicense, and/or sell copies of the
;   Software, and to permit persons to whom the Software is furnished
;   to do so, subject to the following conditions:
;
;   The above copyright notice and this permission notice shall be
;   included in all copies or substantial portions of the Software.
;
;   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
;   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
;   BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
;   ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
;   CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
;   SOFTWARE.
;
;------------------------------------------------------------------------
*/

#pragma	once

#define	CLINT_MSIP				0x0000u
#define	CLINT_MSIP_SIZE			0x4u
#define	CLINT_MTIMECMP			0x4000u
#define	CLINT_MTIMECMP_SIZE		0x8u
#define	CLINT_MTIME				0xBFF8u
#define	CLINT_MTIME_SIZE		0x8u
#define CLINT_MAX_CORES			4095u
#define CLINT_NUM_CORES			2u
#define CLINT_CLOCK_DIV			50u

#define	PLIC_NUM_SOURCES		(EINT_MAX - 1u)
#define	PLIC_NUM_PRIORITIES		7u
#define	PLIC_NUM_CORES			2u

// MSIP Registers
// --------------

// Machine-mode software interrupts are generated by writing to a
// per-core memory-mapped control register. The msip registers are
// 32-bit wide WARL registers, where the LSB is reflected in the
// msip bit of the associated core’s mip register. Other bits in
// the msip registers are hardwired to zero. The mapping supports
// up to 4095 machine-mode cores.
//
typedef	struct	_clint_msip {
	uint32_t	msip : 1;
	uint32_t	zero : 31;
} __attribute__ ((packed, aligned(4))) clint_msip_t;

// Timer compare Registers
// -----------------------

// Timer compare Registers Machine-mode timer interrupts are
// generated by a real-time counter and a per-core comparator. The
// mtime register is a 64-bit read-only register that contains the
// current value of the real-time counter. Each mtimecmp register
// holds its core’s time comparator. A timer interrupt is pending
// whenever mtime is greater than or equal to the value in a
// core’s mtimecmp register. The timer interrupt is reflected in
// the mtip bit of the associated core’s mip register.
//
typedef	uint64_t	clint_mtimecmp_t;

// Timer Registers
// ---------------

// The mtime register has a 64-bit precision on all RV32, RV64,
// and RV128 systems. Platforms provide a 64-bit memory-mapped
// machine-mode timer compare register (mtimecmp), which causes a
// timer interrupt to be posted when the mtime register contains a
// value greater than or equal to the value in the mtimecmp
// register. The interrupt remains posted until it is cleared by
// writing the mtimecmp register. The interrupt will only be taken
// if interrupts are enabled and the MTIE bit is set in the mie
// register.
//
typedef	uint64_t	clint_mtime_t;

// CLINT object
// ------------

// Coreplex-Local INTerrupts, which includes software interrupts,
// local timer interrupts, and other interrupts routed directly to
// a core.
//
typedef	struct	_clint {
	clint_msip_t		msip[CLINT_MAX_CORES];				// 0x0000 to 0x3FF8, MSIP Registers
    uint32_t			resv0;								// Resverd space, do not use
	clint_mtimecmp_t	mtimecmp[CLINT_MAX_CORES];			// 0x4000 to 0xBFF0, Timer Compare Registers
	clint_mtime_t		mtime;								// 0xBFF8, Time Register
} __attribute__ ((packed, aligned(4))) clint_t;

#define	clint	((volatile clint_t *)0x02000000u)
