#!/usr/bin/env zsh
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Laurent von Allmen
#
# Purpose:
#   Execute manually an IWYU check of a downloadable application
#
# Usage:
#   cd Applications/uKOS_Appls_Downloadable/<family>/<app>/<board>
#   check-iwyu-app.sh [cmake_preset]
#
# Arguments:
#   cmake_preset: CMake preset name (default: llvm)
#
# Note:
#   This script extracts compiler flags from compile_commands.json
#   generated by CMake and transforms them for use with IWYU.
#
#   It differs from check-iwyu.sh in how it finds the target: the application
#   build passes no --target to the C++ compiler (and to neither compiler on
#   some cores), so the triple is asked from the compiler itself. The system
#   headers are taken from the toolchain that owns that compiler.

emulate -L zsh
setopt ERR_EXIT NO_UNSET PIPE_FAIL EXTENDED_GLOB

# Colours for messages
readonly RED=$'\033[0;31m'
readonly BLUE=$'\033[0;34m'
readonly NC=$'\033[0m' # No Color

if ! command -v include-what-you-use &>/dev/null; then
    print "Command 'include-what-you-use' is not in your PATH"
    exit 1
fi

readonly mapping_file="${0:A:h}/iwyu-ukosx.imp"
if [[ ! -f "$mapping_file" ]]; then
    print -u2 "${RED}Error: IWYU mapping file not found: ${mapping_file}${NC}"
    exit 1
fi

# Parse command-line arguments
cmake_preset="llvm"
if [[ $# -eq 1 ]]; then
    cmake_preset="$1"
elif [[ $# -gt 1 ]]; then
    print -u2 "${RED}Error: Too many arguments${NC}"
    print -u2 "Usage: ${0:t} [cmake_preset]"
    print -u2 "  cmake_preset: CMake preset name (default: llvm)"
    exit 1
fi
if [[ ! "$cmake_preset" =~ ^llvm ]]; then
    print -u2 "Use only llvm presets"
    exit 1
fi

if [[ ! -f CMakePresets.json || "${PWD:A}" != */Applications/* ]]; then
    print -u2 "${RED}Error: Not an application board directory: ${PWD}${NC}"
    print -u2 "Run from Applications/uKOS_Appls_Downloadable/<family>/<app>/<board>"
    exit 1
fi

print "${BLUE}Running CMake with preset: ${cmake_preset}${NC}"
rm -fr build
cmake --preset "$cmake_preset" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON > /dev/null

if [[ ! -f build/compile_commands.json ]]; then
    print -u2 "${RED}Error: build/compile_commands.json not found${NC}"
    exit 1
fi

# Process each entry in compile_commands.json
while IFS= read -r entry; do
    file=$(jq -r '.[0]' <<< "$entry")
    command=$(jq -r '.[1]' <<< "$entry")

    # Skip assembly files (.S, .s)
    [[ "$file" =~ \.(S|s)$ ]] && continue

    printf '\n%sProcessing:%s %s\n' "${BLUE}" "${NC}" "$file"

    # The compiler is the first word; anything else is not a compile command
    # this script knows how to turn into an IWYU one.
    compiler=${command%% *}
    arguments=${command#* }
    if [[ "${compiler:t}" != clang(|++) ]]; then
        print -u2 "${RED}Error: Not a clang[++] command for ${file} - skipping${NC}"
        continue
    fi

    # The target: the one given, or else the one the compiler derives from the
    # core flags (-mcpu, -march, ...).
    target=$(sed -n 's/.*--target=\([^ ]*\).*/\1/p' <<< "$command")
    if [[ -z "$target" ]]; then
        core_flags=(${(M)${=arguments}:#-m(thumb|cpu=*|arch=*|abi=*|float-abi=*|fpu=*)})
        target=$("$compiler" "${core_flags[@]}" -print-effective-triple)
    fi

    # Set architecture-specific paths based on target
    runtimes="${compiler:h:h}/lib/clang-runtimes"
    if [[ "$target" =~ ^(thumb|arm) ]]; then
        isystem_path="${runtimes}/arm-none-eabi/include"
    elif [[ "$target" =~ ^riscv32 ]]; then
        target="riscv32-unknown-elf"
        isystem_path="${runtimes}/riscv32-unknown-elf/include"
    elif [[ "$target" =~ ^riscv64 ]]; then
        target="riscv64-unknown-elf"
        isystem_path="${runtimes}/riscv64-unknown-elf/include"
    else
        print -u2 "${RED}Error: Unknown architecture for target ${target} - skipping${NC}"
        continue
    fi

    # C++ sources need libc++'s headers (<cinttypes>, etc.) in addition to the C
    # runtime include dir above, and BEFORE it: libc++'s own math.h/cmath etc.
    # are wrappers that #include_next the real C library header.
    cxx_isystem=""
    if [[ "$file" =~ \.(cpp|cc|cxx)$ ]]; then
        cxx_isystem="-isystem${isystem_path}/c++/v1 "
    fi

    # Transform the command
    transformed_cmd="include-what-you-use -Xiwyu --mapping_file=${mapping_file} --target=${target} ${cxx_isystem}-isystem${isystem_path} "
    transformed_cmd+=$(sed -e 's/^/ /' \
        -e 's/ --target=[^ ]*//g' \
        -e 's/ -mcpu=[^ ]*//g' \
        -e 's/ -march=[^ ]*//g' \
        -e 's/ -mfloat-abi=[^ ]*//g' \
        -e 's/ -mfpu=[^ ]*//g' \
        -e 's/ -mabi=[^ ]*//g' \
        -e 's/ -mllvm=[^ ]*//g' \
        -e 's/ -mthumb//g' \
        -e 's/ -o [^ ]*//g' \
        -e 's/ -c / /' <<< "$arguments")

    # IWYU exits non-zero whenever it has something to report
    eval "$transformed_cmd" || true
done < <(jq -cr '.[] | [.file, .command]' build/compile_commands.json)
