#!/usr/bin/env zsh
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025-2026 Laurent von Allmen
#
# Purpose:
#   Execute manually an IWYU check
#
# Usage:
#   cd variant_under_test
#   check-iwyu.sh [cmake_preset]
#
# Arguments:
#   cmake_preset: CMake preset name (default: llvm)
#
# Note:
#   This script extracts compiler flags from compile_commands.json
#   generated by CMake and transforms them for use with IWYU.

emulate -L zsh
setopt ERR_EXIT NO_UNSET PIPE_FAIL EXTENDED_GLOB

if ! command -v include-what-you-use &>/dev/null; then
    print "Command 'include-what-you-use' is not in your PATH"
    exit 1
fi

readonly mapping_file="${0:A:h}/iwyu-ukosx.imp"
if [[ ! -f "$mapping_file" ]]; then
    print -u2 "${RED}Error: IWYU mapping file not found: ${mapping_file}${NC}"
    exit 1
fi

# Colours for messages
readonly RED=$'\033[0;31m'
readonly GREEN=$'\033[0;32m'
readonly YELLOW=$'\033[0;33m'
readonly BLUE=$'\033[0;34m'
readonly BOLD=$'\033[1m'
readonly FAINT=$'\033[2m'
readonly ITALIC=$'\033[3m'
readonly NC=$'\033[0m' # No Color

# Parse command-line arguments
cmake_preset="llvm"
if [[ $# -eq 1 ]]; then
    cmake_preset="$1"
elif [[ $# -gt 1 ]]; then
    print -u2 "${RED}Error: Too many arguments${NC}"
    print -u2 "Usage: ${0:t} [cmake_preset]"
    print -u2 "  cmake_preset: CMake preset name (default: llvm)"
    exit 1
fi
if [[ ! "$cmake_preset" =~ ^llvm ]]; then
    print -u2 "Use only llvm presets"
    exit 1
fi

print "${BLUE}Running CMake with preset: ${cmake_preset}${NC}"
rm -fr build
cmake --preset "$cmake_preset" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON > /dev/null

if [[ ! -f build/compile_commands.json ]]; then
    print -u2 "${RED}Error: build/compile_commands.json not found${NC}"
    exit 1
fi

# Process each entry in compile_commands.json
while IFS= read -r entry; do
    file=$(jq -r '.[0]' <<< "$entry")
    command=$(jq -r '.[1]' <<< "$entry")

    # Skip files containing 'FLASH.sig'
    [[ "$file" == *FLASH.sig* ]] && continue

    # Skip assembly files (.S, .s)
    [[ "$file" =~ \.(S|s)$ ]] && continue

    # Determine architecture from original target
    original_target=$(sed -n 's/.*--target=\([^ ]*\).*/\1/p' <<< "$command")

    # Set architecture-specific paths based on target
    if [[ "$original_target" =~ ^(thumb|arm) ]]; then
        # ARM architecture
        arch_name="arm"
#         iwyu_target="arm-unknown-none-eabi"
        iwyu_target=$original_target
        isystem_path="${PATH_LLVM_ARM}/lib/clang-runtimes/arm-none-eabi/include"
    elif [[ "$original_target" =~ ^riscv32 ]]; then
        # RISC-V 32-bit architecture
        arch_name="riscv"
        iwyu_target="riscv32-unknown-elf"
        isystem_path="${PATH_LLVM_RVXX}/lib/clang-runtimes/riscv32-unknown-elf/include"
    elif [[ "$original_target" =~ ^riscv64 ]]; then
        # RISC-V 64-bit architecture
        arch_name="riscv"
        iwyu_target="riscv64-unknown-elf"
        isystem_path="${PATH_LLVM_RVXX}/lib/clang-runtimes/riscv64-unknown-elf/include"
    else
        print -u2 "${YELLOW}Warning: Unknown architecture for target ${original_target}, defaulting to ARM${NC}"
        arch_name="arm"
        iwyu_target="arm-unknown-none-eabi"
        isystem_path="${PATH_LLVM_ARM}/lib/clang-runtimes/arm-none-eabi/include"
    fi

    # C++ sources need libc++'s headers (<cinttypes>, etc.) in addition to the C
    # runtime include dir above. The toolchain's own clang++ finds these on its
    # own via its bundled layout; IWYU, a separate binary, does not, so add the
    # matching include/c++/v1 explicitly - and search it BEFORE the plain C
    # include dir: libc++'s own math.h/cmath etc. are wrappers that #include_next
    # the real newlib header. Reversing the order lets newlib's math.h (with its
    # isfinite() etc. macros) shadow the wrapper, which then fails to parse.
    cxx_isystem=""
    if [[ "$file" =~ \.(cpp|cc|cxx)$ ]]; then
        cxx_isystem="-isystem${isystem_path}/c++/v1 "
    fi

    # Transform the command
    # NOTE: [+]* matches clang or clang++ (C and C++ compiles alike) without relying
    # on GNU sed's extended-regex alternation, which BSD sed lacks.
    transformed_cmd=$(sed -e "s|[^ ]*/clang[+]* --target=[^ ]*|include-what-you-use -Xiwyu --mapping_file=${mapping_file} --target=${iwyu_target} ${cxx_isystem}-isystem${isystem_path}|" \
        -e 's/ -mcpu=[^ ]*//g' \
        -e 's/ -march=[^ ]*//g' \
        -e 's/ -mfloat-abi=[^ ]*//g' \
        -e 's/ -mfpu=[^ ]*//g' \
        -e 's/ -mabi=[^ ]*//g' \
        -e 's/ -mthumb//g' \
        -e 's/ -o [^ ]*//g' \
        -e 's/ -c / /' <<< "$command")

    printf '\n%sProcessing:%s %s' "${BLUE}" "${NC}" "$file"

    # Guard: if the compiler-command substitution above did not match (e.g. a
    # future entry with no "clang[++] --target=..." prefix), transformed_cmd is
    # still the original compile/link command. eval'ing it would run the real
    # compiler with -c/-o stripped, i.e. a stray full link. Skip instead.
    if [[ "$transformed_cmd" != *"include-what-you-use"* ]]; then
        print -u2 "\n${RED}Error: Could not transform command for ${file} (no clang[++] --target= match) - skipping${NC}"
        continue
    fi

    eval "$transformed_cmd"
done < <(jq -cr '.[] | [.file, .command]' build/compile_commands.json)
