/*
 * SPDX-License-Identifier: MIT
 * SPDX-FileCopyrightText: 2025-2026 Edo. Franzi
 *
 * Generated using the .svd description
 * Goal:     stm32H747_CM7_hrtim_timc equates.
 */

#pragma once

#include    <stdint.h>

// HRTIM_TIMC address definitions
// ------------------------------

typedef struct {
    volatile    uint32_t    TIMCCR;
    volatile    uint32_t    TIMCISR;
    volatile    uint32_t    TIMCICR;
    volatile    uint32_t    TIMCDIER5;
    volatile    uint32_t    CNTCR;
    volatile    uint32_t    PERCR;
    volatile    uint32_t    REPCR;
    volatile    uint32_t    CMP1CR;
    volatile    uint32_t    CMP1CCR;
    volatile    uint32_t    CMP2CR;
    volatile    uint32_t    CMP3CR;
    volatile    uint32_t    CMP4CR;
    volatile    uint32_t    CPT1CR;
    volatile    uint32_t    CPT2CR;
    volatile    uint32_t    DTCR;
    volatile    uint32_t    SETC1R;
    volatile    uint32_t    RSTC1R;
    volatile    uint32_t    SETC2R;
    volatile    uint32_t    RSTC2R;
    volatile    uint32_t    EEFCR1;
    volatile    uint32_t    EEFCR2;
    volatile    uint32_t    RSTCR;
    volatile    uint32_t    CHPCR;
    volatile    uint32_t    CPT1CCR;
    volatile    uint32_t    CPT2CCR;
    volatile    uint32_t    OUTCR;
    volatile    uint32_t    FLTCR;
} HRTIM_TIMC_TypeDef;

#ifdef __cplusplus
#define HRTIM_TIMC  reinterpret_cast<HRTIM_TIMC_TypeDef *>(0x40017580U)

#else
#define HRTIM_TIMC  ((HRTIM_TIMC_TypeDef *)0x40017580U)
#endif

// TIMCCR Configuration

#define HRTIM_TIMC_TIMCCR_CK_PSCX       (0x7U<<0U)
#define HRTIM_TIMC_TIMCCR_CK_PSCX_0     (0x1U<<0U)
#define HRTIM_TIMC_TIMCCR_CONT          (0x1U<<3U)
#define HRTIM_TIMC_TIMCCR_RETRIG        (0x1U<<4U)
#define HRTIM_TIMC_TIMCCR_HALF          (0x1U<<5U)
#define HRTIM_TIMC_TIMCCR_PSHPLL        (0x1U<<6U)
#define HRTIM_TIMC_TIMCCR_SYNCRSTX      (0x1U<<10U)
#define HRTIM_TIMC_TIMCCR_SYNCSTRTX     (0x1U<<11U)
#define HRTIM_TIMC_TIMCCR_DELCMP2       (0x3U<<12U)
#define HRTIM_TIMC_TIMCCR_DELCMP2_0     (0x1U<<12U)
#define HRTIM_TIMC_TIMCCR_DELCMP4       (0x3U<<14U)
#define HRTIM_TIMC_TIMCCR_DELCMP4_0     (0x1U<<14U)
#define HRTIM_TIMC_TIMCCR_TXREPU        (0x1U<<17U)
#define HRTIM_TIMC_TIMCCR_TXRSTU        (0x1U<<18U)
#define HRTIM_TIMC_TIMCCR_TBU           (0x1U<<20U)
#define HRTIM_TIMC_TIMCCR_TCU           (0x1U<<21U)
#define HRTIM_TIMC_TIMCCR_TDU           (0x1U<<22U)
#define HRTIM_TIMC_TIMCCR_TEU           (0x1U<<23U)
#define HRTIM_TIMC_TIMCCR_MSTU          (0x1U<<24U)
#define HRTIM_TIMC_TIMCCR_DACSYNC       (0x3U<<25U)
#define HRTIM_TIMC_TIMCCR_DACSYNC_0     (0x1U<<25U)
#define HRTIM_TIMC_TIMCCR_PREEN         (0x1U<<27U)
#define HRTIM_TIMC_TIMCCR_UPDGAT        (0xFU<<28U)
#define HRTIM_TIMC_TIMCCR_UPDGAT_0      (0x1U<<28U)

// TIMCISR Configuration

#define HRTIM_TIMC_TIMCISR_CMP1         (0x1U<<0U)
#define HRTIM_TIMC_TIMCISR_CMP2         (0x1U<<1U)
#define HRTIM_TIMC_TIMCISR_CMP3         (0x1U<<2U)
#define HRTIM_TIMC_TIMCISR_CMP4         (0x1U<<3U)
#define HRTIM_TIMC_TIMCISR_REP          (0x1U<<4U)
#define HRTIM_TIMC_TIMCISR_UPD          (0x1U<<6U)
#define HRTIM_TIMC_TIMCISR_CPT1         (0x1U<<7U)
#define HRTIM_TIMC_TIMCISR_CPT2         (0x1U<<8U)
#define HRTIM_TIMC_TIMCISR_SETX1        (0x1U<<9U)
#define HRTIM_TIMC_TIMCISR_RSTX1        (0x1U<<10U)
#define HRTIM_TIMC_TIMCISR_SETX2        (0x1U<<11U)
#define HRTIM_TIMC_TIMCISR_RSTX2        (0x1U<<12U)
#define HRTIM_TIMC_TIMCISR_RST          (0x1U<<13U)
#define HRTIM_TIMC_TIMCISR_DLYPRT       (0x1U<<14U)
#define HRTIM_TIMC_TIMCISR_CPPSTAT      (0x1U<<16U)
#define HRTIM_TIMC_TIMCISR_IPPSTAT      (0x1U<<17U)
#define HRTIM_TIMC_TIMCISR_O1STAT       (0x1U<<18U)
#define HRTIM_TIMC_TIMCISR_O2STAT       (0x1U<<19U)

// TIMCICR Configuration

#define HRTIM_TIMC_TIMCICR_CMP1C        (0x1U<<0U)
#define HRTIM_TIMC_TIMCICR_CMP2C        (0x1U<<1U)
#define HRTIM_TIMC_TIMCICR_CMP3C        (0x1U<<2U)
#define HRTIM_TIMC_TIMCICR_CMP4C        (0x1U<<3U)
#define HRTIM_TIMC_TIMCICR_REPC         (0x1U<<4U)
#define HRTIM_TIMC_TIMCICR_UPDC         (0x1U<<6U)
#define HRTIM_TIMC_TIMCICR_CPT1C        (0x1U<<7U)
#define HRTIM_TIMC_TIMCICR_CPT2C        (0x1U<<8U)
#define HRTIM_TIMC_TIMCICR_SET1XC       (0x1U<<9U)
#define HRTIM_TIMC_TIMCICR_RSTX1C       (0x1U<<10U)
#define HRTIM_TIMC_TIMCICR_SET2XC       (0x1U<<11U)
#define HRTIM_TIMC_TIMCICR_RSTX2C       (0x1U<<12U)
#define HRTIM_TIMC_TIMCICR_RSTC         (0x1U<<13U)
#define HRTIM_TIMC_TIMCICR_DLYPRTC      (0x1U<<14U)

// TIMCDIER5 Configuration

#define HRTIM_TIMC_TIMCDIER5_CMP1IE     (0x1U<<0U)
#define HRTIM_TIMC_TIMCDIER5_CMP2IE     (0x1U<<1U)
#define HRTIM_TIMC_TIMCDIER5_CMP3IE     (0x1U<<2U)
#define HRTIM_TIMC_TIMCDIER5_CMP4IE     (0x1U<<3U)
#define HRTIM_TIMC_TIMCDIER5_REPIE      (0x1U<<4U)
#define HRTIM_TIMC_TIMCDIER5_UPDIE      (0x1U<<6U)
#define HRTIM_TIMC_TIMCDIER5_CPT1IE     (0x1U<<7U)
#define HRTIM_TIMC_TIMCDIER5_CPT2IE     (0x1U<<8U)
#define HRTIM_TIMC_TIMCDIER5_SET1XIE    (0x1U<<9U)
#define HRTIM_TIMC_TIMCDIER5_RSTX1IE    (0x1U<<10U)
#define HRTIM_TIMC_TIMCDIER5_SETX2IE    (0x1U<<11U)
#define HRTIM_TIMC_TIMCDIER5_RSTX2IE    (0x1U<<12U)
#define HRTIM_TIMC_TIMCDIER5_RSTIE      (0x1U<<13U)
#define HRTIM_TIMC_TIMCDIER5_DLYPRTIE   (0x1U<<14U)
#define HRTIM_TIMC_TIMCDIER5_CMP1DE     (0x1U<<16U)
#define HRTIM_TIMC_TIMCDIER5_CMP2DE     (0x1U<<17U)
#define HRTIM_TIMC_TIMCDIER5_CMP3DE     (0x1U<<18U)
#define HRTIM_TIMC_TIMCDIER5_CMP4DE     (0x1U<<19U)
#define HRTIM_TIMC_TIMCDIER5_REPDE      (0x1U<<20U)
#define HRTIM_TIMC_TIMCDIER5_UPDDE      (0x1U<<22U)
#define HRTIM_TIMC_TIMCDIER5_CPT1DE     (0x1U<<23U)
#define HRTIM_TIMC_TIMCDIER5_CPT2DE     (0x1U<<24U)
#define HRTIM_TIMC_TIMCDIER5_SET1XDE    (0x1U<<25U)
#define HRTIM_TIMC_TIMCDIER5_RSTX1DE    (0x1U<<26U)
#define HRTIM_TIMC_TIMCDIER5_SETX2DE    (0x1U<<27U)
#define HRTIM_TIMC_TIMCDIER5_RSTX2DE    (0x1U<<28U)
#define HRTIM_TIMC_TIMCDIER5_RSTDE      (0x1U<<29U)
#define HRTIM_TIMC_TIMCDIER5_DLYPRTDE   (0x1U<<30U)

// CNTCR Configuration

#define HRTIM_TIMC_CNTCR_CNTX           (0xFFFFU<<0U)
#define HRTIM_TIMC_CNTCR_CNTX_0         (0x1U<<0U)

// PERCR Configuration

#define HRTIM_TIMC_PERCR_PERX           (0xFFFFU<<0U)
#define HRTIM_TIMC_PERCR_PERX_0         (0x1U<<0U)

// REPCR Configuration

#define HRTIM_TIMC_REPCR_REPX           (0xFFU<<0U)
#define HRTIM_TIMC_REPCR_REPX_0         (0x1U<<0U)

// CMP1CR Configuration

#define HRTIM_TIMC_CMP1CR_CMP1X         (0xFFFFU<<0U)
#define HRTIM_TIMC_CMP1CR_CMP1X_0       (0x1U<<0U)

// CMP1CCR Configuration

#define HRTIM_TIMC_CMP1CCR_CMP1X        (0xFFFFU<<0U)
#define HRTIM_TIMC_CMP1CCR_CMP1X_0      (0x1U<<0U)
#define HRTIM_TIMC_CMP1CCR_REPX         (0xFFU<<16U)
#define HRTIM_TIMC_CMP1CCR_REPX_0       (0x1U<<16U)

// CMP2CR Configuration

#define HRTIM_TIMC_CMP2CR_CMP2X         (0xFFFFU<<0U)
#define HRTIM_TIMC_CMP2CR_CMP2X_0       (0x1U<<0U)

// CMP3CR Configuration

#define HRTIM_TIMC_CMP3CR_CMP3X         (0xFFFFU<<0U)
#define HRTIM_TIMC_CMP3CR_CMP3X_0       (0x1U<<0U)

// CMP4CR Configuration

#define HRTIM_TIMC_CMP4CR_CMP4X         (0xFFFFU<<0U)
#define HRTIM_TIMC_CMP4CR_CMP4X_0       (0x1U<<0U)

// CPT1CR Configuration

#define HRTIM_TIMC_CPT1CR_CPT1X         (0xFFFFU<<0U)
#define HRTIM_TIMC_CPT1CR_CPT1X_0       (0x1U<<0U)

// CPT2CR Configuration

#define HRTIM_TIMC_CPT2CR_CPT2X         (0xFFFFU<<0U)
#define HRTIM_TIMC_CPT2CR_CPT2X_0       (0x1U<<0U)

// DTCR Configuration

#define HRTIM_TIMC_DTCR_DTRX            (0x1FFU<<0U)
#define HRTIM_TIMC_DTCR_DTRX_0          (0x1U<<0U)
#define HRTIM_TIMC_DTCR_SDTRX           (0x1U<<9U)
#define HRTIM_TIMC_DTCR_DTPRSC          (0x7U<<10U)
#define HRTIM_TIMC_DTCR_DTPRSC_0        (0x1U<<10U)
#define HRTIM_TIMC_DTCR_DTRSLKX         (0x1U<<14U)
#define HRTIM_TIMC_DTCR_DTRLKX          (0x1U<<15U)
#define HRTIM_TIMC_DTCR_DTFX            (0x1FFU<<16U)
#define HRTIM_TIMC_DTCR_DTFX_0          (0x1U<<16U)
#define HRTIM_TIMC_DTCR_SDTFX           (0x1U<<25U)
#define HRTIM_TIMC_DTCR_DTFSLKX         (0x1U<<30U)
#define HRTIM_TIMC_DTCR_DTFLKX          (0x1U<<31U)

// SETC1R Configuration

#define HRTIM_TIMC_SETC1R_SST           (0x1U<<0U)
#define HRTIM_TIMC_SETC1R_RESYNC        (0x1U<<1U)
#define HRTIM_TIMC_SETC1R_PER           (0x1U<<2U)
#define HRTIM_TIMC_SETC1R_CMP1          (0x1U<<3U)
#define HRTIM_TIMC_SETC1R_CMP2          (0x1U<<4U)
#define HRTIM_TIMC_SETC1R_CMP3          (0x1U<<5U)
#define HRTIM_TIMC_SETC1R_CMP4          (0x1U<<6U)
#define HRTIM_TIMC_SETC1R_MSTPER        (0x1U<<7U)
#define HRTIM_TIMC_SETC1R_MSTCMP1       (0x1U<<8U)
#define HRTIM_TIMC_SETC1R_MSTCMP2       (0x1U<<9U)
#define HRTIM_TIMC_SETC1R_MSTCMP3       (0x1U<<10U)
#define HRTIM_TIMC_SETC1R_MSTCMP4       (0x1U<<11U)
#define HRTIM_TIMC_SETC1R_TIMEVNT1      (0x1U<<12U)
#define HRTIM_TIMC_SETC1R_TIMEVNT2      (0x1U<<13U)
#define HRTIM_TIMC_SETC1R_TIMEVNT3      (0x1U<<14U)
#define HRTIM_TIMC_SETC1R_TIMEVNT4      (0x1U<<15U)
#define HRTIM_TIMC_SETC1R_TIMEVNT5      (0x1U<<16U)
#define HRTIM_TIMC_SETC1R_TIMEVNT6      (0x1U<<17U)
#define HRTIM_TIMC_SETC1R_TIMEVNT7      (0x1U<<18U)
#define HRTIM_TIMC_SETC1R_TIMEVNT8      (0x1U<<19U)
#define HRTIM_TIMC_SETC1R_TIMEVNT9      (0x1U<<20U)
#define HRTIM_TIMC_SETC1R_EXTEVNT1      (0x1U<<21U)
#define HRTIM_TIMC_SETC1R_EXTEVNT2      (0x1U<<22U)
#define HRTIM_TIMC_SETC1R_EXTEVNT3      (0x1U<<23U)
#define HRTIM_TIMC_SETC1R_EXTEVNT4      (0x1U<<24U)
#define HRTIM_TIMC_SETC1R_EXTEVNT5      (0x1U<<25U)
#define HRTIM_TIMC_SETC1R_EXTEVNT6      (0x1U<<26U)
#define HRTIM_TIMC_SETC1R_EXTEVNT7      (0x1U<<27U)
#define HRTIM_TIMC_SETC1R_EXTEVNT8      (0x1U<<28U)
#define HRTIM_TIMC_SETC1R_EXTEVNT9      (0x1U<<29U)
#define HRTIM_TIMC_SETC1R_EXTEVNT10     (0x1U<<30U)
#define HRTIM_TIMC_SETC1R_UPDATE        (0x1U<<31U)

// RSTC1R Configuration

#define HRTIM_TIMC_RSTC1R_SRT           (0x1U<<0U)
#define HRTIM_TIMC_RSTC1R_RESYNC        (0x1U<<1U)
#define HRTIM_TIMC_RSTC1R_PER           (0x1U<<2U)
#define HRTIM_TIMC_RSTC1R_CMP1          (0x1U<<3U)
#define HRTIM_TIMC_RSTC1R_CMP2          (0x1U<<4U)
#define HRTIM_TIMC_RSTC1R_CMP3          (0x1U<<5U)
#define HRTIM_TIMC_RSTC1R_CMP4          (0x1U<<6U)
#define HRTIM_TIMC_RSTC1R_MSTPER        (0x1U<<7U)
#define HRTIM_TIMC_RSTC1R_MSTCMP1       (0x1U<<8U)
#define HRTIM_TIMC_RSTC1R_MSTCMP2       (0x1U<<9U)
#define HRTIM_TIMC_RSTC1R_MSTCMP3       (0x1U<<10U)
#define HRTIM_TIMC_RSTC1R_MSTCMP4       (0x1U<<11U)
#define HRTIM_TIMC_RSTC1R_TIMEVNT1      (0x1U<<12U)
#define HRTIM_TIMC_RSTC1R_TIMEVNT2      (0x1U<<13U)
#define HRTIM_TIMC_RSTC1R_TIMEVNT3      (0x1U<<14U)
#define HRTIM_TIMC_RSTC1R_TIMEVNT4      (0x1U<<15U)
#define HRTIM_TIMC_RSTC1R_TIMEVNT5      (0x1U<<16U)
#define HRTIM_TIMC_RSTC1R_TIMEVNT6      (0x1U<<17U)
#define HRTIM_TIMC_RSTC1R_TIMEVNT7      (0x1U<<18U)
#define HRTIM_TIMC_RSTC1R_TIMEVNT8      (0x1U<<19U)
#define HRTIM_TIMC_RSTC1R_TIMEVNT9      (0x1U<<20U)
#define HRTIM_TIMC_RSTC1R_EXTEVNT1      (0x1U<<21U)
#define HRTIM_TIMC_RSTC1R_EXTEVNT2      (0x1U<<22U)
#define HRTIM_TIMC_RSTC1R_EXTEVNT3      (0x1U<<23U)
#define HRTIM_TIMC_RSTC1R_EXTEVNT4      (0x1U<<24U)
#define HRTIM_TIMC_RSTC1R_EXTEVNT5      (0x1U<<25U)
#define HRTIM_TIMC_RSTC1R_EXTEVNT6      (0x1U<<26U)
#define HRTIM_TIMC_RSTC1R_EXTEVNT7      (0x1U<<27U)
#define HRTIM_TIMC_RSTC1R_EXTEVNT8      (0x1U<<28U)
#define HRTIM_TIMC_RSTC1R_EXTEVNT9      (0x1U<<29U)
#define HRTIM_TIMC_RSTC1R_EXTEVNT10     (0x1U<<30U)
#define HRTIM_TIMC_RSTC1R_UPDATE        (0x1U<<31U)

// SETC2R Configuration

#define HRTIM_TIMC_SETC2R_SST           (0x1U<<0U)
#define HRTIM_TIMC_SETC2R_RESYNC        (0x1U<<1U)
#define HRTIM_TIMC_SETC2R_PER           (0x1U<<2U)
#define HRTIM_TIMC_SETC2R_CMP1          (0x1U<<3U)
#define HRTIM_TIMC_SETC2R_CMP2          (0x1U<<4U)
#define HRTIM_TIMC_SETC2R_CMP3          (0x1U<<5U)
#define HRTIM_TIMC_SETC2R_CMP4          (0x1U<<6U)
#define HRTIM_TIMC_SETC2R_MSTPER        (0x1U<<7U)
#define HRTIM_TIMC_SETC2R_MSTCMP1       (0x1U<<8U)
#define HRTIM_TIMC_SETC2R_MSTCMP2       (0x1U<<9U)
#define HRTIM_TIMC_SETC2R_MSTCMP3       (0x1U<<10U)
#define HRTIM_TIMC_SETC2R_MSTCMP4       (0x1U<<11U)
#define HRTIM_TIMC_SETC2R_TIMEVNT1      (0x1U<<12U)
#define HRTIM_TIMC_SETC2R_TIMEVNT2      (0x1U<<13U)
#define HRTIM_TIMC_SETC2R_TIMEVNT3      (0x1U<<14U)
#define HRTIM_TIMC_SETC2R_TIMEVNT4      (0x1U<<15U)
#define HRTIM_TIMC_SETC2R_TIMEVNT5      (0x1U<<16U)
#define HRTIM_TIMC_SETC2R_TIMEVNT6      (0x1U<<17U)
#define HRTIM_TIMC_SETC2R_TIMEVNT7      (0x1U<<18U)
#define HRTIM_TIMC_SETC2R_TIMEVNT8      (0x1U<<19U)
#define HRTIM_TIMC_SETC2R_TIMEVNT9      (0x1U<<20U)
#define HRTIM_TIMC_SETC2R_EXTEVNT1      (0x1U<<21U)
#define HRTIM_TIMC_SETC2R_EXTEVNT2      (0x1U<<22U)
#define HRTIM_TIMC_SETC2R_EXTEVNT3      (0x1U<<23U)
#define HRTIM_TIMC_SETC2R_EXTEVNT4      (0x1U<<24U)
#define HRTIM_TIMC_SETC2R_EXTEVNT5      (0x1U<<25U)
#define HRTIM_TIMC_SETC2R_EXTEVNT6      (0x1U<<26U)
#define HRTIM_TIMC_SETC2R_EXTEVNT7      (0x1U<<27U)
#define HRTIM_TIMC_SETC2R_EXTEVNT8      (0x1U<<28U)
#define HRTIM_TIMC_SETC2R_EXTEVNT9      (0x1U<<29U)
#define HRTIM_TIMC_SETC2R_EXTEVNT10     (0x1U<<30U)
#define HRTIM_TIMC_SETC2R_UPDATE        (0x1U<<31U)

// RSTC2R Configuration

#define HRTIM_TIMC_RSTC2R_SRT           (0x1U<<0U)
#define HRTIM_TIMC_RSTC2R_RESYNC        (0x1U<<1U)
#define HRTIM_TIMC_RSTC2R_PER           (0x1U<<2U)
#define HRTIM_TIMC_RSTC2R_CMP1          (0x1U<<3U)
#define HRTIM_TIMC_RSTC2R_CMP2          (0x1U<<4U)
#define HRTIM_TIMC_RSTC2R_CMP3          (0x1U<<5U)
#define HRTIM_TIMC_RSTC2R_CMP4          (0x1U<<6U)
#define HRTIM_TIMC_RSTC2R_MSTPER        (0x1U<<7U)
#define HRTIM_TIMC_RSTC2R_MSTCMP1       (0x1U<<8U)
#define HRTIM_TIMC_RSTC2R_MSTCMP2       (0x1U<<9U)
#define HRTIM_TIMC_RSTC2R_MSTCMP3       (0x1U<<10U)
#define HRTIM_TIMC_RSTC2R_MSTCMP4       (0x1U<<11U)
#define HRTIM_TIMC_RSTC2R_TIMEVNT1      (0x1U<<12U)
#define HRTIM_TIMC_RSTC2R_TIMEVNT2      (0x1U<<13U)
#define HRTIM_TIMC_RSTC2R_TIMEVNT3      (0x1U<<14U)
#define HRTIM_TIMC_RSTC2R_TIMEVNT4      (0x1U<<15U)
#define HRTIM_TIMC_RSTC2R_TIMEVNT5      (0x1U<<16U)
#define HRTIM_TIMC_RSTC2R_TIMEVNT6      (0x1U<<17U)
#define HRTIM_TIMC_RSTC2R_TIMEVNT7      (0x1U<<18U)
#define HRTIM_TIMC_RSTC2R_TIMEVNT8      (0x1U<<19U)
#define HRTIM_TIMC_RSTC2R_TIMEVNT9      (0x1U<<20U)
#define HRTIM_TIMC_RSTC2R_EXTEVNT1      (0x1U<<21U)
#define HRTIM_TIMC_RSTC2R_EXTEVNT2      (0x1U<<22U)
#define HRTIM_TIMC_RSTC2R_EXTEVNT3      (0x1U<<23U)
#define HRTIM_TIMC_RSTC2R_EXTEVNT4      (0x1U<<24U)
#define HRTIM_TIMC_RSTC2R_EXTEVNT5      (0x1U<<25U)
#define HRTIM_TIMC_RSTC2R_EXTEVNT6      (0x1U<<26U)
#define HRTIM_TIMC_RSTC2R_EXTEVNT7      (0x1U<<27U)
#define HRTIM_TIMC_RSTC2R_EXTEVNT8      (0x1U<<28U)
#define HRTIM_TIMC_RSTC2R_EXTEVNT9      (0x1U<<29U)
#define HRTIM_TIMC_RSTC2R_EXTEVNT10     (0x1U<<30U)
#define HRTIM_TIMC_RSTC2R_UPDATE        (0x1U<<31U)

// EEFCR1 Configuration

#define HRTIM_TIMC_EEFCR1_EE1LTCH       (0x1U<<0U)
#define HRTIM_TIMC_EEFCR1_EE1FLTR       (0xFU<<1U)
#define HRTIM_TIMC_EEFCR1_EE1FLTR_0     (0x1U<<1U)
#define HRTIM_TIMC_EEFCR1_EE2LTCH       (0x1U<<6U)
#define HRTIM_TIMC_EEFCR1_EE2FLTR       (0xFU<<7U)
#define HRTIM_TIMC_EEFCR1_EE2FLTR_0     (0x1U<<7U)
#define HRTIM_TIMC_EEFCR1_EE3LTCH       (0x1U<<12U)
#define HRTIM_TIMC_EEFCR1_EE3FLTR       (0xFU<<13U)
#define HRTIM_TIMC_EEFCR1_EE3FLTR_0     (0x1U<<13U)
#define HRTIM_TIMC_EEFCR1_EE4LTCH       (0x1U<<18U)
#define HRTIM_TIMC_EEFCR1_EE4FLTR       (0xFU<<19U)
#define HRTIM_TIMC_EEFCR1_EE4FLTR_0     (0x1U<<19U)
#define HRTIM_TIMC_EEFCR1_EE5LTCH       (0x1U<<24U)
#define HRTIM_TIMC_EEFCR1_EE5FLTR       (0xFU<<25U)
#define HRTIM_TIMC_EEFCR1_EE5FLTR_0     (0x1U<<25U)

// EEFCR2 Configuration

#define HRTIM_TIMC_EEFCR2_EE6LTCH       (0x1U<<0U)
#define HRTIM_TIMC_EEFCR2_EE6FLTR       (0xFU<<1U)
#define HRTIM_TIMC_EEFCR2_EE6FLTR_0     (0x1U<<1U)
#define HRTIM_TIMC_EEFCR2_EE7LTCH       (0x1U<<6U)
#define HRTIM_TIMC_EEFCR2_EE7FLTR       (0xFU<<7U)
#define HRTIM_TIMC_EEFCR2_EE7FLTR_0     (0x1U<<7U)
#define HRTIM_TIMC_EEFCR2_EE8LTCH       (0x1U<<12U)
#define HRTIM_TIMC_EEFCR2_EE8FLTR       (0xFU<<13U)
#define HRTIM_TIMC_EEFCR2_EE8FLTR_0     (0x1U<<13U)
#define HRTIM_TIMC_EEFCR2_EE9LTCH       (0x1U<<18U)
#define HRTIM_TIMC_EEFCR2_EE9FLTR       (0xFU<<19U)
#define HRTIM_TIMC_EEFCR2_EE9FLTR_0     (0x1U<<19U)
#define HRTIM_TIMC_EEFCR2_EE10LTCH      (0x1U<<24U)
#define HRTIM_TIMC_EEFCR2_EE10FLTR      (0xFU<<25U)
#define HRTIM_TIMC_EEFCR2_EE10FLTR_0    (0x1U<<25U)

// RSTCR Configuration

#define HRTIM_TIMC_RSTCR_UPDT           (0x1U<<1U)
#define HRTIM_TIMC_RSTCR_CMP2           (0x1U<<2U)
#define HRTIM_TIMC_RSTCR_CMP4           (0x1U<<3U)
#define HRTIM_TIMC_RSTCR_MSTPER         (0x1U<<4U)
#define HRTIM_TIMC_RSTCR_MSTCMP1        (0x1U<<5U)
#define HRTIM_TIMC_RSTCR_MSTCMP2        (0x1U<<6U)
#define HRTIM_TIMC_RSTCR_MSTCMP3        (0x1U<<7U)
#define HRTIM_TIMC_RSTCR_MSTCMP4        (0x1U<<8U)
#define HRTIM_TIMC_RSTCR_EXTEVNT1       (0x1U<<9U)
#define HRTIM_TIMC_RSTCR_EXTEVNT2       (0x1U<<10U)
#define HRTIM_TIMC_RSTCR_EXTEVNT3       (0x1U<<11U)
#define HRTIM_TIMC_RSTCR_EXTEVNT4       (0x1U<<12U)
#define HRTIM_TIMC_RSTCR_EXTEVNT5       (0x1U<<13U)
#define HRTIM_TIMC_RSTCR_EXTEVNT6       (0x1U<<14U)
#define HRTIM_TIMC_RSTCR_EXTEVNT7       (0x1U<<15U)
#define HRTIM_TIMC_RSTCR_EXTEVNT8       (0x1U<<16U)
#define HRTIM_TIMC_RSTCR_EXTEVNT9       (0x1U<<17U)
#define HRTIM_TIMC_RSTCR_EXTEVNT10      (0x1U<<18U)
#define HRTIM_TIMC_RSTCR_TIMACMP1       (0x1U<<19U)
#define HRTIM_TIMC_RSTCR_TIMACMP2       (0x1U<<20U)
#define HRTIM_TIMC_RSTCR_TIMACMP4       (0x1U<<21U)
#define HRTIM_TIMC_RSTCR_TIMBCMP1       (0x1U<<22U)
#define HRTIM_TIMC_RSTCR_TIMBCMP2       (0x1U<<23U)
#define HRTIM_TIMC_RSTCR_TIMBCMP4       (0x1U<<24U)
#define HRTIM_TIMC_RSTCR_TIMDCMP1       (0x1U<<25U)
#define HRTIM_TIMC_RSTCR_TIMDCMP2       (0x1U<<26U)
#define HRTIM_TIMC_RSTCR_TIMDCMP4       (0x1U<<27U)
#define HRTIM_TIMC_RSTCR_TIMECMP1       (0x1U<<28U)
#define HRTIM_TIMC_RSTCR_TIMECMP2       (0x1U<<29U)
#define HRTIM_TIMC_RSTCR_TIMECMP4       (0x1U<<30U)

// CHPCR Configuration

#define HRTIM_TIMC_CHPCR_CHPFRQ         (0xFU<<0U)
#define HRTIM_TIMC_CHPCR_CHPFRQ_0       (0x1U<<0U)
#define HRTIM_TIMC_CHPCR_CHPDTY         (0x7U<<4U)
#define HRTIM_TIMC_CHPCR_CHPDTY_0       (0x1U<<4U)
#define HRTIM_TIMC_CHPCR_STRTPW         (0xFU<<7U)
#define HRTIM_TIMC_CHPCR_STRTPW_0       (0x1U<<7U)

// CPT1CCR Configuration

#define HRTIM_TIMC_CPT1CCR_SWCPT        (0x1U<<0U)
#define HRTIM_TIMC_CPT1CCR_UDPCPT       (0x1U<<1U)
#define HRTIM_TIMC_CPT1CCR_EXEV1CPT     (0x1U<<2U)
#define HRTIM_TIMC_CPT1CCR_EXEV2CPT     (0x1U<<3U)
#define HRTIM_TIMC_CPT1CCR_EXEV3CPT     (0x1U<<4U)
#define HRTIM_TIMC_CPT1CCR_EXEV4CPT     (0x1U<<5U)
#define HRTIM_TIMC_CPT1CCR_EXEV5CPT     (0x1U<<6U)
#define HRTIM_TIMC_CPT1CCR_EXEV6CPT     (0x1U<<7U)
#define HRTIM_TIMC_CPT1CCR_EXEV7CPT     (0x1U<<8U)
#define HRTIM_TIMC_CPT1CCR_EXEV8CPT     (0x1U<<9U)
#define HRTIM_TIMC_CPT1CCR_EXEV9CPT     (0x1U<<10U)
#define HRTIM_TIMC_CPT1CCR_EXEV10CPT    (0x1U<<11U)
#define HRTIM_TIMC_CPT1CCR_TA1SET       (0x1U<<12U)
#define HRTIM_TIMC_CPT1CCR_TA1RST       (0x1U<<13U)
#define HRTIM_TIMC_CPT1CCR_TACMP1       (0x1U<<14U)
#define HRTIM_TIMC_CPT1CCR_TACMP2       (0x1U<<15U)
#define HRTIM_TIMC_CPT1CCR_TB1SET       (0x1U<<16U)
#define HRTIM_TIMC_CPT1CCR_TB1RST       (0x1U<<17U)
#define HRTIM_TIMC_CPT1CCR_TBCMP1       (0x1U<<18U)
#define HRTIM_TIMC_CPT1CCR_TBCMP2       (0x1U<<19U)
#define HRTIM_TIMC_CPT1CCR_TD1SET       (0x1U<<24U)
#define HRTIM_TIMC_CPT1CCR_TD1RST       (0x1U<<25U)
#define HRTIM_TIMC_CPT1CCR_TDCMP1       (0x1U<<26U)
#define HRTIM_TIMC_CPT1CCR_TDCMP2       (0x1U<<27U)
#define HRTIM_TIMC_CPT1CCR_TE1SET       (0x1U<<28U)
#define HRTIM_TIMC_CPT1CCR_TE1RST       (0x1U<<29U)
#define HRTIM_TIMC_CPT1CCR_TECMP1       (0x1U<<30U)
#define HRTIM_TIMC_CPT1CCR_TECMP2       (0x1U<<31U)

// CPT2CCR Configuration

#define HRTIM_TIMC_CPT2CCR_SWCPT        (0x1U<<0U)
#define HRTIM_TIMC_CPT2CCR_UDPCPT       (0x1U<<1U)
#define HRTIM_TIMC_CPT2CCR_EXEV1CPT     (0x1U<<2U)
#define HRTIM_TIMC_CPT2CCR_EXEV2CPT     (0x1U<<3U)
#define HRTIM_TIMC_CPT2CCR_EXEV3CPT     (0x1U<<4U)
#define HRTIM_TIMC_CPT2CCR_EXEV4CPT     (0x1U<<5U)
#define HRTIM_TIMC_CPT2CCR_EXEV5CPT     (0x1U<<6U)
#define HRTIM_TIMC_CPT2CCR_EXEV6CPT     (0x1U<<7U)
#define HRTIM_TIMC_CPT2CCR_EXEV7CPT     (0x1U<<8U)
#define HRTIM_TIMC_CPT2CCR_EXEV8CPT     (0x1U<<9U)
#define HRTIM_TIMC_CPT2CCR_EXEV9CPT     (0x1U<<10U)
#define HRTIM_TIMC_CPT2CCR_EXEV10CPT    (0x1U<<11U)
#define HRTIM_TIMC_CPT2CCR_TA1SET       (0x1U<<12U)
#define HRTIM_TIMC_CPT2CCR_TA1RST       (0x1U<<13U)
#define HRTIM_TIMC_CPT2CCR_TACMP1       (0x1U<<14U)
#define HRTIM_TIMC_CPT2CCR_TACMP2       (0x1U<<15U)
#define HRTIM_TIMC_CPT2CCR_TB1SET       (0x1U<<16U)
#define HRTIM_TIMC_CPT2CCR_TB1RST       (0x1U<<17U)
#define HRTIM_TIMC_CPT2CCR_TBCMP1       (0x1U<<18U)
#define HRTIM_TIMC_CPT2CCR_TBCMP2       (0x1U<<19U)
#define HRTIM_TIMC_CPT2CCR_TD1SET       (0x1U<<24U)
#define HRTIM_TIMC_CPT2CCR_TD1RST       (0x1U<<25U)
#define HRTIM_TIMC_CPT2CCR_TDCMP1       (0x1U<<26U)
#define HRTIM_TIMC_CPT2CCR_TDCMP2       (0x1U<<27U)
#define HRTIM_TIMC_CPT2CCR_TE1SET       (0x1U<<28U)
#define HRTIM_TIMC_CPT2CCR_TE1RST       (0x1U<<29U)
#define HRTIM_TIMC_CPT2CCR_TECMP1       (0x1U<<30U)
#define HRTIM_TIMC_CPT2CCR_TECMP2       (0x1U<<31U)

// OUTCR Configuration

#define HRTIM_TIMC_OUTCR_POL1           (0x1U<<1U)
#define HRTIM_TIMC_OUTCR_IDLEM1         (0x1U<<2U)
#define HRTIM_TIMC_OUTCR_IDLES1         (0x1U<<3U)
#define HRTIM_TIMC_OUTCR_FAULT1         (0x3U<<4U)
#define HRTIM_TIMC_OUTCR_FAULT1_0       (0x1U<<4U)
#define HRTIM_TIMC_OUTCR_CHP1           (0x1U<<6U)
#define HRTIM_TIMC_OUTCR_DIDL1          (0x1U<<7U)
#define HRTIM_TIMC_OUTCR_DTEN           (0x1U<<8U)
#define HRTIM_TIMC_OUTCR_DLYPRTEN       (0x1U<<9U)
#define HRTIM_TIMC_OUTCR_DLYPRT         (0x7U<<10U)
#define HRTIM_TIMC_OUTCR_DLYPRT_0       (0x1U<<10U)
#define HRTIM_TIMC_OUTCR_POL2           (0x1U<<17U)
#define HRTIM_TIMC_OUTCR_IDLEM2         (0x1U<<18U)
#define HRTIM_TIMC_OUTCR_IDLES2         (0x1U<<19U)
#define HRTIM_TIMC_OUTCR_FAULT2         (0x3U<<20U)
#define HRTIM_TIMC_OUTCR_FAULT2_0       (0x1U<<20U)
#define HRTIM_TIMC_OUTCR_CHP2           (0x1U<<22U)
#define HRTIM_TIMC_OUTCR_DIDL2          (0x1U<<23U)

// FLTCR Configuration

#define HRTIM_TIMC_FLTCR_FLT1EN         (0x1U<<0U)
#define HRTIM_TIMC_FLTCR_FLT2EN         (0x1U<<1U)
#define HRTIM_TIMC_FLTCR_FLT3EN         (0x1U<<2U)
#define HRTIM_TIMC_FLTCR_FLT4EN         (0x1U<<3U)
#define HRTIM_TIMC_FLTCR_FLT5EN         (0x1U<<4U)
#define HRTIM_TIMC_FLTCR_FLTLCK         (0x1U<<31U)
