/*
; stm32H743_otg1_hs_device.
; =========================

; SPDX-License-Identifier: MIT

;------------------------------------------------------------------------
; Author:	Generated using the .svd description	The 2025-01-01
; Modifs:
;
; Project:	uKOS-X
; Goal:		stm32H743_otg1_hs_device equates.
;
;   (c) 2025-2026, Edo. Franzi
;   --------------------------
;                                              __ ______  _____
;   Edo. Franzi                         __  __/ //_/ __ \/ ___/
;   5-Route de Cheseaux                / / / / ,< / / / /\__ \
;   CH 1400 Cheseaux-Noréaz           / /_/ / /| / /_/ /___/ /
;                                     \__,_/_/ |_\____//____/
;   edo.franzi@ukos.ch
;
;   Description: Lightweight, real-time multitasking operating
;   system for embedded microcontroller and DSP-based systems.
;
;   Permission is hereby granted, free of charge, to any person
;   obtaining a copy of this software and associated documentation
;   files (the "Software"), to deal in the Software without restriction,
;   including without limitation the rights to use, copy, modify,
;   merge, publish, distribute, sublicense, and/or sell copies of the
;   Software, and to permit persons to whom the Software is furnished
;   to do so, subject to the following conditions:
;
;   The above copyright notice and this permission notice shall be
;   included in all copies or substantial portions of the Software.
;
;   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
;   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
;   BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
;   ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
;   CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
;   SOFTWARE.
;
;------------------------------------------------------------------------
*/

#pragma	once

// OTG1_HS_DEVICE address definitions
// ----------------------------------

typedef struct {
	volatile	uint32_t	OTG_HS_DCFG;
	volatile	uint32_t	OTG_HS_DCTL;
	volatile	uint32_t	OTG_HS_DSTS;
	volatile	uint32_t	RESERVED0;
	volatile	uint32_t	OTG_HS_DIEPMSK;
	volatile	uint32_t	OTG_HS_DOEPMSK;
	volatile	uint32_t	OTG_HS_DAINT;
	volatile	uint32_t	OTG_HS_DAINTMSK;
	volatile	uint32_t	RESERVED1[2];
	volatile	uint32_t	OTG_HS_DVBUSDIS;
	volatile	uint32_t	OTG_HS_DVBUSPULSE;
	volatile	uint32_t	OTG_HS_DTHRCTL;
	volatile	uint32_t	OTG_HS_DIEPEMPMSK;
	volatile	uint32_t	OTG_HS_DEACHINT;
	volatile	uint32_t	OTG_HS_DEACHINTMSK;
	volatile	uint32_t	RESERVED2[48];
	volatile	uint32_t	OTG_HS_DIEPCTL0;
	volatile	uint32_t	RESERVED3;
	volatile	uint32_t	OTG_HS_DIEPINT0;
	volatile	uint32_t	RESERVED4;
	volatile	uint32_t	OTG_HS_DIEPTSIZ0;
	volatile	uint32_t	OTG_HS_DIEPDMA1;
	volatile	uint32_t	OTG_HS_DTXFSTS0;
	volatile	uint32_t	RESERVED5;
	volatile	uint32_t	OTG_HS_DIEPCTL1;
	volatile	uint32_t	RESERVED6;
	volatile	uint32_t	OTG_HS_DIEPINT1;
	volatile	uint32_t	RESERVED7;
	volatile	uint32_t	OTG_HS_DIEPTSIZ1;
	volatile	uint32_t	OTG_HS_DIEPDMA2;
	volatile	uint32_t	OTG_HS_DTXFSTS1;
	volatile	uint32_t	RESERVED8;
	volatile	uint32_t	OTG_HS_DIEPCTL2;
	volatile	uint32_t	RESERVED9;
	volatile	uint32_t	OTG_HS_DIEPINT2;
	volatile	uint32_t	RESERVED10;
	volatile	uint32_t	OTG_HS_DIEPTSIZ2;
	volatile	uint32_t	OTG_HS_DIEPDMA3;
	volatile	uint32_t	OTG_HS_DTXFSTS2;
	volatile	uint32_t	RESERVED11;
	volatile	uint32_t	OTG_HS_DIEPCTL3;
	volatile	uint32_t	RESERVED12;
	volatile	uint32_t	OTG_HS_DIEPINT3;
	volatile	uint32_t	RESERVED13;
	volatile	uint32_t	OTG_HS_DIEPTSIZ3;
	volatile	uint32_t	OTG_HS_DIEPDMA4;
	volatile	uint32_t	OTG_HS_DTXFSTS3;
	volatile	uint32_t	RESERVED14;
	volatile	uint32_t	OTG_HS_DIEPCTL4;
	volatile	uint32_t	RESERVED15;
	volatile	uint32_t	OTG_HS_DIEPINT4;
	volatile	uint32_t	RESERVED16;
	volatile	uint32_t	OTG_HS_DIEPTSIZ4;
	volatile	uint32_t	OTG_HS_DIEPDMA5;
	volatile	uint32_t	OTG_HS_DTXFSTS4;
	volatile	uint32_t	RESERVED17;
		union {
	volatile	uint32_t	OTG_HS_DIEPCTL5;
	volatile	uint32_t	OTG_HS_DIEPTSIZ6;
		};
	volatile	uint32_t	OTG_HS_DTXFSTS6;
		union {
	volatile	uint32_t	OTG_HS_DIEPINT5;
	volatile	uint32_t	OTG_HS_DIEPTSIZ7;
		};
	volatile	uint32_t	OTG_HS_DTXFSTS7;
	volatile	uint32_t	OTG_HS_DIEPTSIZ5;
	volatile	uint32_t	RESERVED18;
	volatile	uint32_t	OTG_HS_DTXFSTS5;
	volatile	uint32_t	RESERVED19;
	volatile	uint32_t	OTG_HS_DIEPCTL6;
	volatile	uint32_t	RESERVED20;
	volatile	uint32_t	OTG_HS_DIEPINT6;
	volatile	uint32_t	RESERVED21[5];
	volatile	uint32_t	OTG_HS_DIEPCTL7;
	volatile	uint32_t	RESERVED22;
	volatile	uint32_t	OTG_HS_DIEPINT7;
	volatile	uint32_t	RESERVED23[69];
	volatile	uint32_t	OTG_HS_DOEPCTL0;
	volatile	uint32_t	RESERVED24;
	volatile	uint32_t	OTG_HS_DOEPINT0;
	volatile	uint32_t	RESERVED25;
	volatile	uint32_t	OTG_HS_DOEPTSIZ0;
	volatile	uint32_t	RESERVED26[3];
	volatile	uint32_t	OTG_HS_DOEPCTL1;
	volatile	uint32_t	RESERVED27;
	volatile	uint32_t	OTG_HS_DOEPINT1;
	volatile	uint32_t	RESERVED28;
	volatile	uint32_t	OTG_HS_DOEPTSIZ1;
	volatile	uint32_t	RESERVED29[3];
	volatile	uint32_t	OTG_HS_DOEPCTL2;
	volatile	uint32_t	RESERVED30;
	volatile	uint32_t	OTG_HS_DOEPINT2;
	volatile	uint32_t	RESERVED31;
	volatile	uint32_t	OTG_HS_DOEPTSIZ2;
	volatile	uint32_t	RESERVED32[3];
	volatile	uint32_t	OTG_HS_DOEPCTL3;
	volatile	uint32_t	RESERVED33;
	volatile	uint32_t	OTG_HS_DOEPINT3;
	volatile	uint32_t	RESERVED34;
	volatile	uint32_t	OTG_HS_DOEPTSIZ3;
	volatile	uint32_t	RESERVED35[3];
	volatile	uint32_t	OTG_HS_DOEPCTL4;
	volatile	uint32_t	RESERVED36;
	volatile	uint32_t	OTG_HS_DOEPINT4;
	volatile	uint32_t	RESERVED37;
	volatile	uint32_t	OTG_HS_DOEPTSIZ4;
	volatile	uint32_t	RESERVED38[3];
	volatile	uint32_t	OTG_HS_DOEPCTL5;
	volatile	uint32_t	RESERVED39;
	volatile	uint32_t	OTG_HS_DOEPINT5;
	volatile	uint32_t	RESERVED40;
	volatile	uint32_t	OTG_HS_DOEPTSIZ5;
	volatile	uint32_t	RESERVED41[3];
	volatile	uint32_t	OTG_HS_DOEPCTL6;
	volatile	uint32_t	RESERVED42;
	volatile	uint32_t	OTG_HS_DOEPINT6;
	volatile	uint32_t	RESERVED43;
	volatile	uint32_t	OTG_HS_DOEPTSIZ6;
	volatile	uint32_t	RESERVED44[3];
	volatile	uint32_t	OTG_HS_DOEPCTL7;
	volatile	uint32_t	RESERVED45;
	volatile	uint32_t	OTG_HS_DOEPINT7;
	volatile	uint32_t	RESERVED46;
	volatile	uint32_t	OTG_HS_DOEPTSIZ7;
} OTG1_HS_DEVICE_TypeDef;

#if (defined(__cplusplus))
#define	OTG1_HS_DEVICE	reinterpret_cast<OTG1_HS_DEVICE_TypeDef *>(0x40040800u)

#else
#define	OTG1_HS_DEVICE	((OTG1_HS_DEVICE_TypeDef *)0x40040800u)
#endif

// OTG_HS_DCFG Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DCFG_PERSCHIVL				(0x3u<<24)
#define	OTG1_HS_DEVICE_OTG_HS_DCFG_PERSCHIVL_0				(0x1u<<24)
#define	OTG1_HS_DEVICE_OTG_HS_DCFG_PFIVL					(0x3u<<11)
#define	OTG1_HS_DEVICE_OTG_HS_DCFG_PFIVL_0					(0x1u<<11)
#define	OTG1_HS_DEVICE_OTG_HS_DCFG_DAD						(0x7Fu<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DCFG_DAD_0					(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DCFG_NZLSOHSK					(0x1u<<2)
#define	OTG1_HS_DEVICE_OTG_HS_DCFG_DSPD						(0x3u<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DCFG_DSPD_0					(0x1u<<0)

// OTG_HS_DCTL Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DCTL_POPRGDNE					(0x1u<<11)
#define	OTG1_HS_DEVICE_OTG_HS_DCTL_CGONAK					(0x1u<<10)
#define	OTG1_HS_DEVICE_OTG_HS_DCTL_SGONAK					(0x1u<<9)
#define	OTG1_HS_DEVICE_OTG_HS_DCTL_CGINAK					(0x1u<<8)
#define	OTG1_HS_DEVICE_OTG_HS_DCTL_SGINAK					(0x1u<<7)
#define	OTG1_HS_DEVICE_OTG_HS_DCTL_TCTL						(0x7u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DCTL_TCTL_0					(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DCTL_GONSTS					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DCTL_GINSTS					(0x1u<<2)
#define	OTG1_HS_DEVICE_OTG_HS_DCTL_SDIS						(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DCTL_RWUSIG					(0x1u<<0)

// OTG_HS_DSTS Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DSTS_FNSOF					(0x3FFFu<<8)
#define	OTG1_HS_DEVICE_OTG_HS_DSTS_FNSOF_0					(0x1u<<8)
#define	OTG1_HS_DEVICE_OTG_HS_DSTS_EERR						(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DSTS_ENUMSPD					(0x3u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DSTS_ENUMSPD_0				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DSTS_SUSPSTS					(0x1u<<0)

// OTG_HS_DIEPMSK Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPMSK_BIM					(0x1u<<9)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPMSK_TXFURM				(0x1u<<8)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPMSK_INEPNEM				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPMSK_INEPNMM				(0x1u<<5)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPMSK_ITTXFEMSK				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPMSK_TOM					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPMSK_EPDM					(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPMSK_XFRCM					(0x1u<<0)

// OTG_HS_DOEPMSK Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPMSK_BOIM					(0x1u<<9)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPMSK_OPEM					(0x1u<<8)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPMSK_B2BSTUP				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPMSK_OTEPDM				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPMSK_STUPM					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPMSK_EPDM					(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPMSK_XFRCM					(0x1u<<0)

// OTG_HS_DAINT Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DAINT_OEPINT					(0xFFFFu<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DAINT_OEPINT_0				(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DAINT_IEPINT					(0xFFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DAINT_IEPINT_0				(0x1u<<0)

// OTG_HS_DAINTMSK Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DAINTMSK_OEPM					(0xFFFFu<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DAINTMSK_OEPM_0				(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DAINTMSK_IEPM					(0xFFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DAINTMSK_IEPM_0				(0x1u<<0)

// OTG_HS_DVBUSDIS Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DVBUSDIS_VBUSDT				(0xFFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DVBUSDIS_VBUSDT_0				(0x1u<<0)

// OTG_HS_DVBUSPULSE Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DVBUSPULSE_DVBUSP				(0xFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DVBUSPULSE_DVBUSP_0			(0x1u<<0)

// OTG_HS_DTHRCTL Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DTHRCTL_ARPEN					(0x1u<<27)
#define	OTG1_HS_DEVICE_OTG_HS_DTHRCTL_RXTHRLEN				(0x1FFu<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DTHRCTL_RXTHRLEN_0			(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DTHRCTL_RXTHREN				(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DTHRCTL_TXTHRLEN				(0x1FFu<<2)
#define	OTG1_HS_DEVICE_OTG_HS_DTHRCTL_TXTHRLEN_0			(0x1u<<2)
#define	OTG1_HS_DEVICE_OTG_HS_DTHRCTL_ISOTHREN				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DTHRCTL_NONISOTHREN			(0x1u<<0)

// OTG_HS_DIEPEMPMSK Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPEMPMSK_INEPTXFEM			(0xFFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPEMPMSK_INEPTXFEM_0		(0x1u<<0)

// OTG_HS_DEACHINT Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DEACHINT_OEP1INT				(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DEACHINT_IEP1INT				(0x1u<<1)

// OTG_HS_DEACHINTMSK Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DEACHINTMSK_OEP1INTM			(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DEACHINTMSK_IEP1INTM			(0x1u<<1)

// OTG_HS_DIEPCTL0 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL0_EPENA				(0x1u<<31)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL0_EPDIS				(0x1u<<30)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL0_SODDFRM				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL0_SD0PID_SEVNFRM		(0x1u<<28)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL0_SNAK					(0x1u<<27)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL0_CNAK					(0x1u<<26)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL0_TXFNUM				(0xFu<<22)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL0_TXFNUM_0				(0x1u<<22)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL0_STALL				(0x1u<<21)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL0_EPTYP				(0x3u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL0_EPTYP_0				(0x1u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL0_NAKSTS				(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL0_EONUM_DPID			(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL0_USBAEP				(0x1u<<15)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL0_MPSIZ				(0x7FFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL0_MPSIZ_0				(0x1u<<0)

// OTG_HS_DIEPINT0 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT0_NAK					(0x1u<<13)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT0_BERR					(0x1u<<12)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT0_PKTDRPSTS			(0x1u<<11)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT0_BNA					(0x1u<<9)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT0_TXFIFOUDRN			(0x1u<<8)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT0_TXFE					(0x1u<<7)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT0_INEPNE				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT0_ITTXFE				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT0_TOC					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT0_EPDISD				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT0_XFRC					(0x1u<<0)

// OTG_HS_DIEPTSIZ0 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ0_PKTCNT				(0x3u<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ0_PKTCNT_0			(0x1u<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ0_XFRSIZ				(0x7Fu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ0_XFRSIZ_0			(0x1u<<0)

// OTG_HS_DIEPDMA1 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPDMA1_DMAADDR				(0xFFFFFFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPDMA1_DMAADDR_0			(0x1u<<0)

// OTG_HS_DTXFSTS0 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DTXFSTS0_INEPTFSAV			(0xFFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DTXFSTS0_INEPTFSAV_0			(0x1u<<0)

// OTG_HS_DIEPCTL1 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL1_EPENA				(0x1u<<31)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL1_EPDIS				(0x1u<<30)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL1_SODDFRM				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL1_SD0PID_SEVNFRM		(0x1u<<28)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL1_SNAK					(0x1u<<27)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL1_CNAK					(0x1u<<26)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL1_TXFNUM				(0xFu<<22)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL1_TXFNUM_0				(0x1u<<22)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL1_STALL				(0x1u<<21)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL1_EPTYP				(0x3u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL1_EPTYP_0				(0x1u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL1_NAKSTS				(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL1_EONUM_DPID			(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL1_USBAEP				(0x1u<<15)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL1_MPSIZ				(0x7FFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL1_MPSIZ_0				(0x1u<<0)

// OTG_HS_DIEPINT1 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT1_NAK					(0x1u<<13)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT1_BERR					(0x1u<<12)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT1_PKTDRPSTS			(0x1u<<11)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT1_BNA					(0x1u<<9)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT1_TXFIFOUDRN			(0x1u<<8)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT1_TXFE					(0x1u<<7)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT1_INEPNE				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT1_ITTXFE				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT1_TOC					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT1_EPDISD				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT1_XFRC					(0x1u<<0)

// OTG_HS_DIEPTSIZ1 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ1_MCNT				(0x3u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ1_MCNT_0				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ1_PKTCNT				(0x3FFu<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ1_PKTCNT_0			(0x1u<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ1_XFRSIZ				(0x7FFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ1_XFRSIZ_0			(0x1u<<0)

// OTG_HS_DIEPDMA2 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPDMA2_DMAADDR				(0xFFFFFFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPDMA2_DMAADDR_0			(0x1u<<0)

// OTG_HS_DTXFSTS1 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DTXFSTS1_INEPTFSAV			(0xFFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DTXFSTS1_INEPTFSAV_0			(0x1u<<0)

// OTG_HS_DIEPCTL2 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL2_EPENA				(0x1u<<31)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL2_EPDIS				(0x1u<<30)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL2_SODDFRM				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL2_SD0PID_SEVNFRM		(0x1u<<28)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL2_SNAK					(0x1u<<27)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL2_CNAK					(0x1u<<26)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL2_TXFNUM				(0xFu<<22)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL2_TXFNUM_0				(0x1u<<22)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL2_STALL				(0x1u<<21)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL2_EPTYP				(0x3u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL2_EPTYP_0				(0x1u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL2_NAKSTS				(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL2_EONUM_DPID			(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL2_USBAEP				(0x1u<<15)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL2_MPSIZ				(0x7FFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL2_MPSIZ_0				(0x1u<<0)

// OTG_HS_DIEPINT2 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT2_NAK					(0x1u<<13)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT2_BERR					(0x1u<<12)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT2_PKTDRPSTS			(0x1u<<11)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT2_BNA					(0x1u<<9)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT2_TXFIFOUDRN			(0x1u<<8)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT2_TXFE					(0x1u<<7)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT2_INEPNE				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT2_ITTXFE				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT2_TOC					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT2_EPDISD				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT2_XFRC					(0x1u<<0)

// OTG_HS_DIEPTSIZ2 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ2_MCNT				(0x3u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ2_MCNT_0				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ2_PKTCNT				(0x3FFu<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ2_PKTCNT_0			(0x1u<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ2_XFRSIZ				(0x7FFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ2_XFRSIZ_0			(0x1u<<0)

// OTG_HS_DIEPDMA3 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPDMA3_DMAADDR				(0xFFFFFFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPDMA3_DMAADDR_0			(0x1u<<0)

// OTG_HS_DTXFSTS2 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DTXFSTS2_INEPTFSAV			(0xFFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DTXFSTS2_INEPTFSAV_0			(0x1u<<0)

// OTG_HS_DIEPCTL3 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL3_EPENA				(0x1u<<31)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL3_EPDIS				(0x1u<<30)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL3_SODDFRM				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL3_SD0PID_SEVNFRM		(0x1u<<28)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL3_SNAK					(0x1u<<27)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL3_CNAK					(0x1u<<26)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL3_TXFNUM				(0xFu<<22)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL3_TXFNUM_0				(0x1u<<22)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL3_STALL				(0x1u<<21)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL3_EPTYP				(0x3u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL3_EPTYP_0				(0x1u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL3_NAKSTS				(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL3_EONUM_DPID			(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL3_USBAEP				(0x1u<<15)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL3_MPSIZ				(0x7FFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL3_MPSIZ_0				(0x1u<<0)

// OTG_HS_DIEPINT3 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT3_NAK					(0x1u<<13)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT3_BERR					(0x1u<<12)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT3_PKTDRPSTS			(0x1u<<11)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT3_BNA					(0x1u<<9)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT3_TXFIFOUDRN			(0x1u<<8)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT3_TXFE					(0x1u<<7)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT3_INEPNE				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT3_ITTXFE				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT3_TOC					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT3_EPDISD				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT3_XFRC					(0x1u<<0)

// OTG_HS_DIEPTSIZ3 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ3_MCNT				(0x3u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ3_MCNT_0				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ3_PKTCNT				(0x3FFu<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ3_PKTCNT_0			(0x1u<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ3_XFRSIZ				(0x7FFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ3_XFRSIZ_0			(0x1u<<0)

// OTG_HS_DIEPDMA4 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPDMA4_DMAADDR				(0xFFFFFFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPDMA4_DMAADDR_0			(0x1u<<0)

// OTG_HS_DTXFSTS3 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DTXFSTS3_INEPTFSAV			(0xFFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DTXFSTS3_INEPTFSAV_0			(0x1u<<0)

// OTG_HS_DIEPCTL4 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL4_EPENA				(0x1u<<31)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL4_EPDIS				(0x1u<<30)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL4_SODDFRM				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL4_SD0PID_SEVNFRM		(0x1u<<28)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL4_SNAK					(0x1u<<27)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL4_CNAK					(0x1u<<26)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL4_TXFNUM				(0xFu<<22)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL4_TXFNUM_0				(0x1u<<22)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL4_STALL				(0x1u<<21)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL4_EPTYP				(0x3u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL4_EPTYP_0				(0x1u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL4_NAKSTS				(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL4_EONUM_DPID			(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL4_USBAEP				(0x1u<<15)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL4_MPSIZ				(0x7FFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL4_MPSIZ_0				(0x1u<<0)

// OTG_HS_DIEPINT4 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT4_NAK					(0x1u<<13)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT4_BERR					(0x1u<<12)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT4_PKTDRPSTS			(0x1u<<11)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT4_BNA					(0x1u<<9)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT4_TXFIFOUDRN			(0x1u<<8)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT4_TXFE					(0x1u<<7)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT4_INEPNE				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT4_ITTXFE				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT4_TOC					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT4_EPDISD				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT4_XFRC					(0x1u<<0)

// OTG_HS_DIEPTSIZ4 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ4_MCNT				(0x3u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ4_MCNT_0				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ4_PKTCNT				(0x3FFu<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ4_PKTCNT_0			(0x1u<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ4_XFRSIZ				(0x7FFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ4_XFRSIZ_0			(0x1u<<0)

// OTG_HS_DIEPDMA5 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPDMA5_DMAADDR				(0xFFFFFFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPDMA5_DMAADDR_0			(0x1u<<0)

// OTG_HS_DTXFSTS4 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DTXFSTS4_INEPTFSAV			(0xFFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DTXFSTS4_INEPTFSAV_0			(0x1u<<0)

// OTG_HS_DIEPCTL5 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL5_EPENA				(0x1u<<31)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL5_EPDIS				(0x1u<<30)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL5_SODDFRM				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL5_SD0PID_SEVNFRM		(0x1u<<28)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL5_SNAK					(0x1u<<27)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL5_CNAK					(0x1u<<26)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL5_TXFNUM				(0xFu<<22)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL5_TXFNUM_0				(0x1u<<22)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL5_STALL				(0x1u<<21)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL5_EPTYP				(0x3u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL5_EPTYP_0				(0x1u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL5_NAKSTS				(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL5_EONUM_DPID			(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL5_USBAEP				(0x1u<<15)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL5_MPSIZ				(0x7FFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL5_MPSIZ_0				(0x1u<<0)

// OTG_HS_DIEPTSIZ6 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ6_MCNT				(0x3u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ6_MCNT_0				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ6_PKTCNT				(0x3FFu<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ6_PKTCNT_0			(0x1u<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ6_XFRSIZ				(0x7FFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ6_XFRSIZ_0			(0x1u<<0)

// OTG_HS_DTXFSTS6 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DTXFSTS6_INEPTFSAV			(0xFFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DTXFSTS6_INEPTFSAV_0			(0x1u<<0)

// OTG_HS_DIEPINT5 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT5_NAK					(0x1u<<13)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT5_BERR					(0x1u<<12)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT5_PKTDRPSTS			(0x1u<<11)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT5_BNA					(0x1u<<9)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT5_TXFIFOUDRN			(0x1u<<8)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT5_TXFE					(0x1u<<7)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT5_INEPNE				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT5_ITTXFE				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT5_TOC					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT5_EPDISD				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT5_XFRC					(0x1u<<0)

// OTG_HS_DIEPTSIZ7 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ7_MCNT				(0x3u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ7_MCNT_0				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ7_PKTCNT				(0x3FFu<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ7_PKTCNT_0			(0x1u<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ7_XFRSIZ				(0x7FFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ7_XFRSIZ_0			(0x1u<<0)

// OTG_HS_DTXFSTS7 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DTXFSTS7_INEPTFSAV			(0xFFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DTXFSTS7_INEPTFSAV_0			(0x1u<<0)

// OTG_HS_DIEPTSIZ5 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ5_MCNT				(0x3u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ5_MCNT_0				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ5_PKTCNT				(0x3FFu<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ5_PKTCNT_0			(0x1u<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ5_XFRSIZ				(0x7FFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPTSIZ5_XFRSIZ_0			(0x1u<<0)

// OTG_HS_DTXFSTS5 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DTXFSTS5_INEPTFSAV			(0xFFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DTXFSTS5_INEPTFSAV_0			(0x1u<<0)

// OTG_HS_DIEPCTL6 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL6_EPENA				(0x1u<<31)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL6_EPDIS				(0x1u<<30)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL6_SODDFRM				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL6_SD0PID_SEVNFRM		(0x1u<<28)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL6_SNAK					(0x1u<<27)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL6_CNAK					(0x1u<<26)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL6_TXFNUM				(0xFu<<22)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL6_TXFNUM_0				(0x1u<<22)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL6_STALL				(0x1u<<21)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL6_EPTYP				(0x3u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL6_EPTYP_0				(0x1u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL6_NAKSTS				(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL6_EONUM_DPID			(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL6_USBAEP				(0x1u<<15)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL6_MPSIZ				(0x7FFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL6_MPSIZ_0				(0x1u<<0)

// OTG_HS_DIEPINT6 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT6_NAK					(0x1u<<13)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT6_BERR					(0x1u<<12)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT6_PKTDRPSTS			(0x1u<<11)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT6_BNA					(0x1u<<9)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT6_TXFIFOUDRN			(0x1u<<8)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT6_TXFE					(0x1u<<7)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT6_INEPNE				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT6_ITTXFE				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT6_TOC					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT6_EPDISD				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT6_XFRC					(0x1u<<0)

// OTG_HS_DIEPCTL7 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL7_EPENA				(0x1u<<31)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL7_EPDIS				(0x1u<<30)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL7_SODDFRM				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL7_SD0PID_SEVNFRM		(0x1u<<28)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL7_SNAK					(0x1u<<27)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL7_CNAK					(0x1u<<26)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL7_TXFNUM				(0xFu<<22)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL7_TXFNUM_0				(0x1u<<22)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL7_STALL				(0x1u<<21)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL7_EPTYP				(0x3u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL7_EPTYP_0				(0x1u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL7_NAKSTS				(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL7_EONUM_DPID			(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL7_USBAEP				(0x1u<<15)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL7_MPSIZ				(0x7FFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPCTL7_MPSIZ_0				(0x1u<<0)

// OTG_HS_DIEPINT7 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT7_NAK					(0x1u<<13)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT7_BERR					(0x1u<<12)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT7_PKTDRPSTS			(0x1u<<11)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT7_BNA					(0x1u<<9)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT7_TXFIFOUDRN			(0x1u<<8)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT7_TXFE					(0x1u<<7)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT7_INEPNE				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT7_ITTXFE				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT7_TOC					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT7_EPDISD				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DIEPINT7_XFRC					(0x1u<<0)

// OTG_HS_DOEPCTL0 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL0_EPENA				(0x1u<<31)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL0_EPDIS				(0x1u<<30)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL0_SNAK					(0x1u<<27)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL0_CNAK					(0x1u<<26)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL0_STALL				(0x1u<<21)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL0_SNPM					(0x1u<<20)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL0_EPTYP				(0x3u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL0_EPTYP_0				(0x1u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL0_NAKSTS				(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL0_USBAEP				(0x1u<<15)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL0_MPSIZ				(0x3u<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL0_MPSIZ_0				(0x1u<<0)

// OTG_HS_DOEPINT0 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT0_NYET					(0x1u<<14)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT0_B2BSTUP				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT0_OTEPDIS				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT0_STUP					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT0_EPDISD				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT0_XFRC					(0x1u<<0)

// OTG_HS_DOEPTSIZ0 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ0_STUPCNT				(0x3u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ0_STUPCNT_0			(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ0_PKTCNT				(0x1u<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ0_XFRSIZ				(0x7Fu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ0_XFRSIZ_0			(0x1u<<0)

// OTG_HS_DOEPCTL1 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL1_EPENA				(0x1u<<31)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL1_EPDIS				(0x1u<<30)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL1_SODDFRM				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL1_SD0PID_SEVNFRM		(0x1u<<28)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL1_SNAK					(0x1u<<27)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL1_CNAK					(0x1u<<26)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL1_STALL				(0x1u<<21)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL1_SNPM					(0x1u<<20)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL1_EPTYP				(0x3u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL1_EPTYP_0				(0x1u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL1_NAKSTS				(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL1_EONUM_DPID			(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL1_USBAEP				(0x1u<<15)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL1_MPSIZ				(0x7FFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL1_MPSIZ_0				(0x1u<<0)

// OTG_HS_DOEPINT1 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT1_NYET					(0x1u<<14)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT1_B2BSTUP				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT1_OTEPDIS				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT1_STUP					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT1_EPDISD				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT1_XFRC					(0x1u<<0)

// OTG_HS_DOEPTSIZ1 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ1_RXDPID_STUPCNT		(0x3u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ1_RXDPID_STUPCNT_0	(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ1_PKTCNT				(0x3FFu<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ1_PKTCNT_0			(0x1u<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ1_XFRSIZ				(0x7FFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ1_XFRSIZ_0			(0x1u<<0)

// OTG_HS_DOEPCTL2 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL2_EPENA				(0x1u<<31)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL2_EPDIS				(0x1u<<30)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL2_SODDFRM				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL2_SD0PID_SEVNFRM		(0x1u<<28)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL2_SNAK					(0x1u<<27)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL2_CNAK					(0x1u<<26)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL2_STALL				(0x1u<<21)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL2_SNPM					(0x1u<<20)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL2_EPTYP				(0x3u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL2_EPTYP_0				(0x1u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL2_NAKSTS				(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL2_EONUM_DPID			(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL2_USBAEP				(0x1u<<15)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL2_MPSIZ				(0x7FFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL2_MPSIZ_0				(0x1u<<0)

// OTG_HS_DOEPINT2 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT2_NYET					(0x1u<<14)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT2_B2BSTUP				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT2_OTEPDIS				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT2_STUP					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT2_EPDISD				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT2_XFRC					(0x1u<<0)

// OTG_HS_DOEPTSIZ2 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ2_RXDPID_STUPCNT		(0x3u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ2_RXDPID_STUPCNT_0	(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ2_PKTCNT				(0x3FFu<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ2_PKTCNT_0			(0x1u<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ2_XFRSIZ				(0x7FFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ2_XFRSIZ_0			(0x1u<<0)

// OTG_HS_DOEPCTL3 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL3_EPENA				(0x1u<<31)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL3_EPDIS				(0x1u<<30)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL3_SODDFRM				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL3_SD0PID_SEVNFRM		(0x1u<<28)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL3_SNAK					(0x1u<<27)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL3_CNAK					(0x1u<<26)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL3_STALL				(0x1u<<21)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL3_SNPM					(0x1u<<20)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL3_EPTYP				(0x3u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL3_EPTYP_0				(0x1u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL3_NAKSTS				(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL3_EONUM_DPID			(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL3_USBAEP				(0x1u<<15)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL3_MPSIZ				(0x7FFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL3_MPSIZ_0				(0x1u<<0)

// OTG_HS_DOEPINT3 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT3_NYET					(0x1u<<14)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT3_B2BSTUP				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT3_OTEPDIS				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT3_STUP					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT3_EPDISD				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT3_XFRC					(0x1u<<0)

// OTG_HS_DOEPTSIZ3 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ3_RXDPID_STUPCNT		(0x3u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ3_RXDPID_STUPCNT_0	(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ3_PKTCNT				(0x3FFu<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ3_PKTCNT_0			(0x1u<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ3_XFRSIZ				(0x7FFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ3_XFRSIZ_0			(0x1u<<0)

// OTG_HS_DOEPCTL4 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL4_EPENA				(0x1u<<31)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL4_EPDIS				(0x1u<<30)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL4_SODDFRM				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL4_SD0PID_SEVNFRM		(0x1u<<28)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL4_SNAK					(0x1u<<27)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL4_CNAK					(0x1u<<26)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL4_STALL				(0x1u<<21)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL4_SNPM					(0x1u<<20)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL4_EPTYP				(0x3u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL4_EPTYP_0				(0x1u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL4_NAKSTS				(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL4_EONUM_DPID			(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL4_USBAEP				(0x1u<<15)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL4_MPSIZ				(0x7FFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL4_MPSIZ_0				(0x1u<<0)

// OTG_HS_DOEPINT4 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT4_NYET					(0x1u<<14)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT4_B2BSTUP				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT4_OTEPDIS				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT4_STUP					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT4_EPDISD				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT4_XFRC					(0x1u<<0)

// OTG_HS_DOEPTSIZ4 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ4_RXDPID_STUPCNT		(0x3u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ4_RXDPID_STUPCNT_0	(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ4_PKTCNT				(0x3FFu<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ4_PKTCNT_0			(0x1u<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ4_XFRSIZ				(0x7FFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ4_XFRSIZ_0			(0x1u<<0)

// OTG_HS_DOEPCTL5 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL5_EPENA				(0x1u<<31)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL5_EPDIS				(0x1u<<30)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL5_SODDFRM				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL5_SD0PID_SEVNFRM		(0x1u<<28)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL5_SNAK					(0x1u<<27)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL5_CNAK					(0x1u<<26)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL5_STALL				(0x1u<<21)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL5_SNPM					(0x1u<<20)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL5_EPTYP				(0x3u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL5_EPTYP_0				(0x1u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL5_NAKSTS				(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL5_EONUM_DPID			(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL5_USBAEP				(0x1u<<15)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL5_MPSIZ				(0x7FFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL5_MPSIZ_0				(0x1u<<0)

// OTG_HS_DOEPINT5 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT5_NYET					(0x1u<<14)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT5_B2BSTUP				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT5_OTEPDIS				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT5_STUP					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT5_EPDISD				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT5_XFRC					(0x1u<<0)

// OTG_HS_DOEPTSIZ5 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ5_RXDPID_STUPCNT		(0x3u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ5_RXDPID_STUPCNT_0	(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ5_PKTCNT				(0x3FFu<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ5_PKTCNT_0			(0x1u<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ5_XFRSIZ				(0x7FFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ5_XFRSIZ_0			(0x1u<<0)

// OTG_HS_DOEPCTL6 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL6_EPENA				(0x1u<<31)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL6_EPDIS				(0x1u<<30)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL6_SODDFRM				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL6_SD0PID_SEVNFRM		(0x1u<<28)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL6_SNAK					(0x1u<<27)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL6_CNAK					(0x1u<<26)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL6_STALL				(0x1u<<21)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL6_SNPM					(0x1u<<20)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL6_EPTYP				(0x3u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL6_EPTYP_0				(0x1u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL6_NAKSTS				(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL6_EONUM_DPID			(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL6_USBAEP				(0x1u<<15)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL6_MPSIZ				(0x7FFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL6_MPSIZ_0				(0x1u<<0)

// OTG_HS_DOEPINT6 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT6_NYET					(0x1u<<14)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT6_B2BSTUP				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT6_OTEPDIS				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT6_STUP					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT6_EPDISD				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT6_XFRC					(0x1u<<0)

// OTG_HS_DOEPTSIZ6 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ6_RXDPID_STUPCNT		(0x3u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ6_RXDPID_STUPCNT_0	(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ6_PKTCNT				(0x3FFu<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ6_PKTCNT_0			(0x1u<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ6_XFRSIZ				(0x7FFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ6_XFRSIZ_0			(0x1u<<0)

// OTG_HS_DOEPCTL7 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL7_EPENA				(0x1u<<31)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL7_EPDIS				(0x1u<<30)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL7_SODDFRM				(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL7_SD0PID_SEVNFRM		(0x1u<<28)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL7_SNAK					(0x1u<<27)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL7_CNAK					(0x1u<<26)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL7_STALL				(0x1u<<21)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL7_SNPM					(0x1u<<20)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL7_EPTYP				(0x3u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL7_EPTYP_0				(0x1u<<18)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL7_NAKSTS				(0x1u<<17)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL7_EONUM_DPID			(0x1u<<16)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL7_USBAEP				(0x1u<<15)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL7_MPSIZ				(0x7FFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPCTL7_MPSIZ_0				(0x1u<<0)

// OTG_HS_DOEPINT7 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT7_NYET					(0x1u<<14)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT7_B2BSTUP				(0x1u<<6)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT7_OTEPDIS				(0x1u<<4)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT7_STUP					(0x1u<<3)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT7_EPDISD				(0x1u<<1)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPINT7_XFRC					(0x1u<<0)

// OTG_HS_DOEPTSIZ7 Configuration

#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ7_RXDPID_STUPCNT		(0x3u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ7_RXDPID_STUPCNT_0	(0x1u<<29)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ7_PKTCNT				(0x3FFu<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ7_PKTCNT_0			(0x1u<<19)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ7_XFRSIZ				(0x7FFFFu<<0)
#define	OTG1_HS_DEVICE_OTG_HS_DOEPTSIZ7_XFRSIZ_0			(0x1u<<0)
