/*
; RP2350_busctrl.
; ===============

; SPDX-License-Identifier: MIT

;------------------------------------------------------------------------
; Author:	Generated using the .svd description	The 2025-01-01
; Modifs:
;
; Project:	uKOS-X
; Goal:		RP2350_busctrl equates.
;
;   (c) 2025-2026, Edo. Franzi
;   --------------------------
;                                              __ ______  _____
;   Edo. Franzi                         __  __/ //_/ __ \/ ___/
;   5-Route de Cheseaux                / / / / ,< / / / /\__ \
;   CH 1400 Cheseaux-Noréaz           / /_/ / /| / /_/ /___/ /
;                                     \__,_/_/ |_\____//____/
;   edo.franzi@ukos.ch
;
;   Description: Lightweight, real-time multitasking operating
;   system for embedded microcontroller and DSP-based systems.
;
;   Permission is hereby granted, free of charge, to any person
;   obtaining a copy of this software and associated documentation
;   files (the "Software"), to deal in the Software without restriction,
;   including without limitation the rights to use, copy, modify,
;   merge, publish, distribute, sublicense, and/or sell copies of the
;   Software, and to permit persons to whom the Software is furnished
;   to do so, subject to the following conditions:
;
;   The above copyright notice and this permission notice shall be
;   included in all copies or substantial portions of the Software.
;
;   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
;   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
;   BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
;   ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
;   CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
;   SOFTWARE.
;
;------------------------------------------------------------------------
*/

#pragma	once

// BUSCTRL address definitions
// ---------------------------

typedef struct {
	volatile	uint32_t	BUS_PRIORITY;
	volatile	uint32_t	BUS_PRIORITY_ACK;
	volatile	uint32_t	PERFCTR_EN;
	volatile	uint32_t	PERFCTR0;
	volatile	uint32_t	PERFSEL0;
	volatile	uint32_t	PERFCTR1;
	volatile	uint32_t	PERFSEL1;
	volatile	uint32_t	PERFCTR2;
	volatile	uint32_t	PERFSEL2;
	volatile	uint32_t	PERFCTR3;
	volatile	uint32_t	PERFSEL3;
} BUSCTRL_TypeDef;

#if (defined(__cplusplus))
#define	BUSCTRL_NS	reinterpret_cast<BUSCTRL_TypeDef *>(0x40068000u)
#define	BUSCTRL_S	reinterpret_cast<BUSCTRL_TypeDef *>(0x40068000u)
#else
#define	BUSCTRL_NS	((BUSCTRL_TypeDef *)0x40068000u)
#define	BUSCTRL_S	((BUSCTRL_TypeDef *)0x40068000u)
#endif

// BUS_PRIORITY Configuration

#define	BUSCTRL_BUS_PRIORITY_PROC0								(0x1u<<0)
#define	BUSCTRL_BUS_PRIORITY_PROC1								(0x1u<<4)
#define	BUSCTRL_BUS_PRIORITY_DMA_R								(0x1u<<8)
#define	BUSCTRL_BUS_PRIORITY_DMA_W								(0x1u<<12)

// BUS_PRIORITY_ACK Configuration

#define	BUSCTRL_BUS_PRIORITY_ACK_BUS_PRIORITY_ACK				(0x1u<<0)

// PERFCTR_EN Configuration

#define	BUSCTRL_PERFCTR_EN_PERFCTR_EN							(0x1u<<0)

// PERFCTR0 Configuration

#define	BUSCTRL_PERFCTR0_PERFCTR0								(0xFFFFFFu<<0)
#define	BUSCTRL_PERFCTR0_PERFCTR0_0								(0x1u<<0)

// PERFSEL0 Configuration

#define	BUSCTRL_PERFSEL0_PERFSEL0								(0x7Fu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_0								(0x1u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SIOB_PROC1_STALL_UPSTREAM		(0x0u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SIOB_PROC1_STALL_DOWNSTREAM	(0x1u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SIOB_PROC1_ACCESS_CONTESTED	(0x2u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SIOB_PROC1_ACCESS				(0x3u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SIOB_PROC0_STALL_UPSTREAM		(0x4u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SIOB_PROC0_STALL_DOWNSTREAM	(0x5u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SIOB_PROC0_ACCESS_CONTESTED	(0x6u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SIOB_PROC0_ACCESS				(0x7u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_APB_STALL_UPSTREAM			(0x8u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_APB_STALL_DOWNSTREAM			(0x9u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_APB_ACCESS_CONTESTED			(0xAu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_APB_ACCESS					(0xBu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_FASTPERI_STALL_UPSTREAM		(0xCu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_FASTPERI_STALL_DOWNSTREAM		(0xDu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_FASTPERI_ACCESS_CONTESTED		(0xEu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_FASTPERI_ACCESS				(0xFu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM9_STALL_UPSTREAM			(0x10u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM9_STALL_DOWNSTREAM		(0x11u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM9_ACCESS_CONTESTED		(0x12u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM9_ACCESS					(0x13u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM8_STALL_UPSTREAM			(0x14u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM8_STALL_DOWNSTREAM		(0x15u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM8_ACCESS_CONTESTED		(0x16u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM8_ACCESS					(0x17u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM7_STALL_UPSTREAM			(0x18u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM7_STALL_DOWNSTREAM		(0x19u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM7_ACCESS_CONTESTED		(0x1Au<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM7_ACCESS					(0x1Bu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM6_STALL_UPSTREAM			(0x1Cu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM6_STALL_DOWNSTREAM		(0x1Du<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM6_ACCESS_CONTESTED		(0x1Eu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM6_ACCESS					(0x1Fu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM5_STALL_UPSTREAM			(0x20u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM5_STALL_DOWNSTREAM		(0x21u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM5_ACCESS_CONTESTED		(0x22u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM5_ACCESS					(0x23u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM4_STALL_UPSTREAM			(0x24u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM4_STALL_DOWNSTREAM		(0x25u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM4_ACCESS_CONTESTED		(0x26u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM4_ACCESS					(0x27u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM3_STALL_UPSTREAM			(0x28u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM3_STALL_DOWNSTREAM		(0x29u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM3_ACCESS_CONTESTED		(0x2Au<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM3_ACCESS					(0x2Bu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM2_STALL_UPSTREAM			(0x2Cu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM2_STALL_DOWNSTREAM		(0x2Du<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM2_ACCESS_CONTESTED		(0x2Eu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM2_ACCESS					(0x2Fu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM1_STALL_UPSTREAM			(0x30u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM1_STALL_DOWNSTREAM		(0x31u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM1_ACCESS_CONTESTED		(0x32u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM1_ACCESS					(0x33u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM0_STALL_UPSTREAM			(0x34u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM0_STALL_DOWNSTREAM		(0x35u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM0_ACCESS_CONTESTED		(0x36u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_SRAM0_ACCESS					(0x37u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_XIP_MAIN1_STALL_UPSTREAM		(0x38u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_XIP_MAIN1_STALL_DOWNSTREAM	(0x39u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_XIP_MAIN1_ACCESS_CONTESTED	(0x3Au<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_XIP_MAIN1_ACCESS				(0x3Bu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_XIP_MAIN0_STALL_UPSTREAM		(0x3Cu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_XIP_MAIN0_STALL_DOWNSTREAM	(0x3Du<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_XIP_MAIN0_ACCESS_CONTESTED	(0x3Eu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_XIP_MAIN0_ACCESS				(0x3Fu<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_ROM_STALL_UPSTREAM			(0x40u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_ROM_STALL_DOWNSTREAM			(0x41u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_ROM_ACCESS_CONTESTED			(0x42u<<0)
#define	BUSCTRL_PERFSEL0_PERFSEL0_ROM_ACCESS					(0x43u<<0)

// PERFCTR1 Configuration

#define	BUSCTRL_PERFCTR1_PERFCTR1								(0xFFFFFFu<<0)
#define	BUSCTRL_PERFCTR1_PERFCTR1_0								(0x1u<<0)

// PERFSEL1 Configuration

#define	BUSCTRL_PERFSEL1_PERFSEL1								(0x7Fu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_0								(0x1u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SIOB_PROC1_STALL_UPSTREAM		(0x0u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SIOB_PROC1_STALL_DOWNSTREAM	(0x1u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SIOB_PROC1_ACCESS_CONTESTED	(0x2u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SIOB_PROC1_ACCESS				(0x3u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SIOB_PROC0_STALL_UPSTREAM		(0x4u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SIOB_PROC0_STALL_DOWNSTREAM	(0x5u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SIOB_PROC0_ACCESS_CONTESTED	(0x6u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SIOB_PROC0_ACCESS				(0x7u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_APB_STALL_UPSTREAM			(0x8u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_APB_STALL_DOWNSTREAM			(0x9u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_APB_ACCESS_CONTESTED			(0xAu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_APB_ACCESS					(0xBu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_FASTPERI_STALL_UPSTREAM		(0xCu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_FASTPERI_STALL_DOWNSTREAM		(0xDu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_FASTPERI_ACCESS_CONTESTED		(0xEu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_FASTPERI_ACCESS				(0xFu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM9_STALL_UPSTREAM			(0x10u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM9_STALL_DOWNSTREAM		(0x11u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM9_ACCESS_CONTESTED		(0x12u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM9_ACCESS					(0x13u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM8_STALL_UPSTREAM			(0x14u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM8_STALL_DOWNSTREAM		(0x15u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM8_ACCESS_CONTESTED		(0x16u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM8_ACCESS					(0x17u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM7_STALL_UPSTREAM			(0x18u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM7_STALL_DOWNSTREAM		(0x19u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM7_ACCESS_CONTESTED		(0x1Au<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM7_ACCESS					(0x1Bu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM6_STALL_UPSTREAM			(0x1Cu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM6_STALL_DOWNSTREAM		(0x1Du<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM6_ACCESS_CONTESTED		(0x1Eu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM6_ACCESS					(0x1Fu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM5_STALL_UPSTREAM			(0x20u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM5_STALL_DOWNSTREAM		(0x21u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM5_ACCESS_CONTESTED		(0x22u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM5_ACCESS					(0x23u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM4_STALL_UPSTREAM			(0x24u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM4_STALL_DOWNSTREAM		(0x25u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM4_ACCESS_CONTESTED		(0x26u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM4_ACCESS					(0x27u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM3_STALL_UPSTREAM			(0x28u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM3_STALL_DOWNSTREAM		(0x29u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM3_ACCESS_CONTESTED		(0x2Au<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM3_ACCESS					(0x2Bu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM2_STALL_UPSTREAM			(0x2Cu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM2_STALL_DOWNSTREAM		(0x2Du<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM2_ACCESS_CONTESTED		(0x2Eu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM2_ACCESS					(0x2Fu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM1_STALL_UPSTREAM			(0x30u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM1_STALL_DOWNSTREAM		(0x31u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM1_ACCESS_CONTESTED		(0x32u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM1_ACCESS					(0x33u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM0_STALL_UPSTREAM			(0x34u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM0_STALL_DOWNSTREAM		(0x35u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM0_ACCESS_CONTESTED		(0x36u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_SRAM0_ACCESS					(0x37u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_XIP_MAIN1_STALL_UPSTREAM		(0x38u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_XIP_MAIN1_STALL_DOWNSTREAM	(0x39u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_XIP_MAIN1_ACCESS_CONTESTED	(0x3Au<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_XIP_MAIN1_ACCESS				(0x3Bu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_XIP_MAIN0_STALL_UPSTREAM		(0x3Cu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_XIP_MAIN0_STALL_DOWNSTREAM	(0x3Du<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_XIP_MAIN0_ACCESS_CONTESTED	(0x3Eu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_XIP_MAIN0_ACCESS				(0x3Fu<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_ROM_STALL_UPSTREAM			(0x40u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_ROM_STALL_DOWNSTREAM			(0x41u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_ROM_ACCESS_CONTESTED			(0x42u<<0)
#define	BUSCTRL_PERFSEL1_PERFSEL1_ROM_ACCESS					(0x43u<<0)

// PERFCTR2 Configuration

#define	BUSCTRL_PERFCTR2_PERFCTR2								(0xFFFFFFu<<0)
#define	BUSCTRL_PERFCTR2_PERFCTR2_0								(0x1u<<0)

// PERFSEL2 Configuration

#define	BUSCTRL_PERFSEL2_PERFSEL2								(0x7Fu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_0								(0x1u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SIOB_PROC1_STALL_UPSTREAM		(0x0u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SIOB_PROC1_STALL_DOWNSTREAM	(0x1u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SIOB_PROC1_ACCESS_CONTESTED	(0x2u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SIOB_PROC1_ACCESS				(0x3u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SIOB_PROC0_STALL_UPSTREAM		(0x4u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SIOB_PROC0_STALL_DOWNSTREAM	(0x5u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SIOB_PROC0_ACCESS_CONTESTED	(0x6u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SIOB_PROC0_ACCESS				(0x7u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_APB_STALL_UPSTREAM			(0x8u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_APB_STALL_DOWNSTREAM			(0x9u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_APB_ACCESS_CONTESTED			(0xAu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_APB_ACCESS					(0xBu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_FASTPERI_STALL_UPSTREAM		(0xCu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_FASTPERI_STALL_DOWNSTREAM		(0xDu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_FASTPERI_ACCESS_CONTESTED		(0xEu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_FASTPERI_ACCESS				(0xFu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM9_STALL_UPSTREAM			(0x10u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM9_STALL_DOWNSTREAM		(0x11u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM9_ACCESS_CONTESTED		(0x12u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM9_ACCESS					(0x13u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM8_STALL_UPSTREAM			(0x14u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM8_STALL_DOWNSTREAM		(0x15u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM8_ACCESS_CONTESTED		(0x16u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM8_ACCESS					(0x17u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM7_STALL_UPSTREAM			(0x18u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM7_STALL_DOWNSTREAM		(0x19u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM7_ACCESS_CONTESTED		(0x1Au<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM7_ACCESS					(0x1Bu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM6_STALL_UPSTREAM			(0x1Cu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM6_STALL_DOWNSTREAM		(0x1Du<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM6_ACCESS_CONTESTED		(0x1Eu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM6_ACCESS					(0x1Fu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM5_STALL_UPSTREAM			(0x20u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM5_STALL_DOWNSTREAM		(0x21u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM5_ACCESS_CONTESTED		(0x22u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM5_ACCESS					(0x23u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM4_STALL_UPSTREAM			(0x24u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM4_STALL_DOWNSTREAM		(0x25u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM4_ACCESS_CONTESTED		(0x26u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM4_ACCESS					(0x27u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM3_STALL_UPSTREAM			(0x28u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM3_STALL_DOWNSTREAM		(0x29u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM3_ACCESS_CONTESTED		(0x2Au<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM3_ACCESS					(0x2Bu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM2_STALL_UPSTREAM			(0x2Cu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM2_STALL_DOWNSTREAM		(0x2Du<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM2_ACCESS_CONTESTED		(0x2Eu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM2_ACCESS					(0x2Fu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM1_STALL_UPSTREAM			(0x30u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM1_STALL_DOWNSTREAM		(0x31u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM1_ACCESS_CONTESTED		(0x32u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM1_ACCESS					(0x33u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM0_STALL_UPSTREAM			(0x34u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM0_STALL_DOWNSTREAM		(0x35u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM0_ACCESS_CONTESTED		(0x36u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_SRAM0_ACCESS					(0x37u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_XIP_MAIN1_STALL_UPSTREAM		(0x38u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_XIP_MAIN1_STALL_DOWNSTREAM	(0x39u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_XIP_MAIN1_ACCESS_CONTESTED	(0x3Au<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_XIP_MAIN1_ACCESS				(0x3Bu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_XIP_MAIN0_STALL_UPSTREAM		(0x3Cu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_XIP_MAIN0_STALL_DOWNSTREAM	(0x3Du<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_XIP_MAIN0_ACCESS_CONTESTED	(0x3Eu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_XIP_MAIN0_ACCESS				(0x3Fu<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_ROM_STALL_UPSTREAM			(0x40u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_ROM_STALL_DOWNSTREAM			(0x41u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_ROM_ACCESS_CONTESTED			(0x42u<<0)
#define	BUSCTRL_PERFSEL2_PERFSEL2_ROM_ACCESS					(0x43u<<0)

// PERFCTR3 Configuration

#define	BUSCTRL_PERFCTR3_PERFCTR3								(0xFFFFFFu<<0)
#define	BUSCTRL_PERFCTR3_PERFCTR3_0								(0x1u<<0)

// PERFSEL3 Configuration

#define	BUSCTRL_PERFSEL3_PERFSEL3								(0x7Fu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_0								(0x1u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SIOB_PROC1_STALL_UPSTREAM		(0x0u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SIOB_PROC1_STALL_DOWNSTREAM	(0x1u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SIOB_PROC1_ACCESS_CONTESTED	(0x2u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SIOB_PROC1_ACCESS				(0x3u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SIOB_PROC0_STALL_UPSTREAM		(0x4u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SIOB_PROC0_STALL_DOWNSTREAM	(0x5u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SIOB_PROC0_ACCESS_CONTESTED	(0x6u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SIOB_PROC0_ACCESS				(0x7u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_APB_STALL_UPSTREAM			(0x8u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_APB_STALL_DOWNSTREAM			(0x9u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_APB_ACCESS_CONTESTED			(0xAu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_APB_ACCESS					(0xBu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_FASTPERI_STALL_UPSTREAM		(0xCu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_FASTPERI_STALL_DOWNSTREAM		(0xDu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_FASTPERI_ACCESS_CONTESTED		(0xEu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_FASTPERI_ACCESS				(0xFu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM9_STALL_UPSTREAM			(0x10u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM9_STALL_DOWNSTREAM		(0x11u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM9_ACCESS_CONTESTED		(0x12u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM9_ACCESS					(0x13u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM8_STALL_UPSTREAM			(0x14u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM8_STALL_DOWNSTREAM		(0x15u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM8_ACCESS_CONTESTED		(0x16u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM8_ACCESS					(0x17u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM7_STALL_UPSTREAM			(0x18u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM7_STALL_DOWNSTREAM		(0x19u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM7_ACCESS_CONTESTED		(0x1Au<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM7_ACCESS					(0x1Bu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM6_STALL_UPSTREAM			(0x1Cu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM6_STALL_DOWNSTREAM		(0x1Du<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM6_ACCESS_CONTESTED		(0x1Eu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM6_ACCESS					(0x1Fu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM5_STALL_UPSTREAM			(0x20u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM5_STALL_DOWNSTREAM		(0x21u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM5_ACCESS_CONTESTED		(0x22u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM5_ACCESS					(0x23u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM4_STALL_UPSTREAM			(0x24u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM4_STALL_DOWNSTREAM		(0x25u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM4_ACCESS_CONTESTED		(0x26u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM4_ACCESS					(0x27u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM3_STALL_UPSTREAM			(0x28u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM3_STALL_DOWNSTREAM		(0x29u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM3_ACCESS_CONTESTED		(0x2Au<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM3_ACCESS					(0x2Bu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM2_STALL_UPSTREAM			(0x2Cu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM2_STALL_DOWNSTREAM		(0x2Du<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM2_ACCESS_CONTESTED		(0x2Eu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM2_ACCESS					(0x2Fu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM1_STALL_UPSTREAM			(0x30u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM1_STALL_DOWNSTREAM		(0x31u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM1_ACCESS_CONTESTED		(0x32u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM1_ACCESS					(0x33u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM0_STALL_UPSTREAM			(0x34u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM0_STALL_DOWNSTREAM		(0x35u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM0_ACCESS_CONTESTED		(0x36u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_SRAM0_ACCESS					(0x37u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_XIP_MAIN1_STALL_UPSTREAM		(0x38u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_XIP_MAIN1_STALL_DOWNSTREAM	(0x39u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_XIP_MAIN1_ACCESS_CONTESTED	(0x3Au<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_XIP_MAIN1_ACCESS				(0x3Bu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_XIP_MAIN0_STALL_UPSTREAM		(0x3Cu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_XIP_MAIN0_STALL_DOWNSTREAM	(0x3Du<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_XIP_MAIN0_ACCESS_CONTESTED	(0x3Eu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_XIP_MAIN0_ACCESS				(0x3Fu<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_ROM_STALL_UPSTREAM			(0x40u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_ROM_STALL_DOWNSTREAM			(0x41u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_ROM_ACCESS_CONTESTED			(0x42u<<0)
#define	BUSCTRL_PERFSEL3_PERFSEL3_ROM_ACCESS					(0x43u<<0)
