/*
 * SPDX-License-Identifier: MIT
 * SPDX-FileCopyrightText: 2025-2026 Edo. Franzi
 *
 * Goal:        Demo of a C application.
 *          TensorFlow classifier.
 */

#include    <stdlib.h>
#include    <math.h>
#include    <cinttypes>

#include    "kern/kern.h"
#include    "serial/serial.h"
#include    "types.h"
#include    "ui.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wconversion"
#pragma GCC diagnostic ignored "-Wcast-align"
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wswitch-default"
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#pragma GCC diagnostic ignored "-Wpedantic"
#include    "tensorflow/lite/core/c/common.h"
#include    "tensorflow/lite/micro/micro_interpreter.h"
#include    "tensorflow/lite/micro/micro_log.h"
#include    "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include    "tensorflow/lite/micro/micro_profiler.h"
#include    "tensorflow/lite/micro/recording_micro_interpreter.h"
#include    "tensorflow/lite/micro/system_setup.h"
#include    "tensorflow/lite/schema/schema_generated.h"
#include    "tensorflow/lite/micro/cortex_m_generic/debug_log_callback.h"

#pragma GCC diagnostic pop

// TFLite model generated by xxd

#include    "./_Training/mlp_model.c_inc"

// Prototypes

extern "C" {
void    ui_drawTensorFlowExecutionTime(const char_t *s);
}

// Suggested memory allocation

constexpr   int         KTENSOR_ARENA_SIZE = (128 * 1024);
namespace {
            uint8_t     tensor_arena[KTENSOR_ARENA_SIZE];
}

// Operators necessary for the model

namespace {
void RegisterOps(tflite::MicroMutableOpResolver<13>& resolver) {

    resolver.AddResizeNearestNeighbor();
    resolver.AddConv2D();
    resolver.AddFullyConnected();
    resolver.AddRelu();
    resolver.AddTanh();
    resolver.AddReshape();
    resolver.AddShape();
    resolver.AddStridedSlice();
    resolver.AddPack();
    resolver.AddAdd();
    resolver.AddMul();
    resolver.AddConcatenation();}
}
namespace {
void    debuglog(const char *s) {

    (void)dprintf(KSYST, "%s\n", s);
}
}

namespace tfl {

/*
 * \brief tfl_init
 *
 * - Initialise the used resources
 *
 */
void    tfl_init(void) {

    RegisterDebugLogCallback(debuglog);
}

/*
 * \brief tfl_classify
 *
 * - Classify a data vector
 *
 */
void    tfl_classify(float32_t *entry, uint8_t *face) {
    TfLiteTensor    *input;
    TfLiteTensor    *output;
    uint64_t        time[2];
    int32_t         q;
    uint32_t        i, delta = 0u;
    char_t          text[40];

// Load the TFLite model

    const tflite::Model *model = tflite::GetModel(mlp_model_tflite);
    if (model->version() != TFLITE_SCHEMA_VERSION) {
        (void)dprintf(KSYST, "Error : Model version not compatible\n");
        exit(EXIT_OS_FAILURE);
    }

// Create the resolver operator
// Create the micro interpreter

    tflite::MicroMutableOpResolver<13> resolver;
    RegisterOps(resolver);
    tflite::MicroInterpreter interpreter(model, resolver, tensor_arena, KTENSOR_ARENA_SIZE);

// Allocate for the tensors

    if (interpreter.AllocateTensors() != kTfLiteOk) {
        (void)dprintf(KSYST, "Error: Tensor allocation!\n");
        exit(EXIT_OS_FAILURE);
    }

// Prepare the inputs

    kern_readTickCount(&time[0]);
    input = interpreter.input(0);
    for (i = 0u; i < 64u; i++) {

    q = (int32_t)roundf(entry[i] / input->params.scale) + input->params.zero_point;

    if (q < -128) { q = -128; }
    if (q >  127) { q =  127; }

    input->data.int8[i] = (int8_t)q;
}
    if (interpreter.Invoke() != kTfLiteOk) {
        (void)dprintf(KSYST, "Error: Excecution!\n");
        exit(EXIT_OS_FAILURE);
    }

// Return the face

    output = interpreter.output(0);

    for (i = 0u; i < (KFACE_SRC_W * KFACE_SRC_H); i++) {
        face[i] = (uint8_t)(output->data.int8[i] + 128);
    }
    kern_readTickCount(&time[1]);
    delta = (uint32_t)(time[1] - time[0]);

    (void)snprintf(text, sizeof(text), "Ex. time: %" PRIu32 " [us]", delta);
    ui_drawTensorFlowExecutionTime(text);
}
}
