# makefile.
# =========

# SPDX-License-Identifier: MIT

#------------------------------------------------------------------------
# Author:	Edo. Franzi		The 2025-01-01
# Modifs:
#
# Project:	uKOS-X
# Goal:		makefile for building the Sysquake viewer.so extension
#
#   (c) 2025-2026, Edo. Franzi
#   --------------------------
#                                              __ ______  _____
#   Edo. Franzi                         __  __/ //_/ __ \/ ___/
#   5-Route de Cheseaux                / / / / ,< / / / /\__ \
#   CH 1400 Cheseaux-Noréaz           / /_/ / /| / /_/ /___/ /
#                                     \__,_/_/ |_\____//____/
#   edo.franzi@ukos.ch
#
#   Description: Lightweight, real-time multitasking operating
#   system for embedded microcontroller and DSP-based systems.
#
#   Permission is hereby granted, free of charge, to any person
#   obtaining a copy of this software and associated documentation
#   files (the "Software"), to deal in the Software without restriction,
#   including without limitation the rights to use, copy, modify,
#   merge, publish, distribute, sublicense, and/or sell copies of the
#   Software, and to permit persons to whom the Software is furnished
#   to do so, subject to the following conditions:
#
#   The above copyright notice and this permission notice shall be
#   included in all copies or substantial portions of the Software.
#
#   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
#   BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
#   ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
#   CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#   SOFTWARE.
#
#------------------------------------------------------------------------

SHELL			= /bin/sh

ifndef PATH_UKOS_X_PACKAGE
    $(error PATH_UKOS_X_PACKAGE is not defined)
endif

PATH_D2XX		= $(PATH_TOOLS_ROOT)/local
PATH_SQEX		= ~/Library/Calerga/LMEExt
PATH_LME		= '/Applications/Sysquake Pro 6.5/Sysquake Pro.app/Contents/Resources/include'

CFLAGS			=  -DLMEIntSizeIs64
CFLAGS			+= -I$(PATH_D2XX)/include
CFLAGS			+= -I$(PATH_UKOS_X_PACKAGE)/OS/Includes
CFLAGS			+= -I$(PATH_LME)
CFLAGS			+= -g
CFLAGS			+= -target x86_64-apple-macos12
LDFLAGS			=  -target x86_64-apple-macos12 -bundle -undefined suppress -Wl,-flat_namespace
LDFLAGS			+= -g

.PHONY: all
all: viewer.so

viewer.so: viewer.o ftdiSPI.o
	$(CC) $(LDFLAGS) -o $@ $^ -L$(PATH_D2XX)/lib -lftd2xx
	install_name_tool -change libftd2xx.dylib $(PATH_D2XX)/lib/libftd2xx.dylib $@
	cp -R viewer.so $(PATH_SQEX)/viewer.so
