/*
; tfl_classifier.
; ===============

; SPDX-License-Identifier: MIT
; SPDX-FileCopyrightText: 2025-2026 Edo. Franzi

;------------------------------------------------------------------------
; Author:   Edo. Franzi     The 2025-01-01
; Modifs:
;
; Project:  uKOS-X
; Goal:     Demo of a C application.
;           TensorFlow classifier.
;
;   (c) 2025-2026, Edo. Franzi
;   --------------------------
;                                              __ ______  _____
;   Edo. Franzi                         __  __/ //_/ __ \/ ___/
;   5-Route de Cheseaux                / / / / ,< / / / /\__ \
;   CH 1400 Cheseaux-Noréaz           / /_/ / /| / /_/ /___/ /
;                                     \__,_/_/ |_\____//____/
;   edo.franzi@ukos.ch
;
;   Description: Lightweight, real-time multitasking operating
;   system for embedded microcontroller and DSP-based systems.
;
;   Permission is hereby granted, free of charge, to any person
;   obtaining a copy of this software and associated documentation
;   files (the "Software"), to deal in the Software without restriction,
;   including without limitation the rights to use, copy, modify,
;   merge, publish, distribute, sublicense, and/or sell copies of the
;   Software, and to permit persons to whom the Software is furnished
;   to do so, subject to the following conditions:
;
;   The above copyright notice and this permission notice shall be
;   included in all copies or substantial portions of the Software.
;
;   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
;   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
;   BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
;   ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
;   CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
;   SOFTWARE.
;
;------------------------------------------------------------------------
*/

#include    "database.h"
#include    <stdlib.h>
#include    <math.h>
#include    <cinttypes>

#include    "kern/temporal.h"
#include    "serial/serial.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wconversion"
#pragma GCC diagnostic ignored "-Wcast-align"
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wswitch-default"
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#pragma GCC diagnostic ignored "-Wpedantic"
#include    "tensorflow/lite/core/c/common.h"
#include    "tensorflow/lite/micro/micro_interpreter.h"
#include    "tensorflow/lite/micro/micro_log.h"
#include    "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include    "tensorflow/lite/micro/micro_profiler.h"
#include    "tensorflow/lite/micro/recording_micro_interpreter.h"
#include    "tensorflow/lite/micro/system_setup.h"
#include    "tensorflow/lite/schema/schema_generated.h"
#include    "tensorflow/lite/micro/cortex_m_generic/debug_log_callback.h"

#pragma GCC diagnostic pop

// TFLite model generated by xxd

#include    "./_Training/NN_model.c_inc"

// Prototypes

extern "C" {
void    ui_drawTensorFlowExecutionTime(const char_t *s);
}

// Suggested memory allocation

constexpr   int         KTENSOR_ARENA_SIZE = (10 * 1024);
namespace {
            uint8_t     tensor_arena[KTENSOR_ARENA_SIZE];
}

// Operators necessary for the model

namespace {
void    RegisterOps(tflite::MicroMutableOpResolver<3> &resolver) {

    resolver.AddTanh();
    resolver.AddFullyConnected();
    resolver.AddSoftmax();
}
}

namespace {
void    debuglog(const char *s) {

    (void)dprintf(KSYST, "%s\n", s);
}
}

namespace tfl {

/*
 * \brief tfl_init
 *
 * - Initialise the used resources
 *
 */
void    tfl_init(void) {

    RegisterDebugLogCallback(debuglog);
}

/*
 * \brief tfl_classify
 *
 * - Classify a data vector
 *
 */
void    tfl_classify(const dataBase_t *entry) {
    TfLiteTensor    *input;
    uint64_t        time[2];
    uint32_t        delta = 0u;
    char_t          text[40];

// Load the TFLite model

    const tflite::Model *model = tflite::GetModel(NN_model_tflite);
    if (model->version() != TFLITE_SCHEMA_VERSION) {
        (void)dprintf(KSYST, "Error : Model version not compatible\n");
        exit(EXIT_OS_FAILURE);
    }

// Create the resolver operator
// Create the micro interpreter

    tflite::MicroMutableOpResolver<3> resolver;
    RegisterOps(resolver);
    tflite::MicroInterpreter interpreter(model, resolver, tensor_arena, KTENSOR_ARENA_SIZE);

// Allocate for the tensors

    if (interpreter.AllocateTensors() != kTfLiteOk) {
        (void)dprintf(KSYST, "Error: Tensor allocation!\n");
        exit(EXIT_OS_FAILURE);
    }

// Prepare the inputs

    input = interpreter.input(0);
    input->data.f[0] = entry->oDataSet[0];
    input->data.f[1] = entry->oDataSet[1];
    input->data.f[2] = entry->oDataSet[2];
    input->data.f[3] = entry->oDataSet[3];
    input->data.f[4] = entry->oDataSet[4];
    input->data.f[5] = entry->oDataSet[5];
    input->data.f[6] = entry->oDataSet[6];
    input->data.f[7] = entry->oDataSet[7];

    kern_readTickCount(&time[0]);
    if (interpreter.Invoke() != kTfLiteOk) {
        (void)dprintf(KSYST, "Error: Excecution!\n");
        exit(EXIT_OS_FAILURE);
    }

    kern_readTickCount(&time[1]);
    delta = (uint32_t)(time[1] - time[0]);

// The winner take all

    #if (defined(PRINT_THE_RESULTS_S))
    float32_t       max;
    uint32_t        winner;
    TfLiteTensor    *output;

    output = interpreter.output(0);

    winner = 0u; max = 0.0f;
    if (output->data.f[0] > max) { max = output->data.f[0]; winner = 2u; }
    if (output->data.f[1] > max) { max = output->data.f[1]; winner = 1u; }
    if (output->data.f[2] > max) {                          winner = 0u; }

// Display the results

    (void)dprintf(KSYST, "TensorFlow:  result Out-Expected: %7.3f, %7.3f    %7.3f, %7.3f    %7.3f, %7.3f    Class DB = %s   Class Recognised = %s   "
                         "Exec time %" PRIu32 " [us]\n", output->data.f[0],
                                                         entry->oDataSet[8],
                                                         output->data.f[1],
                                                         entry->oDataSet[9],
                                                         output->data.f[2],
                                                         entry->oDataSet[10],
                                                         entry->oClassLabel,
                                                         aClass[winner],
                                                         delta);
    #endif

    (void)snprintf(text, sizeof(text), "TensorFlow     Ex. time: %" PRIu32 " [us]", delta);
    ui_drawTensorFlowExecutionTime(text);
}

}
