/*
 * SPDX-License-Identifier: MIT
 * SPDX-FileCopyrightText: 2025-2026 Laurent von Allmen
 *
 * Test of the UART0 Tx interruption (variant: one byte per IRQ)
 * using Hazard3 vectored interrupts (mtvec.MODE = 1). Each IRQ writes
 * a single character; the next IRQ is generated by the UART when the
 * Tx FIFO drops below the threshold.
 *
 * Expected on hardware:
 * - UART0 Tx prints ".. but we are not afraid, we are alway firsts ...\n"
 *   roughly once per second
 * - RED   (GPIO13) toggles once per completed string transmission
 *   (~1 s)
 * - GREEN (GPIO12) toggles on each completed string transmission
 *   (so once per RED toggle)
 */

#include    <stdint.h>

#include    "board.h"
#include    "cmns.h"
#include    "core.h"
#include    "first_riscv.h"
#include    "macros_core.h"
#include    "macros_soc.h"
#include    "soc_reg.h"
#include    "types.h"

void    (*vExce_indExcVectors[KNB_CORES][KNB_EXCEPTIONS])(void);
void    (*vExce_indIntVectors[KNB_CORES][KNB_INTERRUPTIONS])(void);
bool    vExce_isException[KNB_CORES] = MCSET(false);

static  volatile    bool        vTransmitted = false;
static  volatile    uint8_t     vString[] = ".. but we are not afraid, we are alway firsts ...\n";

// Prototypes

static void local_UART0_IRQHandler(void);

/*
 * \brief test_07
 *
 * - Test of the UART0 Tx interruption (one byte per IRQ)
 *
 */
static void test_07(void) {

// Switch the trap entry to the local vector table (mtvec.MODE = 1)
// Safe to do here because mstatus.MIE is still cleared

    core_putCSR(RV_CSR_MTVEC, ((uint32_t)vector_table_C0) | 0x1u);

// Initialise the UART0 to generate Tx interruptions

    INTERRUPT_VECTOR(UART0_IRQ_C0_IRQn, local_UART0_IRQHandler);
    core_enableExternalIRQ(UART0_IRQ_C0_IRQn);
    core_setBitCSR(RV_CSR_MIE, MIE_MEIE);

    cmns_init();

    INTERRUPTION_ON_HARD;

    while (true) {
        REG(UART0)->UARTIMSC |= UART_UARTIMSC_TXIM;
        core_setPendingExternalIRQ(UART0_IRQ_C0_IRQn);

// Let terminate the buffer transfer

        cmns_wait(1000000);
        do { } while (vTransmitted == false);

        vTransmitted = false;
        LED_RED_TOGGLE;
    }
}

/*
 * \brief local_UART0_IRQHandler
 *
 * - Blink the GREEN Led on the end of the Tx
 *
 */
static void local_UART0_IRQHandler(void) {
            volatile    uint32_t    data;
    static  volatile    uint8_t     index = 0u;

// Clear the force-pending bit (set by core_setPendingExternalIRQ)

    core_clearPendingExternalIRQ(UART0_IRQ_C0_IRQn);

// Tx interruption

    REG(UART0)->UARTICR = UART_UARTICR_TXIC;

    data = (uint32_t)vString[index];
    REG(UART0)->UARTDR = data;
    index++;
    if (vString[index] == 0u) {

// Terminated

        LED_GREEN_TOGGLE;

        index = 0u;
        vTransmitted = true;
        REG(UART0)->UARTIMSC &= ~UART_UARTIMSC_TXIM;
    }
}

/*
 * \brief main
 *
 * - Execute the test
 *
 */
int     main([[maybe_unused]] int argc, [[maybe_unused]] const char_t *argv[]) {
    test_07();
}
