/*
; stm32H743_otg1_hs_global.
; =========================

; SPDX-License-Identifier: MIT

;------------------------------------------------------------------------
; Author:	Generated using the .svd description	The 2025-01-01
; Modifs:
;
; Project:	uKOS-X
; Goal:		stm32H743_otg1_hs_global equates.
;
;   (c) 2025-2026, Edo. Franzi
;   --------------------------
;                                              __ ______  _____
;   Edo. Franzi                         __  __/ //_/ __ \/ ___/
;   5-Route de Cheseaux                / / / / ,< / / / /\__ \
;   CH 1400 Cheseaux-Noréaz           / /_/ / /| / /_/ /___/ /
;                                     \__,_/_/ |_\____//____/
;   edo.franzi@ukos.ch
;
;   Description: Lightweight, real-time multitasking operating
;   system for embedded microcontroller and DSP-based systems.
;
;   Permission is hereby granted, free of charge, to any person
;   obtaining a copy of this software and associated documentation
;   files (the "Software"), to deal in the Software without restriction,
;   including without limitation the rights to use, copy, modify,
;   merge, publish, distribute, sublicense, and/or sell copies of the
;   Software, and to permit persons to whom the Software is furnished
;   to do so, subject to the following conditions:
;
;   The above copyright notice and this permission notice shall be
;   included in all copies or substantial portions of the Software.
;
;   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
;   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
;   BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
;   ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
;   CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
;   SOFTWARE.
;
;------------------------------------------------------------------------
*/

#pragma	once

#include	<stdint.h>

// OTG1_HS_GLOBAL address definitions
// ----------------------------------

typedef struct {
	volatile	uint32_t	OTG_HS_GOTGCTL;
	volatile	uint32_t	OTG_HS_GOTGINT;
	volatile	uint32_t	OTG_HS_GAHBCFG;
	volatile	uint32_t	OTG_HS_GUSBCFG;
	volatile	uint32_t	OTG_HS_GRSTCTL;
	volatile	uint32_t	OTG_HS_GINTSTS;
	volatile	uint32_t	OTG_HS_GINTMSK;
	volatile	uint32_t	OTG_HS_GRXSTSR;
	volatile	uint32_t	OTG_HS_GRXSTSP;
	volatile	uint32_t	OTG_HS_GRXFSIZ;
		union {
	volatile	uint32_t	OTG_HS_HNPTXFSIZ_HOST;
	volatile	uint32_t	OTG_HS_DIEPTXF0_DEVICE;
		};
	volatile	uint32_t	OTG_HS_GNPTXSTS;
	volatile	uint32_t	RESERVED0[2];
	volatile	uint32_t	OTG_HS_GCCFG;
	volatile	uint32_t	OTG_HS_CID;
	volatile	uint32_t	RESERVED1[5];
	volatile	uint32_t	OTG_HS_GLPMCFG;
	volatile	uint32_t	RESERVED2[42];
	volatile	uint32_t	OTG_HS_HPTXFSIZ;
	volatile	uint32_t	OTG_HS_DIEPTXF1;
	volatile	uint32_t	OTG_HS_DIEPTXF2;
	volatile	uint32_t	OTG_HS_DIEPTXF3;
	volatile	uint32_t	OTG_HS_DIEPTXF4;
	volatile	uint32_t	OTG_HS_DIEPTXF5;
	volatile	uint32_t	OTG_HS_DIEPTXF6;
	volatile	uint32_t	OTG_HS_DIEPTXF7;
	volatile	uint32_t	OTG_DIEPTXF8;
} OTG1_HS_GLOBAL_TypeDef;

#ifdef __cplusplus
#define	OTG1_HS_GLOBAL	reinterpret_cast<OTG1_HS_GLOBAL_TypeDef *>(0x40040000u)

#else
#define	OTG1_HS_GLOBAL	((OTG1_HS_GLOBAL_TypeDef *)0x40040000u)
#endif

// OTG_HS_GOTGCTL Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_CURMOD			(0x1u<<21)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_OTGVER			(0x1u<<20)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_BSVLD				(0x1u<<19)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_ASVLD				(0x1u<<18)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_DBCT				(0x1u<<17)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_CIDSTS			(0x1u<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_EHEN				(0x1u<<12)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_DHNPEN			(0x1u<<11)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_HSHNPEN			(0x1u<<10)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_HNPRQ				(0x1u<<9)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_HNGSCS			(0x1u<<8)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_BVALOVAL			(0x1u<<7)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_BVALOEN			(0x1u<<6)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_AVALOVAL			(0x1u<<5)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_AVALOEN			(0x1u<<4)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_VBVALOVAL			(0x1u<<3)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_VBVALOEN			(0x1u<<2)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_SRQ				(0x1u<<1)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGCTL_SRQSCS			(0x1u<<0)

// OTG_HS_GOTGINT Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_GOTGINT_IDCHNG			(0x1u<<20)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGINT_DBCDNE			(0x1u<<19)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGINT_ADTOCHG			(0x1u<<18)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGINT_HNGDET			(0x1u<<17)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGINT_HNSSCHG			(0x1u<<9)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGINT_SRSSCHG			(0x1u<<8)
#define	OTG1_HS_GLOBAL_OTG_HS_GOTGINT_SEDET				(0x1u<<2)

// OTG_HS_GAHBCFG Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_GAHBCFG_PTXFELVL			(0x1u<<8)
#define	OTG1_HS_GLOBAL_OTG_HS_GAHBCFG_TXFELVL			(0x1u<<7)
#define	OTG1_HS_GLOBAL_OTG_HS_GAHBCFG_DMAEN				(0x1u<<5)
#define	OTG1_HS_GLOBAL_OTG_HS_GAHBCFG_HBSTLEN			(0xFu<<1)
#define	OTG1_HS_GLOBAL_OTG_HS_GAHBCFG_HBSTLEN_0			(0x1u<<1)
#define	OTG1_HS_GLOBAL_OTG_HS_GAHBCFG_GINT				(0x1u<<0)

// OTG_HS_GUSBCFG Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_FDMOD				(0x1u<<30)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_FHMOD				(0x1u<<29)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_ULPIIPD			(0x1u<<25)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_PTCI				(0x1u<<24)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_PCCI				(0x1u<<23)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_TSDPS				(0x1u<<22)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_ULPIEVBUSI		(0x1u<<21)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_ULPIEVBUSD		(0x1u<<20)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_ULPICSM			(0x1u<<19)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_ULPIAR			(0x1u<<18)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_ULPIFSLS			(0x1u<<17)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_PHYLPCS			(0x1u<<15)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_TRDT				(0xFu<<10)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_TRDT_0			(0x1u<<10)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_HNPCAP			(0x1u<<9)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_SRPCAP			(0x1u<<8)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_PHYSEL			(0x1u<<6)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_TOCAL				(0x7u<<0)
#define	OTG1_HS_GLOBAL_OTG_HS_GUSBCFG_TOCAL_0			(0x1u<<0)

// OTG_HS_GRSTCTL Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_GRSTCTL_DMAREQ			(0x1u<<30)
#define	OTG1_HS_GLOBAL_OTG_HS_GRSTCTL_AHBIDL			(0x1u<<31)
#define	OTG1_HS_GLOBAL_OTG_HS_GRSTCTL_TXFNUM			(0x1Fu<<6)
#define	OTG1_HS_GLOBAL_OTG_HS_GRSTCTL_TXFNUM_0			(0x1u<<6)
#define	OTG1_HS_GLOBAL_OTG_HS_GRSTCTL_TXFFLSH			(0x1u<<5)
#define	OTG1_HS_GLOBAL_OTG_HS_GRSTCTL_RXFFLSH			(0x1u<<4)
#define	OTG1_HS_GLOBAL_OTG_HS_GRSTCTL_FCRST				(0x1u<<2)
#define	OTG1_HS_GLOBAL_OTG_HS_GRSTCTL_HSRST				(0x1u<<1)
#define	OTG1_HS_GLOBAL_OTG_HS_GRSTCTL_CSRST				(0x1u<<0)

// OTG_HS_GINTSTS Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_WKUINT			(0x1u<<31)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_SRQINT			(0x1u<<30)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_DISCINT			(0x1u<<29)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_CIDSCHG			(0x1u<<28)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_PTXFE				(0x1u<<26)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_HCINT				(0x1u<<25)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_HPRTINT			(0x1u<<24)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_DATAFSUSP			(0x1u<<22)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_PXFR_INCOMPISOOUT	(0x1u<<21)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_IISOIXFR			(0x1u<<20)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_OEPINT			(0x1u<<19)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_IEPINT			(0x1u<<18)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_EOPF				(0x1u<<15)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_ISOODRP			(0x1u<<14)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_ENUMDNE			(0x1u<<13)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_USBRST			(0x1u<<12)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_USBSUSP			(0x1u<<11)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_ESUSP				(0x1u<<10)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_BOUTNAKEFF		(0x1u<<7)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_GINAKEFF			(0x1u<<6)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_NPTXFE			(0x1u<<5)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_RXFLVL			(0x1u<<4)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_SOF				(0x1u<<3)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_OTGINT			(0x1u<<2)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_MMIS				(0x1u<<1)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTSTS_CMOD				(0x1u<<0)

// OTG_HS_GINTMSK Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_LPMINTM			(0x1u<<27)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_RSTDE				(0x1u<<23)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_WUIM				(0x1u<<31)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_SRQIM				(0x1u<<30)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_DISCINT			(0x1u<<29)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_CIDSCHGM			(0x1u<<28)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_PTXFEM			(0x1u<<26)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_HCIM				(0x1u<<25)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_PRTIM				(0x1u<<24)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_FSUSPM			(0x1u<<22)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_PXFRM_IISOOXFRM	(0x1u<<21)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_IISOIXFRM			(0x1u<<20)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_OEPINT			(0x1u<<19)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_IEPINT			(0x1u<<18)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_EOPFM				(0x1u<<15)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_ISOODRPM			(0x1u<<14)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_ENUMDNEM			(0x1u<<13)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_USBRST			(0x1u<<12)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_USBSUSPM			(0x1u<<11)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_ESUSPM			(0x1u<<10)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_GONAKEFFM			(0x1u<<7)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_GINAKEFFM			(0x1u<<6)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_NPTXFEM			(0x1u<<5)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_RXFLVLM			(0x1u<<4)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_SOFM				(0x1u<<3)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_OTGINT			(0x1u<<2)
#define	OTG1_HS_GLOBAL_OTG_HS_GINTMSK_MMISM				(0x1u<<1)

// OTG_HS_GRXSTSR Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_GRXSTSR_PKTSTS			(0xFu<<17)
#define	OTG1_HS_GLOBAL_OTG_HS_GRXSTSR_PKTSTS_0			(0x1u<<17)
#define	OTG1_HS_GLOBAL_OTG_HS_GRXSTSR_DPID				(0x3u<<15)
#define	OTG1_HS_GLOBAL_OTG_HS_GRXSTSR_DPID_0			(0x1u<<15)
#define	OTG1_HS_GLOBAL_OTG_HS_GRXSTSR_BCNT				(0x7FFu<<4)
#define	OTG1_HS_GLOBAL_OTG_HS_GRXSTSR_BCNT_0			(0x1u<<4)
#define	OTG1_HS_GLOBAL_OTG_HS_GRXSTSR_CHNUM				(0xFu<<0)
#define	OTG1_HS_GLOBAL_OTG_HS_GRXSTSR_CHNUM_0			(0x1u<<0)

// OTG_HS_GRXSTSP Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_GRXSTSP_PKTSTS			(0xFu<<17)
#define	OTG1_HS_GLOBAL_OTG_HS_GRXSTSP_PKTSTS_0			(0x1u<<17)
#define	OTG1_HS_GLOBAL_OTG_HS_GRXSTSP_DPID				(0x3u<<15)
#define	OTG1_HS_GLOBAL_OTG_HS_GRXSTSP_DPID_0			(0x1u<<15)
#define	OTG1_HS_GLOBAL_OTG_HS_GRXSTSP_BCNT				(0x7FFu<<4)
#define	OTG1_HS_GLOBAL_OTG_HS_GRXSTSP_BCNT_0			(0x1u<<4)
#define	OTG1_HS_GLOBAL_OTG_HS_GRXSTSP_CHNUM				(0xFu<<0)
#define	OTG1_HS_GLOBAL_OTG_HS_GRXSTSP_CHNUM_0			(0x1u<<0)

// OTG_HS_GRXFSIZ Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_GRXFSIZ_RXFD				(0xFFFFu<<0)
#define	OTG1_HS_GLOBAL_OTG_HS_GRXFSIZ_RXFD_0			(0x1u<<0)

// OTG_HS_HNPTXFSIZ_HOST Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_HNPTXFSIZ_HOST_NPTXFD		(0xFFFFu<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_HNPTXFSIZ_HOST_NPTXFD_0	(0x1u<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_HNPTXFSIZ_HOST_NPTXFSA	(0xFFFFu<<0)
#define	OTG1_HS_GLOBAL_OTG_HS_HNPTXFSIZ_HOST_NPTXFSA_0	(0x1u<<0)

// OTG_HS_DIEPTXF0_DEVICE Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF0_DEVICE_TX0FD		(0xFFFFu<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF0_DEVICE_TX0FD_0	(0x1u<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF0_DEVICE_TX0FSA	(0xFFFFu<<0)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF0_DEVICE_TX0FSA_0	(0x1u<<0)

// OTG_HS_GNPTXSTS Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_GNPTXSTS_NPTXQTOP			(0x7Fu<<24)
#define	OTG1_HS_GLOBAL_OTG_HS_GNPTXSTS_NPTXQTOP_0		(0x1u<<24)
#define	OTG1_HS_GLOBAL_OTG_HS_GNPTXSTS_NPTQXSAV			(0xFFu<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_GNPTXSTS_NPTQXSAV_0		(0x1u<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_GNPTXSTS_NPTXFSAV			(0xFFFFu<<0)
#define	OTG1_HS_GLOBAL_OTG_HS_GNPTXSTS_NPTXFSAV_0		(0x1u<<0)

// OTG_HS_GCCFG Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_GCCFG_PS2DET				(0x1u<<3)
#define	OTG1_HS_GLOBAL_OTG_HS_GCCFG_SDET				(0x1u<<2)
#define	OTG1_HS_GLOBAL_OTG_HS_GCCFG_PDET				(0x1u<<1)
#define	OTG1_HS_GLOBAL_OTG_HS_GCCFG_DCDET				(0x1u<<0)
#define	OTG1_HS_GLOBAL_OTG_HS_GCCFG_VBDEN				(0x1u<<21)
#define	OTG1_HS_GLOBAL_OTG_HS_GCCFG_SDEN				(0x1u<<20)
#define	OTG1_HS_GLOBAL_OTG_HS_GCCFG_PDEN				(0x1u<<19)
#define	OTG1_HS_GLOBAL_OTG_HS_GCCFG_DCDEN				(0x1u<<18)
#define	OTG1_HS_GLOBAL_OTG_HS_GCCFG_BCDEN				(0x1u<<17)
#define	OTG1_HS_GLOBAL_OTG_HS_GCCFG_PWRDWN				(0x1u<<16)

// OTG_HS_CID Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_CID_PRODUCT_ID			(0xFFFFFFFFu<<0)
#define	OTG1_HS_GLOBAL_OTG_HS_CID_PRODUCT_ID_0			(0x1u<<0)

// OTG_HS_GLPMCFG Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_ENBESL			(0x1u<<28)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_LPMRCNTSTS		(0x7u<<25)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_LPMRCNTSTS_0		(0x1u<<25)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_SNDLPM			(0x1u<<24)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_LPMRCNT			(0x7u<<21)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_LPMRCNT_0			(0x1u<<21)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_LPMCHIDX			(0xFu<<17)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_LPMCHIDX_0		(0x1u<<17)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_L1RSMOK			(0x1u<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_SLPSTS			(0x1u<<15)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_LPMRST			(0x3u<<13)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_LPMRST_0			(0x1u<<13)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_L1DSEN			(0x1u<<12)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_BESLTHRS			(0xFu<<8)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_BESLTHRS_0		(0x1u<<8)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_L1SSEN			(0x1u<<7)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_REMWAKE			(0x1u<<6)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_BESL				(0xFu<<2)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_BESL_0			(0x1u<<2)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_LPMACK			(0x1u<<1)
#define	OTG1_HS_GLOBAL_OTG_HS_GLPMCFG_LPMEN				(0x1u<<0)

// OTG_HS_HPTXFSIZ Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_HPTXFSIZ_PTXFD			(0xFFFFu<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_HPTXFSIZ_PTXFD_0			(0x1u<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_HPTXFSIZ_PTXSA			(0xFFFFu<<0)
#define	OTG1_HS_GLOBAL_OTG_HS_HPTXFSIZ_PTXSA_0			(0x1u<<0)

// OTG_HS_DIEPTXF1 Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF1_INEPTXFD			(0xFFFFu<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF1_INEPTXFD_0		(0x1u<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF1_INEPTXSA			(0xFFFFu<<0)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF1_INEPTXSA_0		(0x1u<<0)

// OTG_HS_DIEPTXF2 Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF2_INEPTXFD			(0xFFFFu<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF2_INEPTXFD_0		(0x1u<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF2_INEPTXSA			(0xFFFFu<<0)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF2_INEPTXSA_0		(0x1u<<0)

// OTG_HS_DIEPTXF3 Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF3_INEPTXFD			(0xFFFFu<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF3_INEPTXFD_0		(0x1u<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF3_INEPTXSA			(0xFFFFu<<0)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF3_INEPTXSA_0		(0x1u<<0)

// OTG_HS_DIEPTXF4 Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF4_INEPTXFD			(0xFFFFu<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF4_INEPTXFD_0		(0x1u<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF4_INEPTXSA			(0xFFFFu<<0)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF4_INEPTXSA_0		(0x1u<<0)

// OTG_HS_DIEPTXF5 Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF5_INEPTXFD			(0xFFFFu<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF5_INEPTXFD_0		(0x1u<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF5_INEPTXSA			(0xFFFFu<<0)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF5_INEPTXSA_0		(0x1u<<0)

// OTG_HS_DIEPTXF6 Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF6_INEPTXFD			(0xFFFFu<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF6_INEPTXFD_0		(0x1u<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF6_INEPTXSA			(0xFFFFu<<0)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF6_INEPTXSA_0		(0x1u<<0)

// OTG_HS_DIEPTXF7 Configuration

#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF7_INEPTXFD			(0xFFFFu<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF7_INEPTXFD_0		(0x1u<<16)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF7_INEPTXSA			(0xFFFFu<<0)
#define	OTG1_HS_GLOBAL_OTG_HS_DIEPTXF7_INEPTXSA_0		(0x1u<<0)

// OTG_DIEPTXF8 Configuration

#define	OTG1_HS_GLOBAL_OTG_DIEPTXF8_INEPTXFD			(0xFFFFu<<16)
#define	OTG1_HS_GLOBAL_OTG_DIEPTXF8_INEPTXFD_0			(0x1u<<16)
#define	OTG1_HS_GLOBAL_OTG_DIEPTXF8_INEPTXSA			(0xFFFFu<<0)
#define	OTG1_HS_GLOBAL_OTG_DIEPTXF8_INEPTXSA_0			(0x1u<<0)
