/*
 * SPDX-License-Identifier: MIT
 * SPDX-FileCopyrightText: 2025-2026 Edo. Franzi
 *
 * Demo of a C application.
 * This application shows how to operate with the uKOS-X uKernel.
 *
 *           Launch 1 processes in C++:
 *
 *           - P0: Every 1000-ms
 *                 Compute the inference
 *                 Display the classes
 * Expected results:
 *          Serial terminal output
 *          uKOS-X > run
 *          Execute the downloaded application.
 *          Run the downloaded application...
 *
 *  In-0  0.584, In-1 -0.529, result: Out-0    0.0%, Out-1    0.0%, Out-2  100.0%     Class C3 (square)       Exec time 163 [us]
 *  In-0  0.415, In-1  0.500, result: Out-0    0.0%, Out-1    0.0%, Out-2  100.0%     Class C3 (square)       Exec time 135 [us]
 *  In-0  0.180, In-1 -0.022, result: Out-0    0.0%, Out-1    0.0%, Out-2  100.0%     Class C3 (square)       Exec time 132 [us]
 *  In-0 -0.942, In-1  0.821, result: Out-0    0.3%, Out-1   99.7%, Out-2    0.0%     Class C2 (inner-outer)  Exec time 153 [us]
 *  In-0  0.005, In-1 -0.255, result: Out-0    3.0%, Out-1   97.0%, Out-2    0.0%     Class C2 (inner-outer)  Exec time 132 [us]
 *  In-0  0.222, In-1  0.506, result: Out-0    0.0%, Out-1    0.0%, Out-2  100.0%     Class C3 (square)       Exec time 130 [us]
 *  .....
 */

/*!
 * \file
 * \ingroup app_mlp
 * \brief This application shows how to operate with the uKOS uKernel.
 *
 *          Launch 1 processes:
 *
 *          - P0: Configure the mlp
 *                Every 1000-ms
 *                  - Simple 4 layer MLP (2 hidden layers)
 *
 */

#include    <inttypes.h>
#include    <stdio.h>
#include    <stdlib.h>

#include    "crt0.h"
#include    "serial/serial.h"
#include    "kern/kern.h"
#include    "macros.h"
#include    "macros_core.h"
#include    "macros_core_stackFrame.h"
#include    "memo/memo.h"
#include    "mlpn/mlpn.h"
#include    "modules.h"
#include    "os_errors.h"
#include    "random/random.h"
#include    "record/record.h"
#include    "types.h"

// MLP model generated by Py

#include    "./_Training/network.c_inc"

// uKOS-X specific (see the module.h)
// ==================================

// ----------------------------------I------------I-----------------------------------------I--------------I

STRG_LOC_CONST(aStrApplication[]) = "class_Py     Py 3 layer MLP test.                      (c) EFr-2026";
STRG_LOC_CONST(aStrHelp[])        = "This is a romable C application\n"
                                    "===============================\n\n"

                                    "This user function module is a C written application.\n\n"

                                    "Input format:  class_Py\n"
                                    "Output format: [result]\n\n"

                                    "Module built on "__DATE__"  "__TIME__" (c) EFr-2026\n\n";

#ifdef ROMABLE_S

static  int32_t     prgm(uint32_t argc, const char_t *argv[]);

MODULE(
    Class_Py,                           // Module name (the first letter has to be upper case)
    KID_FAM_CLI,                        // Family (defined in the module.h)
    KNUM_ROMABLE_0,                     // Module identifier (defined in the module.h)
    nullptr,                            // Address of the initialisation code (early pre-init)
    prgm,                               // Address of the code (prgm for tools, aStart for applications, nullptr for libraries)
    nullptr,                            // Address of the clean code (clean the module)
    " 1.0",                             // Revision string (major . minor)
    ((1U<<BSHOW) | (1U<<BEXE_CONSOLE)), // Flags (BSHOW = visible with "man", BEXE_CONSOLE = executable, BCONFIDENTIAL = hidden)
    0                                   // Execution cores
);

#else
MODULE(
    UserAppl,                           // Module name (the first letter has to be upper case)
    KID_FAM_APPLICATIONS,               // Family (defined in the module.h)
    KNUM_APPLICATION,                   // Module identifier (defined in the module.h)
    nullptr,                            // Address of the initialisation code (early pre-init)
    aStart,                             // Address of the code (prgm for tools, aStart for applications, nullptr for libraries)
    nullptr,                            // Address of the clean code (clean the module)
    " 1.0",                             // Revision string (major . minor)
    ((1U<<BSHOW) | (1U<<BEXE_CONSOLE)), // Flags (BSHOW = visible with "man", BEXE_CONSOLE = executable, BCONFIDENTIAL = hidden)
    0                                   // Execution cores
);
#endif

/*
 * \brief aProcess 0
 *
 * - P0:  Configure the mlp
 *        Every 1000-ms
 *          - Simple 4 layer MLP (2 hidden layers)
 *          - Display the result
 *
 */
[[noreturn]]
static void aProcess_0(const void *argument) {
            float32_t   x, y, result, gain = 2.0F;
            uint64_t    time[2];
            uint32_t    random[2], delta = 0U;
    const   char_t      *winner;

    UNUSED(argument);

    mlpn_configure(&aNetwork);

    while (true) {
        kern_suspendProcess(1000U);

// Prepare the inputs

        random_read(KRANDOM_SOFT, &random[0], 2U);
        x = (((float32_t)random[0] / (float32_t)(KRAND_MAX)) - 0.5F) * gain;
        y = (((float32_t)random[1] / (float32_t)(KRAND_MAX)) - 0.5F) * gain;

        vInput_L1[0] = x;
        vInput_L1[1] = y;

        kern_readTickCount(&time[0]);
        mlpn_compute(&aNetwork);
        kern_readTickCount(&time[1]);
        delta = (uint32_t)(time[1] - time[0]);

// Display the results
// The output is the probability of the class
// The winner takes all

                                      result = vOutput_L3[0]; winner = "Class C1 (ring)        ";
        if (vOutput_L3[1] > result) { result = vOutput_L3[1]; winner = "Class C2 (inner-outer) "; }
        if (vOutput_L3[2] > result) { result = vOutput_L3[2]; winner = "Class C3 (square)      "; }

        if (result < 0.3) {                                   winner = "Not well classified    "; }

        (void)dprintf(KSYST, "In-0 %6.3f, In-1 %6.3f, "
                             "result: Out-0 %6.1f%%, Out-1 %6.1f%%, Out-2 %6.1f%% "
                             "    %s "
                             "Exec time %"PRIu32" [us]\n", x,
                                                           y,
                                                           vOutput_L3[0] * 100,
                                                           vOutput_L3[1] * 100,
                                                           vOutput_L3[2] * 100,
                                                           winner,
                                                           delta);
    }
}

/*
 * \brief main
 *
 * - Initialise the used libraries
 * - Launch all the processes
 * - Kill the "main". At this moment only the launched processes are executed
 *
 */
MAIN_ENTRY(argc, argv[]) {
    proc_t  *process_0;

// ---------------------------------I-----------------------------------------I--------------I

    STRG_LOC_CONST(aStrIden_0[]) = "Process_User_0";
    STRG_LOC_CONST(aStrText_0[]) = "Process user 0.                           (c) EFr-2026";

    UNUSED(argc);
    UNUSED(argv);

// Specifications for the processes

    PROCESS_STACKMALLOC(
        0,                                  // Index
        specification_0,                    // Specifications (just use specification_x)
        aStrText_0,                         // Info string (nullptr if anonymous)
        KKERN_SZ_STACK_XLIB,                // KKERN_SZ_STACK_xx Stack size (number of words (machine size). _XL Extra large, _LL Large, _MM Medium, _SS Small)
        aProcess_0,                         // Code of the process
        aStrIden_0,                         // Identifier (nullptr if anonymous)
        KSYST,                              // Default Serial Communication Manager (KDEF0, KURTx, KSYST, ...)
        KKERN_PRIORITY_HIGH_01              // KKERN_PRIORITY_HIGH < Priority < KKERN_PRIORITY_LOW_14. KKERN_PRIORITY_LOW_15 is reserved for the idle process
    );

// Create the user processes

    if (kern_createProcess(&specification_0, nullptr, &process_0) != KERR_KERN_NOERR) { LOG(KFATAL_USER, "Create proc"); return EXIT_OS_FAILURE; }

    LOG(KINFO_USER, "Application launched, kill the console");
    return EXIT_OS_SUCCESS;
}
