/*
; RP2350_io_qspi.
; ===============

; SPDX-License-Identifier: MIT

;------------------------------------------------------------------------
; Author:	Generated using the .svd description	The 2025-01-01
; Modifs:
;
; Project:	uKOS-X
; Goal:		RP2350_io_qspi equates.
;
;   (c) 2025-2026, Edo. Franzi
;   --------------------------
;                                              __ ______  _____
;   Edo. Franzi                         __  __/ //_/ __ \/ ___/
;   5-Route de Cheseaux                / / / / ,< / / / /\__ \
;   CH 1400 Cheseaux-Noréaz           / /_/ / /| / /_/ /___/ /
;                                     \__,_/_/ |_\____//____/
;   edo.franzi@ukos.ch
;
;   Description: Lightweight, real-time multitasking operating
;   system for embedded microcontroller and DSP-based systems.
;
;   Permission is hereby granted, free of charge, to any person
;   obtaining a copy of this software and associated documentation
;   files (the "Software"), to deal in the Software without restriction,
;   including without limitation the rights to use, copy, modify,
;   merge, publish, distribute, sublicense, and/or sell copies of the
;   Software, and to permit persons to whom the Software is furnished
;   to do so, subject to the following conditions:
;
;   The above copyright notice and this permission notice shall be
;   included in all copies or substantial portions of the Software.
;
;   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
;   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
;   BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
;   ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
;   CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
;   SOFTWARE.
;
;------------------------------------------------------------------------
*/

#pragma	once

#include	<stdint.h>

// IO_QSPI address definitions
// ---------------------------

typedef struct {
	volatile	uint32_t	USBPHY_DP_STATUS;
	volatile	uint32_t	USBPHY_DP_CTRL;
	volatile	uint32_t	USBPHY_DM_STATUS;
	volatile	uint32_t	USBPHY_DM_CTRL;
	volatile	uint32_t	GPIO_QSPI_SCLK_STATUS;
	volatile	uint32_t	GPIO_QSPI_SCLK_CTRL;
	volatile	uint32_t	GPIO_QSPI_SS_STATUS;
	volatile	uint32_t	GPIO_QSPI_SS_CTRL;
	volatile	uint32_t	GPIO_QSPI_SD0_STATUS;
	volatile	uint32_t	GPIO_QSPI_SD0_CTRL;
	volatile	uint32_t	GPIO_QSPI_SD1_STATUS;
	volatile	uint32_t	GPIO_QSPI_SD1_CTRL;
	volatile	uint32_t	GPIO_QSPI_SD2_STATUS;
	volatile	uint32_t	GPIO_QSPI_SD2_CTRL;
	volatile	uint32_t	GPIO_QSPI_SD3_STATUS;
	volatile	uint32_t	GPIO_QSPI_SD3_CTRL;
	volatile	uint32_t	RESERVED0[112];
	volatile	uint32_t	IRQSUMMARY_PROC0_SECURE;
	volatile	uint32_t	IRQSUMMARY_PROC0_NONSECURE;
	volatile	uint32_t	IRQSUMMARY_PROC1_SECURE;
	volatile	uint32_t	IRQSUMMARY_PROC1_NONSECURE;
	volatile	uint32_t	IRQSUMMARY_DORMANT_WAKE_SECURE;
	volatile	uint32_t	IRQSUMMARY_DORMANT_WAKE_NONSECURE;
	volatile	uint32_t	INTR;
	volatile	uint32_t	PROC0_INTE;
	volatile	uint32_t	PROC0_INTF;
	volatile	uint32_t	PROC0_INTS;
	volatile	uint32_t	PROC1_INTE;
	volatile	uint32_t	PROC1_INTF;
	volatile	uint32_t	PROC1_INTS;
	volatile	uint32_t	DORMANT_WAKE_INTE;
	volatile	uint32_t	DORMANT_WAKE_INTF;
	volatile	uint32_t	DORMANT_WAKE_INTS;
} IO_QSPI_TypeDef;

#ifdef __cplusplus
#define	IO_QSPI_NS	reinterpret_cast<IO_QSPI_TypeDef *>(0x40030000u)
#define	IO_QSPI_S	reinterpret_cast<IO_QSPI_TypeDef *>(0x40030000u)
#else
#define	IO_QSPI_NS	((IO_QSPI_TypeDef *)0x40030000u)
#define	IO_QSPI_S	((IO_QSPI_TypeDef *)0x40030000u)
#endif

// USBPHY_DP_STATUS Configuration

#define	IO_QSPI_USBPHY_DP_STATUS_OUTTOPAD							(0x1u<<9)
#define	IO_QSPI_USBPHY_DP_STATUS_OETOPAD							(0x1u<<13)
#define	IO_QSPI_USBPHY_DP_STATUS_INFROMPAD							(0x1u<<17)
#define	IO_QSPI_USBPHY_DP_STATUS_IRQTOPROC							(0x1u<<26)

// USBPHY_DP_CTRL Configuration

#define	IO_QSPI_USBPHY_DP_CTRL_FUNCSEL								(0x1Fu<<0)
#define	IO_QSPI_USBPHY_DP_CTRL_FUNCSEL_0							(0x1u<<0)
#define	IO_QSPI_USBPHY_DP_CTRL_OUTOVER								(0x3u<<12)
#define	IO_QSPI_USBPHY_DP_CTRL_OUTOVER_0							(0x1u<<12)
#define	IO_QSPI_USBPHY_DP_CTRL_OEOVER								(0x3u<<14)
#define	IO_QSPI_USBPHY_DP_CTRL_OEOVER_0								(0x1u<<14)
#define	IO_QSPI_USBPHY_DP_CTRL_INOVER								(0x3u<<16)
#define	IO_QSPI_USBPHY_DP_CTRL_INOVER_0								(0x1u<<16)
#define	IO_QSPI_USBPHY_DP_CTRL_IRQOVER								(0x3u<<28)
#define	IO_QSPI_USBPHY_DP_CTRL_IRQOVER_0							(0x1u<<28)
#define	IO_QSPI_USBPHY_DP_CTRL_FUNCSEL_UART1_TX						(0x2u<<0)
#define	IO_QSPI_USBPHY_DP_CTRL_FUNCSEL_I2C0_SDA						(0x3u<<0)
#define	IO_QSPI_USBPHY_DP_CTRL_FUNCSEL_SIOB_PROC_56					(0x5u<<0)
#define	IO_QSPI_USBPHY_DP_CTRL_FUNCSEL_NULL							(0x1Fu<<0)
#define	IO_QSPI_USBPHY_DP_CTRL_OUTOVER_NORMAL						(0x0u<<12)
#define	IO_QSPI_USBPHY_DP_CTRL_OUTOVER_INVERT						(0x1u<<12)
#define	IO_QSPI_USBPHY_DP_CTRL_OUTOVER_LOW							(0x2u<<12)
#define	IO_QSPI_USBPHY_DP_CTRL_OUTOVER_HIGH							(0x3u<<12)
#define	IO_QSPI_USBPHY_DP_CTRL_OEOVER_NORMAL						(0x0u<<14)
#define	IO_QSPI_USBPHY_DP_CTRL_OEOVER_INVERT						(0x1u<<14)
#define	IO_QSPI_USBPHY_DP_CTRL_OEOVER_DISABLE						(0x2u<<14)
#define	IO_QSPI_USBPHY_DP_CTRL_OEOVER_ENABLE						(0x3u<<14)
#define	IO_QSPI_USBPHY_DP_CTRL_INOVER_NORMAL						(0x0u<<16)
#define	IO_QSPI_USBPHY_DP_CTRL_INOVER_INVERT						(0x1u<<16)
#define	IO_QSPI_USBPHY_DP_CTRL_INOVER_LOW							(0x2u<<16)
#define	IO_QSPI_USBPHY_DP_CTRL_INOVER_HIGH							(0x3u<<16)
#define	IO_QSPI_USBPHY_DP_CTRL_IRQOVER_NORMAL						(0x0u<<28)
#define	IO_QSPI_USBPHY_DP_CTRL_IRQOVER_INVERT						(0x1u<<28)
#define	IO_QSPI_USBPHY_DP_CTRL_IRQOVER_LOW							(0x2u<<28)
#define	IO_QSPI_USBPHY_DP_CTRL_IRQOVER_HIGH							(0x3u<<28)

// USBPHY_DM_STATUS Configuration

#define	IO_QSPI_USBPHY_DM_STATUS_OUTTOPAD							(0x1u<<9)
#define	IO_QSPI_USBPHY_DM_STATUS_OETOPAD							(0x1u<<13)
#define	IO_QSPI_USBPHY_DM_STATUS_INFROMPAD							(0x1u<<17)
#define	IO_QSPI_USBPHY_DM_STATUS_IRQTOPROC							(0x1u<<26)

// USBPHY_DM_CTRL Configuration

#define	IO_QSPI_USBPHY_DM_CTRL_FUNCSEL								(0x1Fu<<0)
#define	IO_QSPI_USBPHY_DM_CTRL_FUNCSEL_0							(0x1u<<0)
#define	IO_QSPI_USBPHY_DM_CTRL_OUTOVER								(0x3u<<12)
#define	IO_QSPI_USBPHY_DM_CTRL_OUTOVER_0							(0x1u<<12)
#define	IO_QSPI_USBPHY_DM_CTRL_OEOVER								(0x3u<<14)
#define	IO_QSPI_USBPHY_DM_CTRL_OEOVER_0								(0x1u<<14)
#define	IO_QSPI_USBPHY_DM_CTRL_INOVER								(0x3u<<16)
#define	IO_QSPI_USBPHY_DM_CTRL_INOVER_0								(0x1u<<16)
#define	IO_QSPI_USBPHY_DM_CTRL_IRQOVER								(0x3u<<28)
#define	IO_QSPI_USBPHY_DM_CTRL_IRQOVER_0							(0x1u<<28)
#define	IO_QSPI_USBPHY_DM_CTRL_FUNCSEL_UART1_RX						(0x2u<<0)
#define	IO_QSPI_USBPHY_DM_CTRL_FUNCSEL_I2C0_SCL						(0x3u<<0)
#define	IO_QSPI_USBPHY_DM_CTRL_FUNCSEL_SIOB_PROC_57					(0x5u<<0)
#define	IO_QSPI_USBPHY_DM_CTRL_FUNCSEL_NULL							(0x1Fu<<0)
#define	IO_QSPI_USBPHY_DM_CTRL_OUTOVER_NORMAL						(0x0u<<12)
#define	IO_QSPI_USBPHY_DM_CTRL_OUTOVER_INVERT						(0x1u<<12)
#define	IO_QSPI_USBPHY_DM_CTRL_OUTOVER_LOW							(0x2u<<12)
#define	IO_QSPI_USBPHY_DM_CTRL_OUTOVER_HIGH							(0x3u<<12)
#define	IO_QSPI_USBPHY_DM_CTRL_OEOVER_NORMAL						(0x0u<<14)
#define	IO_QSPI_USBPHY_DM_CTRL_OEOVER_INVERT						(0x1u<<14)
#define	IO_QSPI_USBPHY_DM_CTRL_OEOVER_DISABLE						(0x2u<<14)
#define	IO_QSPI_USBPHY_DM_CTRL_OEOVER_ENABLE						(0x3u<<14)
#define	IO_QSPI_USBPHY_DM_CTRL_INOVER_NORMAL						(0x0u<<16)
#define	IO_QSPI_USBPHY_DM_CTRL_INOVER_INVERT						(0x1u<<16)
#define	IO_QSPI_USBPHY_DM_CTRL_INOVER_LOW							(0x2u<<16)
#define	IO_QSPI_USBPHY_DM_CTRL_INOVER_HIGH							(0x3u<<16)
#define	IO_QSPI_USBPHY_DM_CTRL_IRQOVER_NORMAL						(0x0u<<28)
#define	IO_QSPI_USBPHY_DM_CTRL_IRQOVER_INVERT						(0x1u<<28)
#define	IO_QSPI_USBPHY_DM_CTRL_IRQOVER_LOW							(0x2u<<28)
#define	IO_QSPI_USBPHY_DM_CTRL_IRQOVER_HIGH							(0x3u<<28)

// GPIO_QSPI_SCLK_STATUS Configuration

#define	IO_QSPI_GPIO_QSPI_SCLK_STATUS_OUTTOPAD						(0x1u<<9)
#define	IO_QSPI_GPIO_QSPI_SCLK_STATUS_OETOPAD						(0x1u<<13)
#define	IO_QSPI_GPIO_QSPI_SCLK_STATUS_INFROMPAD						(0x1u<<17)
#define	IO_QSPI_GPIO_QSPI_SCLK_STATUS_IRQTOPROC						(0x1u<<26)

// GPIO_QSPI_SCLK_CTRL Configuration

#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL							(0x1Fu<<0)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_0						(0x1u<<0)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER							(0x3u<<12)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER_0						(0x1u<<12)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER							(0x3u<<14)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER_0						(0x1u<<14)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER							(0x3u<<16)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER_0						(0x1u<<16)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER							(0x3u<<28)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER_0						(0x1u<<28)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_XIP_SCLK				(0x0u<<0)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_UART1_CTS				(0x2u<<0)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_I2C1_SDA				(0x3u<<0)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_SIOB_PROC_58			(0x5u<<0)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_UART1_TX				(0xBu<<0)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_NULL					(0x1Fu<<0)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER_NORMAL					(0x0u<<12)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER_INVERT					(0x1u<<12)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER_LOW						(0x2u<<12)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER_HIGH					(0x3u<<12)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER_NORMAL					(0x0u<<14)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER_INVERT					(0x1u<<14)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER_DISABLE					(0x2u<<14)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER_ENABLE					(0x3u<<14)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER_NORMAL					(0x0u<<16)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER_INVERT					(0x1u<<16)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER_LOW						(0x2u<<16)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER_HIGH						(0x3u<<16)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER_NORMAL					(0x0u<<28)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER_INVERT					(0x1u<<28)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER_LOW						(0x2u<<28)
#define	IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER_HIGH					(0x3u<<28)

// GPIO_QSPI_SS_STATUS Configuration

#define	IO_QSPI_GPIO_QSPI_SS_STATUS_OUTTOPAD						(0x1u<<9)
#define	IO_QSPI_GPIO_QSPI_SS_STATUS_OETOPAD							(0x1u<<13)
#define	IO_QSPI_GPIO_QSPI_SS_STATUS_INFROMPAD						(0x1u<<17)
#define	IO_QSPI_GPIO_QSPI_SS_STATUS_IRQTOPROC						(0x1u<<26)

// GPIO_QSPI_SS_CTRL Configuration

#define	IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL							(0x1Fu<<0)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_0							(0x1u<<0)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER							(0x3u<<12)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER_0							(0x1u<<12)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER							(0x3u<<14)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER_0							(0x1u<<14)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER							(0x3u<<16)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER_0							(0x1u<<16)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER							(0x3u<<28)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER_0							(0x1u<<28)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_XIP_SS_N_0				(0x0u<<0)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_UART1_RTS					(0x2u<<0)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_I2C1_SCL					(0x3u<<0)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_SIOB_PROC_59				(0x5u<<0)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_UART1_RX					(0xBu<<0)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_NULL						(0x1Fu<<0)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER_NORMAL					(0x0u<<12)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER_INVERT					(0x1u<<12)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER_LOW						(0x2u<<12)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER_HIGH						(0x3u<<12)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER_NORMAL						(0x0u<<14)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER_INVERT						(0x1u<<14)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER_DISABLE					(0x2u<<14)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER_ENABLE						(0x3u<<14)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER_NORMAL						(0x0u<<16)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER_INVERT						(0x1u<<16)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER_LOW						(0x2u<<16)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER_HIGH						(0x3u<<16)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER_NORMAL					(0x0u<<28)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER_INVERT					(0x1u<<28)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER_LOW						(0x2u<<28)
#define	IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER_HIGH						(0x3u<<28)

// GPIO_QSPI_SD0_STATUS Configuration

#define	IO_QSPI_GPIO_QSPI_SD0_STATUS_OUTTOPAD						(0x1u<<9)
#define	IO_QSPI_GPIO_QSPI_SD0_STATUS_OETOPAD						(0x1u<<13)
#define	IO_QSPI_GPIO_QSPI_SD0_STATUS_INFROMPAD						(0x1u<<17)
#define	IO_QSPI_GPIO_QSPI_SD0_STATUS_IRQTOPROC						(0x1u<<26)

// GPIO_QSPI_SD0_CTRL Configuration

#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL							(0x1Fu<<0)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL_0						(0x1u<<0)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER							(0x3u<<12)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER_0						(0x1u<<12)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER							(0x3u<<14)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER_0							(0x1u<<14)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER							(0x3u<<16)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER_0							(0x1u<<16)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER							(0x3u<<28)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER_0						(0x1u<<28)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL_XIP_SD0					(0x0u<<0)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL_UART0_TX					(0x2u<<0)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL_I2C0_SDA					(0x3u<<0)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL_SIOB_PROC_60				(0x5u<<0)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL_NULL						(0x1Fu<<0)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER_NORMAL					(0x0u<<12)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER_INVERT					(0x1u<<12)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER_LOW						(0x2u<<12)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER_HIGH						(0x3u<<12)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER_NORMAL					(0x0u<<14)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER_INVERT					(0x1u<<14)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER_DISABLE					(0x2u<<14)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER_ENABLE					(0x3u<<14)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER_NORMAL					(0x0u<<16)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER_INVERT					(0x1u<<16)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER_LOW						(0x2u<<16)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER_HIGH						(0x3u<<16)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER_NORMAL					(0x0u<<28)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER_INVERT					(0x1u<<28)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER_LOW						(0x2u<<28)
#define	IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER_HIGH						(0x3u<<28)

// GPIO_QSPI_SD1_STATUS Configuration

#define	IO_QSPI_GPIO_QSPI_SD1_STATUS_OUTTOPAD						(0x1u<<9)
#define	IO_QSPI_GPIO_QSPI_SD1_STATUS_OETOPAD						(0x1u<<13)
#define	IO_QSPI_GPIO_QSPI_SD1_STATUS_INFROMPAD						(0x1u<<17)
#define	IO_QSPI_GPIO_QSPI_SD1_STATUS_IRQTOPROC						(0x1u<<26)

// GPIO_QSPI_SD1_CTRL Configuration

#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL							(0x1Fu<<0)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL_0						(0x1u<<0)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER							(0x3u<<12)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER_0						(0x1u<<12)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER							(0x3u<<14)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER_0							(0x1u<<14)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER							(0x3u<<16)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER_0							(0x1u<<16)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER							(0x3u<<28)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER_0						(0x1u<<28)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL_XIP_SD1					(0x0u<<0)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL_UART0_RX					(0x2u<<0)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL_I2C0_SCL					(0x3u<<0)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL_SIOB_PROC_61				(0x5u<<0)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL_NULL						(0x1Fu<<0)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER_NORMAL					(0x0u<<12)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER_INVERT					(0x1u<<12)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER_LOW						(0x2u<<12)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER_HIGH						(0x3u<<12)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER_NORMAL					(0x0u<<14)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER_INVERT					(0x1u<<14)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER_DISABLE					(0x2u<<14)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER_ENABLE					(0x3u<<14)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER_NORMAL					(0x0u<<16)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER_INVERT					(0x1u<<16)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER_LOW						(0x2u<<16)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER_HIGH						(0x3u<<16)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER_NORMAL					(0x0u<<28)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER_INVERT					(0x1u<<28)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER_LOW						(0x2u<<28)
#define	IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER_HIGH						(0x3u<<28)

// GPIO_QSPI_SD2_STATUS Configuration

#define	IO_QSPI_GPIO_QSPI_SD2_STATUS_OUTTOPAD						(0x1u<<9)
#define	IO_QSPI_GPIO_QSPI_SD2_STATUS_OETOPAD						(0x1u<<13)
#define	IO_QSPI_GPIO_QSPI_SD2_STATUS_INFROMPAD						(0x1u<<17)
#define	IO_QSPI_GPIO_QSPI_SD2_STATUS_IRQTOPROC						(0x1u<<26)

// GPIO_QSPI_SD2_CTRL Configuration

#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL							(0x1Fu<<0)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_0						(0x1u<<0)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER							(0x3u<<12)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER_0						(0x1u<<12)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER							(0x3u<<14)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER_0							(0x1u<<14)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER							(0x3u<<16)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER_0							(0x1u<<16)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER							(0x3u<<28)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER_0						(0x1u<<28)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_XIP_SD2					(0x0u<<0)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_UART0_CTS				(0x2u<<0)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_I2C1_SDA					(0x3u<<0)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_SIOB_PROC_62				(0x5u<<0)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_UART0_TX					(0xBu<<0)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_NULL						(0x1Fu<<0)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER_NORMAL					(0x0u<<12)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER_INVERT					(0x1u<<12)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER_LOW						(0x2u<<12)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER_HIGH						(0x3u<<12)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER_NORMAL					(0x0u<<14)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER_INVERT					(0x1u<<14)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER_DISABLE					(0x2u<<14)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER_ENABLE					(0x3u<<14)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER_NORMAL					(0x0u<<16)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER_INVERT					(0x1u<<16)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER_LOW						(0x2u<<16)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER_HIGH						(0x3u<<16)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER_NORMAL					(0x0u<<28)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER_INVERT					(0x1u<<28)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER_LOW						(0x2u<<28)
#define	IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER_HIGH						(0x3u<<28)

// GPIO_QSPI_SD3_STATUS Configuration

#define	IO_QSPI_GPIO_QSPI_SD3_STATUS_OUTTOPAD						(0x1u<<9)
#define	IO_QSPI_GPIO_QSPI_SD3_STATUS_OETOPAD						(0x1u<<13)
#define	IO_QSPI_GPIO_QSPI_SD3_STATUS_INFROMPAD						(0x1u<<17)
#define	IO_QSPI_GPIO_QSPI_SD3_STATUS_IRQTOPROC						(0x1u<<26)

// GPIO_QSPI_SD3_CTRL Configuration

#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL							(0x1Fu<<0)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_0						(0x1u<<0)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER							(0x3u<<12)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER_0						(0x1u<<12)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER							(0x3u<<14)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER_0							(0x1u<<14)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER							(0x3u<<16)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER_0							(0x1u<<16)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER							(0x3u<<28)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER_0						(0x1u<<28)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_XIP_SD3					(0x0u<<0)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_UART0_RTS				(0x2u<<0)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_I2C1_SCL					(0x3u<<0)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_SIOB_PROC_63				(0x5u<<0)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_UART0_RX					(0xBu<<0)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_NULL						(0x1Fu<<0)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER_NORMAL					(0x0u<<12)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER_INVERT					(0x1u<<12)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER_LOW						(0x2u<<12)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER_HIGH						(0x3u<<12)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER_NORMAL					(0x0u<<14)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER_INVERT					(0x1u<<14)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER_DISABLE					(0x2u<<14)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER_ENABLE					(0x3u<<14)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER_NORMAL					(0x0u<<16)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER_INVERT					(0x1u<<16)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER_LOW						(0x2u<<16)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER_HIGH						(0x3u<<16)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER_NORMAL					(0x0u<<28)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER_INVERT					(0x1u<<28)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER_LOW						(0x2u<<28)
#define	IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER_HIGH						(0x3u<<28)

// IRQSUMMARY_PROC0_SECURE Configuration

#define	IO_QSPI_IRQSUMMARY_PROC0_SECURE_USBPHY_DP					(0x1u<<0)
#define	IO_QSPI_IRQSUMMARY_PROC0_SECURE_USBPHY_DM					(0x1u<<1)
#define	IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SCLK				(0x1u<<2)
#define	IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SS				(0x1u<<3)
#define	IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SD0				(0x1u<<4)
#define	IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SD1				(0x1u<<5)
#define	IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SD2				(0x1u<<6)
#define	IO_QSPI_IRQSUMMARY_PROC0_SECURE_GPIO_QSPI_SD3				(0x1u<<7)

// IRQSUMMARY_PROC0_NONSECURE Configuration

#define	IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_USBPHY_DP				(0x1u<<0)
#define	IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_USBPHY_DM				(0x1u<<1)
#define	IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SCLK			(0x1u<<2)
#define	IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SS				(0x1u<<3)
#define	IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SD0			(0x1u<<4)
#define	IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SD1			(0x1u<<5)
#define	IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SD2			(0x1u<<6)
#define	IO_QSPI_IRQSUMMARY_PROC0_NONSECURE_GPIO_QSPI_SD3			(0x1u<<7)

// IRQSUMMARY_PROC1_SECURE Configuration

#define	IO_QSPI_IRQSUMMARY_PROC1_SECURE_USBPHY_DP					(0x1u<<0)
#define	IO_QSPI_IRQSUMMARY_PROC1_SECURE_USBPHY_DM					(0x1u<<1)
#define	IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SCLK				(0x1u<<2)
#define	IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SS				(0x1u<<3)
#define	IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SD0				(0x1u<<4)
#define	IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SD1				(0x1u<<5)
#define	IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SD2				(0x1u<<6)
#define	IO_QSPI_IRQSUMMARY_PROC1_SECURE_GPIO_QSPI_SD3				(0x1u<<7)

// IRQSUMMARY_PROC1_NONSECURE Configuration

#define	IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_USBPHY_DP				(0x1u<<0)
#define	IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_USBPHY_DM				(0x1u<<1)
#define	IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SCLK			(0x1u<<2)
#define	IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SS				(0x1u<<3)
#define	IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SD0			(0x1u<<4)
#define	IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SD1			(0x1u<<5)
#define	IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SD2			(0x1u<<6)
#define	IO_QSPI_IRQSUMMARY_PROC1_NONSECURE_GPIO_QSPI_SD3			(0x1u<<7)

// IRQSUMMARY_DORMANT_WAKE_SECURE Configuration

#define	IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_USBPHY_DP			(0x1u<<0)
#define	IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_USBPHY_DM			(0x1u<<1)
#define	IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SCLK		(0x1u<<2)
#define	IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SS			(0x1u<<3)
#define	IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SD0		(0x1u<<4)
#define	IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SD1		(0x1u<<5)
#define	IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SD2		(0x1u<<6)
#define	IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE_GPIO_QSPI_SD3		(0x1u<<7)

// IRQSUMMARY_DORMANT_WAKE_NONSECURE Configuration

#define	IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_USBPHY_DP			(0x1u<<0)
#define	IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_USBPHY_DM			(0x1u<<1)
#define	IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SCLK	(0x1u<<2)
#define	IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SS		(0x1u<<3)
#define	IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SD0		(0x1u<<4)
#define	IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SD1		(0x1u<<5)
#define	IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SD2		(0x1u<<6)
#define	IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE_GPIO_QSPI_SD3		(0x1u<<7)

// INTR Configuration

#define	IO_QSPI_INTR_USBPHY_DP_LEVEL_LOW							(0x1u<<0)
#define	IO_QSPI_INTR_USBPHY_DP_LEVEL_HIGH							(0x1u<<1)
#define	IO_QSPI_INTR_USBPHY_DP_EDGE_LOW								(0x1u<<2)
#define	IO_QSPI_INTR_USBPHY_DP_EDGE_HIGH							(0x1u<<3)
#define	IO_QSPI_INTR_USBPHY_DM_LEVEL_LOW							(0x1u<<4)
#define	IO_QSPI_INTR_USBPHY_DM_LEVEL_HIGH							(0x1u<<5)
#define	IO_QSPI_INTR_USBPHY_DM_EDGE_LOW								(0x1u<<6)
#define	IO_QSPI_INTR_USBPHY_DM_EDGE_HIGH							(0x1u<<7)
#define	IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_LOW						(0x1u<<8)
#define	IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_HIGH						(0x1u<<9)
#define	IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_LOW						(0x1u<<10)
#define	IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_HIGH						(0x1u<<11)
#define	IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_LOW							(0x1u<<12)
#define	IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_HIGH						(0x1u<<13)
#define	IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_LOW							(0x1u<<14)
#define	IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_HIGH							(0x1u<<15)
#define	IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_LOW						(0x1u<<16)
#define	IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_HIGH						(0x1u<<17)
#define	IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_LOW							(0x1u<<18)
#define	IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_HIGH						(0x1u<<19)
#define	IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_LOW						(0x1u<<20)
#define	IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_HIGH						(0x1u<<21)
#define	IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_LOW							(0x1u<<22)
#define	IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_HIGH						(0x1u<<23)
#define	IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_LOW						(0x1u<<24)
#define	IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_HIGH						(0x1u<<25)
#define	IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_LOW							(0x1u<<26)
#define	IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_HIGH						(0x1u<<27)
#define	IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_LOW						(0x1u<<28)
#define	IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_HIGH						(0x1u<<29)
#define	IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_LOW							(0x1u<<30)
#define	IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_HIGH						(0x1u<<31)

// PROC0_INTE Configuration

#define	IO_QSPI_PROC0_INTE_USBPHY_DP_LEVEL_LOW						(0x1u<<0)
#define	IO_QSPI_PROC0_INTE_USBPHY_DP_LEVEL_HIGH						(0x1u<<1)
#define	IO_QSPI_PROC0_INTE_USBPHY_DP_EDGE_LOW						(0x1u<<2)
#define	IO_QSPI_PROC0_INTE_USBPHY_DP_EDGE_HIGH						(0x1u<<3)
#define	IO_QSPI_PROC0_INTE_USBPHY_DM_LEVEL_LOW						(0x1u<<4)
#define	IO_QSPI_PROC0_INTE_USBPHY_DM_LEVEL_HIGH						(0x1u<<5)
#define	IO_QSPI_PROC0_INTE_USBPHY_DM_EDGE_LOW						(0x1u<<6)
#define	IO_QSPI_PROC0_INTE_USBPHY_DM_EDGE_HIGH						(0x1u<<7)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_LOW					(0x1u<<8)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH				(0x1u<<9)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_LOW					(0x1u<<10)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_HIGH					(0x1u<<11)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_LOW					(0x1u<<12)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_HIGH					(0x1u<<13)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_LOW					(0x1u<<14)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_HIGH					(0x1u<<15)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_LOW					(0x1u<<16)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_HIGH					(0x1u<<17)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_LOW					(0x1u<<18)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_HIGH					(0x1u<<19)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_LOW					(0x1u<<20)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_HIGH					(0x1u<<21)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_LOW					(0x1u<<22)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_HIGH					(0x1u<<23)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_LOW					(0x1u<<24)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_HIGH					(0x1u<<25)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_LOW					(0x1u<<26)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_HIGH					(0x1u<<27)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_LOW					(0x1u<<28)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_HIGH					(0x1u<<29)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_LOW					(0x1u<<30)
#define	IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_HIGH					(0x1u<<31)

// PROC0_INTF Configuration

#define	IO_QSPI_PROC0_INTF_USBPHY_DP_LEVEL_LOW						(0x1u<<0)
#define	IO_QSPI_PROC0_INTF_USBPHY_DP_LEVEL_HIGH						(0x1u<<1)
#define	IO_QSPI_PROC0_INTF_USBPHY_DP_EDGE_LOW						(0x1u<<2)
#define	IO_QSPI_PROC0_INTF_USBPHY_DP_EDGE_HIGH						(0x1u<<3)
#define	IO_QSPI_PROC0_INTF_USBPHY_DM_LEVEL_LOW						(0x1u<<4)
#define	IO_QSPI_PROC0_INTF_USBPHY_DM_LEVEL_HIGH						(0x1u<<5)
#define	IO_QSPI_PROC0_INTF_USBPHY_DM_EDGE_LOW						(0x1u<<6)
#define	IO_QSPI_PROC0_INTF_USBPHY_DM_EDGE_HIGH						(0x1u<<7)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_LOW					(0x1u<<8)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH				(0x1u<<9)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_LOW					(0x1u<<10)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_HIGH					(0x1u<<11)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_LOW					(0x1u<<12)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_HIGH					(0x1u<<13)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_LOW					(0x1u<<14)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_HIGH					(0x1u<<15)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_LOW					(0x1u<<16)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_HIGH					(0x1u<<17)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_LOW					(0x1u<<18)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_HIGH					(0x1u<<19)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_LOW					(0x1u<<20)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_HIGH					(0x1u<<21)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_LOW					(0x1u<<22)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_HIGH					(0x1u<<23)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_LOW					(0x1u<<24)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_HIGH					(0x1u<<25)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_LOW					(0x1u<<26)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_HIGH					(0x1u<<27)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_LOW					(0x1u<<28)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_HIGH					(0x1u<<29)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_LOW					(0x1u<<30)
#define	IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_HIGH					(0x1u<<31)

// PROC0_INTS Configuration

#define	IO_QSPI_PROC0_INTS_USBPHY_DP_LEVEL_LOW						(0x1u<<0)
#define	IO_QSPI_PROC0_INTS_USBPHY_DP_LEVEL_HIGH						(0x1u<<1)
#define	IO_QSPI_PROC0_INTS_USBPHY_DP_EDGE_LOW						(0x1u<<2)
#define	IO_QSPI_PROC0_INTS_USBPHY_DP_EDGE_HIGH						(0x1u<<3)
#define	IO_QSPI_PROC0_INTS_USBPHY_DM_LEVEL_LOW						(0x1u<<4)
#define	IO_QSPI_PROC0_INTS_USBPHY_DM_LEVEL_HIGH						(0x1u<<5)
#define	IO_QSPI_PROC0_INTS_USBPHY_DM_EDGE_LOW						(0x1u<<6)
#define	IO_QSPI_PROC0_INTS_USBPHY_DM_EDGE_HIGH						(0x1u<<7)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_LOW					(0x1u<<8)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH				(0x1u<<9)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_LOW					(0x1u<<10)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_HIGH					(0x1u<<11)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_LOW					(0x1u<<12)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_HIGH					(0x1u<<13)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_LOW					(0x1u<<14)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_HIGH					(0x1u<<15)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_LOW					(0x1u<<16)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_HIGH					(0x1u<<17)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_LOW					(0x1u<<18)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_HIGH					(0x1u<<19)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_LOW					(0x1u<<20)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_HIGH					(0x1u<<21)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_LOW					(0x1u<<22)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_HIGH					(0x1u<<23)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_LOW					(0x1u<<24)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_HIGH					(0x1u<<25)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_LOW					(0x1u<<26)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_HIGH					(0x1u<<27)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_LOW					(0x1u<<28)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_HIGH					(0x1u<<29)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_LOW					(0x1u<<30)
#define	IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_HIGH					(0x1u<<31)

// PROC1_INTE Configuration

#define	IO_QSPI_PROC1_INTE_USBPHY_DP_LEVEL_LOW						(0x1u<<0)
#define	IO_QSPI_PROC1_INTE_USBPHY_DP_LEVEL_HIGH						(0x1u<<1)
#define	IO_QSPI_PROC1_INTE_USBPHY_DP_EDGE_LOW						(0x1u<<2)
#define	IO_QSPI_PROC1_INTE_USBPHY_DP_EDGE_HIGH						(0x1u<<3)
#define	IO_QSPI_PROC1_INTE_USBPHY_DM_LEVEL_LOW						(0x1u<<4)
#define	IO_QSPI_PROC1_INTE_USBPHY_DM_LEVEL_HIGH						(0x1u<<5)
#define	IO_QSPI_PROC1_INTE_USBPHY_DM_EDGE_LOW						(0x1u<<6)
#define	IO_QSPI_PROC1_INTE_USBPHY_DM_EDGE_HIGH						(0x1u<<7)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_LOW					(0x1u<<8)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH				(0x1u<<9)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_LOW					(0x1u<<10)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_HIGH					(0x1u<<11)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_LOW					(0x1u<<12)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_HIGH					(0x1u<<13)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_LOW					(0x1u<<14)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_HIGH					(0x1u<<15)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_LOW					(0x1u<<16)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_HIGH					(0x1u<<17)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_LOW					(0x1u<<18)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_HIGH					(0x1u<<19)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_LOW					(0x1u<<20)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_HIGH					(0x1u<<21)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_LOW					(0x1u<<22)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_HIGH					(0x1u<<23)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_LOW					(0x1u<<24)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_HIGH					(0x1u<<25)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_LOW					(0x1u<<26)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_HIGH					(0x1u<<27)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_LOW					(0x1u<<28)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_HIGH					(0x1u<<29)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_LOW					(0x1u<<30)
#define	IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_HIGH					(0x1u<<31)

// PROC1_INTF Configuration

#define	IO_QSPI_PROC1_INTF_USBPHY_DP_LEVEL_LOW						(0x1u<<0)
#define	IO_QSPI_PROC1_INTF_USBPHY_DP_LEVEL_HIGH						(0x1u<<1)
#define	IO_QSPI_PROC1_INTF_USBPHY_DP_EDGE_LOW						(0x1u<<2)
#define	IO_QSPI_PROC1_INTF_USBPHY_DP_EDGE_HIGH						(0x1u<<3)
#define	IO_QSPI_PROC1_INTF_USBPHY_DM_LEVEL_LOW						(0x1u<<4)
#define	IO_QSPI_PROC1_INTF_USBPHY_DM_LEVEL_HIGH						(0x1u<<5)
#define	IO_QSPI_PROC1_INTF_USBPHY_DM_EDGE_LOW						(0x1u<<6)
#define	IO_QSPI_PROC1_INTF_USBPHY_DM_EDGE_HIGH						(0x1u<<7)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_LOW					(0x1u<<8)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH				(0x1u<<9)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_LOW					(0x1u<<10)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_HIGH					(0x1u<<11)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_LOW					(0x1u<<12)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_HIGH					(0x1u<<13)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_LOW					(0x1u<<14)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_HIGH					(0x1u<<15)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_LOW					(0x1u<<16)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_HIGH					(0x1u<<17)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_LOW					(0x1u<<18)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_HIGH					(0x1u<<19)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_LOW					(0x1u<<20)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_HIGH					(0x1u<<21)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_LOW					(0x1u<<22)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_HIGH					(0x1u<<23)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_LOW					(0x1u<<24)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_HIGH					(0x1u<<25)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_LOW					(0x1u<<26)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_HIGH					(0x1u<<27)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_LOW					(0x1u<<28)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_HIGH					(0x1u<<29)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_LOW					(0x1u<<30)
#define	IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_HIGH					(0x1u<<31)

// PROC1_INTS Configuration

#define	IO_QSPI_PROC1_INTS_USBPHY_DP_LEVEL_LOW						(0x1u<<0)
#define	IO_QSPI_PROC1_INTS_USBPHY_DP_LEVEL_HIGH						(0x1u<<1)
#define	IO_QSPI_PROC1_INTS_USBPHY_DP_EDGE_LOW						(0x1u<<2)
#define	IO_QSPI_PROC1_INTS_USBPHY_DP_EDGE_HIGH						(0x1u<<3)
#define	IO_QSPI_PROC1_INTS_USBPHY_DM_LEVEL_LOW						(0x1u<<4)
#define	IO_QSPI_PROC1_INTS_USBPHY_DM_LEVEL_HIGH						(0x1u<<5)
#define	IO_QSPI_PROC1_INTS_USBPHY_DM_EDGE_LOW						(0x1u<<6)
#define	IO_QSPI_PROC1_INTS_USBPHY_DM_EDGE_HIGH						(0x1u<<7)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_LOW					(0x1u<<8)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH				(0x1u<<9)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_LOW					(0x1u<<10)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_HIGH					(0x1u<<11)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_LOW					(0x1u<<12)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_HIGH					(0x1u<<13)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_LOW					(0x1u<<14)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_HIGH					(0x1u<<15)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_LOW					(0x1u<<16)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_HIGH					(0x1u<<17)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_LOW					(0x1u<<18)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_HIGH					(0x1u<<19)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_LOW					(0x1u<<20)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_HIGH					(0x1u<<21)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_LOW					(0x1u<<22)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_HIGH					(0x1u<<23)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_LOW					(0x1u<<24)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_HIGH					(0x1u<<25)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_LOW					(0x1u<<26)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_HIGH					(0x1u<<27)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_LOW					(0x1u<<28)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_HIGH					(0x1u<<29)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_LOW					(0x1u<<30)
#define	IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_HIGH					(0x1u<<31)

// DORMANT_WAKE_INTE Configuration

#define	IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_LEVEL_LOW				(0x1u<<0)
#define	IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_LEVEL_HIGH				(0x1u<<1)
#define	IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_EDGE_LOW				(0x1u<<2)
#define	IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_EDGE_HIGH				(0x1u<<3)
#define	IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_LEVEL_LOW				(0x1u<<4)
#define	IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_LEVEL_HIGH				(0x1u<<5)
#define	IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_EDGE_LOW				(0x1u<<6)
#define	IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_EDGE_HIGH				(0x1u<<7)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_LOW			(0x1u<<8)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH			(0x1u<<9)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_LOW			(0x1u<<10)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_HIGH			(0x1u<<11)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_LOW			(0x1u<<12)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_HIGH			(0x1u<<13)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_LOW				(0x1u<<14)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_HIGH			(0x1u<<15)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_LOW			(0x1u<<16)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_HIGH			(0x1u<<17)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_LOW			(0x1u<<18)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_HIGH			(0x1u<<19)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_LOW			(0x1u<<20)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_HIGH			(0x1u<<21)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_LOW			(0x1u<<22)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_HIGH			(0x1u<<23)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_LOW			(0x1u<<24)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_HIGH			(0x1u<<25)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_LOW			(0x1u<<26)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_HIGH			(0x1u<<27)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_LOW			(0x1u<<28)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_HIGH			(0x1u<<29)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_LOW			(0x1u<<30)
#define	IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_HIGH			(0x1u<<31)

// DORMANT_WAKE_INTF Configuration

#define	IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_LEVEL_LOW				(0x1u<<0)
#define	IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_LEVEL_HIGH				(0x1u<<1)
#define	IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_EDGE_LOW				(0x1u<<2)
#define	IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_EDGE_HIGH				(0x1u<<3)
#define	IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_LEVEL_LOW				(0x1u<<4)
#define	IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_LEVEL_HIGH				(0x1u<<5)
#define	IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_EDGE_LOW				(0x1u<<6)
#define	IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_EDGE_HIGH				(0x1u<<7)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_LOW			(0x1u<<8)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH			(0x1u<<9)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_LOW			(0x1u<<10)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_HIGH			(0x1u<<11)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_LOW			(0x1u<<12)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_HIGH			(0x1u<<13)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_LOW				(0x1u<<14)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_HIGH			(0x1u<<15)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_LOW			(0x1u<<16)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_HIGH			(0x1u<<17)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_LOW			(0x1u<<18)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_HIGH			(0x1u<<19)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_LOW			(0x1u<<20)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_HIGH			(0x1u<<21)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_LOW			(0x1u<<22)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_HIGH			(0x1u<<23)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_LOW			(0x1u<<24)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_HIGH			(0x1u<<25)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_LOW			(0x1u<<26)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_HIGH			(0x1u<<27)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_LOW			(0x1u<<28)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_HIGH			(0x1u<<29)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_LOW			(0x1u<<30)
#define	IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_HIGH			(0x1u<<31)

// DORMANT_WAKE_INTS Configuration

#define	IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_LEVEL_LOW				(0x1u<<0)
#define	IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_LEVEL_HIGH				(0x1u<<1)
#define	IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_EDGE_LOW				(0x1u<<2)
#define	IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_EDGE_HIGH				(0x1u<<3)
#define	IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_LEVEL_LOW				(0x1u<<4)
#define	IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_LEVEL_HIGH				(0x1u<<5)
#define	IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_EDGE_LOW				(0x1u<<6)
#define	IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_EDGE_HIGH				(0x1u<<7)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_LOW			(0x1u<<8)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH			(0x1u<<9)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_LOW			(0x1u<<10)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_HIGH			(0x1u<<11)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_LOW			(0x1u<<12)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_HIGH			(0x1u<<13)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_LOW				(0x1u<<14)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_HIGH			(0x1u<<15)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_LOW			(0x1u<<16)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_HIGH			(0x1u<<17)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_LOW			(0x1u<<18)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_HIGH			(0x1u<<19)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_LOW			(0x1u<<20)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_HIGH			(0x1u<<21)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_LOW			(0x1u<<22)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_HIGH			(0x1u<<23)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_LOW			(0x1u<<24)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_HIGH			(0x1u<<25)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_LOW			(0x1u<<26)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_HIGH			(0x1u<<27)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_LOW			(0x1u<<28)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_HIGH			(0x1u<<29)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_LOW			(0x1u<<30)
#define	IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_HIGH			(0x1u<<31)
