/*
; RP2350_usb_dpram.
; =================

; SPDX-License-Identifier: MIT

;------------------------------------------------------------------------
; Author:	Generated using the .svd description	The 2025-01-01
; Modifs:
;
; Project:	uKOS-X
; Goal:		RP2350_usb_dpram equates.
;
;   (c) 2025-2026, Edo. Franzi
;   --------------------------
;                                              __ ______  _____
;   Edo. Franzi                         __  __/ //_/ __ \/ ___/
;   5-Route de Cheseaux                / / / / ,< / / / /\__ \
;   CH 1400 Cheseaux-Noréaz           / /_/ / /| / /_/ /___/ /
;                                     \__,_/_/ |_\____//____/
;   edo.franzi@ukos.ch
;
;   Description: Lightweight, real-time multitasking operating
;   system for embedded microcontroller and DSP-based systems.
;
;   Permission is hereby granted, free of charge, to any person
;   obtaining a copy of this software and associated documentation
;   files (the "Software"), to deal in the Software without restriction,
;   including without limitation the rights to use, copy, modify,
;   merge, publish, distribute, sublicense, and/or sell copies of the
;   Software, and to permit persons to whom the Software is furnished
;   to do so, subject to the following conditions:
;
;   The above copyright notice and this permission notice shall be
;   included in all copies or substantial portions of the Software.
;
;   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
;   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
;   BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
;   ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
;   CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
;   SOFTWARE.
;
;------------------------------------------------------------------------
*/

#pragma	once

#include	<stdint.h>

// USB_DPRAM address definitions
// -----------------------------

typedef struct {
	volatile	uint32_t	SETUP_PACKET_LOW;
	volatile	uint32_t	SETUP_PACKET_HIGH;
	volatile	uint32_t	EP1_IN_CONTROL;
	volatile	uint32_t	EP1_OUT_CONTROL;
	volatile	uint32_t	EP2_IN_CONTROL;
	volatile	uint32_t	EP2_OUT_CONTROL;
	volatile	uint32_t	EP3_IN_CONTROL;
	volatile	uint32_t	EP3_OUT_CONTROL;
	volatile	uint32_t	EP4_IN_CONTROL;
	volatile	uint32_t	EP4_OUT_CONTROL;
	volatile	uint32_t	EP5_IN_CONTROL;
	volatile	uint32_t	EP5_OUT_CONTROL;
	volatile	uint32_t	EP6_IN_CONTROL;
	volatile	uint32_t	EP6_OUT_CONTROL;
	volatile	uint32_t	EP7_IN_CONTROL;
	volatile	uint32_t	EP7_OUT_CONTROL;
	volatile	uint32_t	EP8_IN_CONTROL;
	volatile	uint32_t	EP8_OUT_CONTROL;
	volatile	uint32_t	EP9_IN_CONTROL;
	volatile	uint32_t	EP9_OUT_CONTROL;
	volatile	uint32_t	EP10_IN_CONTROL;
	volatile	uint32_t	EP10_OUT_CONTROL;
	volatile	uint32_t	EP11_IN_CONTROL;
	volatile	uint32_t	EP11_OUT_CONTROL;
	volatile	uint32_t	EP12_IN_CONTROL;
	volatile	uint32_t	EP12_OUT_CONTROL;
	volatile	uint32_t	EP13_IN_CONTROL;
	volatile	uint32_t	EP13_OUT_CONTROL;
	volatile	uint32_t	EP14_IN_CONTROL;
	volatile	uint32_t	EP14_OUT_CONTROL;
	volatile	uint32_t	EP15_IN_CONTROL;
	volatile	uint32_t	EP15_OUT_CONTROL;
	volatile	uint32_t	EP0_IN_BUFFER_CONTROL;
	volatile	uint32_t	EP0_OUT_BUFFER_CONTROL;
	volatile	uint32_t	EP1_IN_BUFFER_CONTROL;
	volatile	uint32_t	EP1_OUT_BUFFER_CONTROL;
	volatile	uint32_t	EP2_IN_BUFFER_CONTROL;
	volatile	uint32_t	EP2_OUT_BUFFER_CONTROL;
	volatile	uint32_t	EP3_IN_BUFFER_CONTROL;
	volatile	uint32_t	EP3_OUT_BUFFER_CONTROL;
	volatile	uint32_t	EP4_IN_BUFFER_CONTROL;
	volatile	uint32_t	EP4_OUT_BUFFER_CONTROL;
	volatile	uint32_t	EP5_IN_BUFFER_CONTROL;
	volatile	uint32_t	EP5_OUT_BUFFER_CONTROL;
	volatile	uint32_t	EP6_IN_BUFFER_CONTROL;
	volatile	uint32_t	EP6_OUT_BUFFER_CONTROL;
	volatile	uint32_t	EP7_IN_BUFFER_CONTROL;
	volatile	uint32_t	EP7_OUT_BUFFER_CONTROL;
	volatile	uint32_t	EP8_IN_BUFFER_CONTROL;
	volatile	uint32_t	EP8_OUT_BUFFER_CONTROL;
	volatile	uint32_t	EP9_IN_BUFFER_CONTROL;
	volatile	uint32_t	EP9_OUT_BUFFER_CONTROL;
	volatile	uint32_t	EP10_IN_BUFFER_CONTROL;
	volatile	uint32_t	EP10_OUT_BUFFER_CONTROL;
	volatile	uint32_t	EP11_IN_BUFFER_CONTROL;
	volatile	uint32_t	EP11_OUT_BUFFER_CONTROL;
	volatile	uint32_t	EP12_IN_BUFFER_CONTROL;
	volatile	uint32_t	EP12_OUT_BUFFER_CONTROL;
	volatile	uint32_t	EP13_IN_BUFFER_CONTROL;
	volatile	uint32_t	EP13_OUT_BUFFER_CONTROL;
	volatile	uint32_t	EP14_IN_BUFFER_CONTROL;
	volatile	uint32_t	EP14_OUT_BUFFER_CONTROL;
	volatile	uint32_t	EP15_IN_BUFFER_CONTROL;
	volatile	uint32_t	EP15_OUT_BUFFER_CONTROL;
} USB_DPRAM_TypeDef;

#ifdef __cplusplus
#define	USB_DPRAM_NS	reinterpret_cast<USB_DPRAM_TypeDef *>(0x50100000u)
#define	USB_DPRAM_S		reinterpret_cast<USB_DPRAM_TypeDef *>(0x50100000u)
#else
#define	USB_DPRAM_NS	((USB_DPRAM_TypeDef *)0x50100000u)
#define	USB_DPRAM_S		((USB_DPRAM_TypeDef *)0x50100000u)
#endif

// SETUP_PACKET_LOW Configuration

#define	USB_DPRAM_SETUP_PACKET_LOW_BMREQUESTTYPE							(0xFFu<<0)
#define	USB_DPRAM_SETUP_PACKET_LOW_BMREQUESTTYPE_0							(0x1u<<0)
#define	USB_DPRAM_SETUP_PACKET_LOW_BREQUEST									(0xFFu<<8)
#define	USB_DPRAM_SETUP_PACKET_LOW_BREQUEST_0								(0x1u<<8)
#define	USB_DPRAM_SETUP_PACKET_LOW_WVALUE									(0xFFFFu<<16)
#define	USB_DPRAM_SETUP_PACKET_LOW_WVALUE_0									(0x1u<<16)

// SETUP_PACKET_HIGH Configuration

#define	USB_DPRAM_SETUP_PACKET_HIGH_WINDEX									(0xFFFFu<<0)
#define	USB_DPRAM_SETUP_PACKET_HIGH_WINDEX_0								(0x1u<<0)
#define	USB_DPRAM_SETUP_PACKET_HIGH_WLENGTH									(0xFFFFu<<16)
#define	USB_DPRAM_SETUP_PACKET_HIGH_WLENGTH_0								(0x1u<<16)

// EP1_IN_CONTROL Configuration

#define	USB_DPRAM_EP1_IN_CONTROL_BUFFER_ADDRESS								(0xFFFFu<<0)
#define	USB_DPRAM_EP1_IN_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP1_IN_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP1_IN_CONTROL_INTERRUPT_ON_STALL							(0x1u<<17)
#define	USB_DPRAM_EP1_IN_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP1_IN_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP1_IN_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP1_IN_CONTROL_INTERRUPT_PER_BUFF							(0x1u<<29)
#define	USB_DPRAM_EP1_IN_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP1_IN_CONTROL_ENABLE										(0x1u<<31)
#define	USB_DPRAM_EP1_IN_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP1_IN_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP1_IN_CONTROL_ENDPOINT_TYPE_BULK							(0x2u<<26)
#define	USB_DPRAM_EP1_IN_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP1_OUT_CONTROL Configuration

#define	USB_DPRAM_EP1_OUT_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP1_OUT_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP1_OUT_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP1_OUT_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP1_OUT_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP1_OUT_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP1_OUT_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP1_OUT_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP1_OUT_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP1_OUT_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP1_OUT_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP1_OUT_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP1_OUT_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP1_OUT_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP2_IN_CONTROL Configuration

#define	USB_DPRAM_EP2_IN_CONTROL_BUFFER_ADDRESS								(0xFFFFu<<0)
#define	USB_DPRAM_EP2_IN_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP2_IN_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP2_IN_CONTROL_INTERRUPT_ON_STALL							(0x1u<<17)
#define	USB_DPRAM_EP2_IN_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP2_IN_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP2_IN_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP2_IN_CONTROL_INTERRUPT_PER_BUFF							(0x1u<<29)
#define	USB_DPRAM_EP2_IN_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP2_IN_CONTROL_ENABLE										(0x1u<<31)
#define	USB_DPRAM_EP2_IN_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP2_IN_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP2_IN_CONTROL_ENDPOINT_TYPE_BULK							(0x2u<<26)
#define	USB_DPRAM_EP2_IN_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP2_OUT_CONTROL Configuration

#define	USB_DPRAM_EP2_OUT_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP2_OUT_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP2_OUT_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP2_OUT_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP2_OUT_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP2_OUT_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP2_OUT_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP2_OUT_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP2_OUT_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP2_OUT_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP2_OUT_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP2_OUT_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP2_OUT_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP2_OUT_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP3_IN_CONTROL Configuration

#define	USB_DPRAM_EP3_IN_CONTROL_BUFFER_ADDRESS								(0xFFFFu<<0)
#define	USB_DPRAM_EP3_IN_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP3_IN_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP3_IN_CONTROL_INTERRUPT_ON_STALL							(0x1u<<17)
#define	USB_DPRAM_EP3_IN_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP3_IN_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP3_IN_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP3_IN_CONTROL_INTERRUPT_PER_BUFF							(0x1u<<29)
#define	USB_DPRAM_EP3_IN_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP3_IN_CONTROL_ENABLE										(0x1u<<31)
#define	USB_DPRAM_EP3_IN_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP3_IN_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP3_IN_CONTROL_ENDPOINT_TYPE_BULK							(0x2u<<26)
#define	USB_DPRAM_EP3_IN_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP3_OUT_CONTROL Configuration

#define	USB_DPRAM_EP3_OUT_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP3_OUT_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP3_OUT_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP3_OUT_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP3_OUT_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP3_OUT_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP3_OUT_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP3_OUT_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP3_OUT_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP3_OUT_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP3_OUT_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP3_OUT_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP3_OUT_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP3_OUT_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP4_IN_CONTROL Configuration

#define	USB_DPRAM_EP4_IN_CONTROL_BUFFER_ADDRESS								(0xFFFFu<<0)
#define	USB_DPRAM_EP4_IN_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP4_IN_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP4_IN_CONTROL_INTERRUPT_ON_STALL							(0x1u<<17)
#define	USB_DPRAM_EP4_IN_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP4_IN_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP4_IN_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP4_IN_CONTROL_INTERRUPT_PER_BUFF							(0x1u<<29)
#define	USB_DPRAM_EP4_IN_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP4_IN_CONTROL_ENABLE										(0x1u<<31)
#define	USB_DPRAM_EP4_IN_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP4_IN_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP4_IN_CONTROL_ENDPOINT_TYPE_BULK							(0x2u<<26)
#define	USB_DPRAM_EP4_IN_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP4_OUT_CONTROL Configuration

#define	USB_DPRAM_EP4_OUT_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP4_OUT_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP4_OUT_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP4_OUT_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP4_OUT_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP4_OUT_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP4_OUT_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP4_OUT_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP4_OUT_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP4_OUT_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP4_OUT_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP4_OUT_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP4_OUT_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP4_OUT_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP5_IN_CONTROL Configuration

#define	USB_DPRAM_EP5_IN_CONTROL_BUFFER_ADDRESS								(0xFFFFu<<0)
#define	USB_DPRAM_EP5_IN_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP5_IN_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP5_IN_CONTROL_INTERRUPT_ON_STALL							(0x1u<<17)
#define	USB_DPRAM_EP5_IN_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP5_IN_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP5_IN_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP5_IN_CONTROL_INTERRUPT_PER_BUFF							(0x1u<<29)
#define	USB_DPRAM_EP5_IN_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP5_IN_CONTROL_ENABLE										(0x1u<<31)
#define	USB_DPRAM_EP5_IN_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP5_IN_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP5_IN_CONTROL_ENDPOINT_TYPE_BULK							(0x2u<<26)
#define	USB_DPRAM_EP5_IN_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP5_OUT_CONTROL Configuration

#define	USB_DPRAM_EP5_OUT_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP5_OUT_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP5_OUT_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP5_OUT_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP5_OUT_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP5_OUT_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP5_OUT_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP5_OUT_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP5_OUT_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP5_OUT_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP5_OUT_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP5_OUT_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP5_OUT_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP5_OUT_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP6_IN_CONTROL Configuration

#define	USB_DPRAM_EP6_IN_CONTROL_BUFFER_ADDRESS								(0xFFFFu<<0)
#define	USB_DPRAM_EP6_IN_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP6_IN_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP6_IN_CONTROL_INTERRUPT_ON_STALL							(0x1u<<17)
#define	USB_DPRAM_EP6_IN_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP6_IN_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP6_IN_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP6_IN_CONTROL_INTERRUPT_PER_BUFF							(0x1u<<29)
#define	USB_DPRAM_EP6_IN_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP6_IN_CONTROL_ENABLE										(0x1u<<31)
#define	USB_DPRAM_EP6_IN_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP6_IN_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP6_IN_CONTROL_ENDPOINT_TYPE_BULK							(0x2u<<26)
#define	USB_DPRAM_EP6_IN_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP6_OUT_CONTROL Configuration

#define	USB_DPRAM_EP6_OUT_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP6_OUT_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP6_OUT_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP6_OUT_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP6_OUT_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP6_OUT_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP6_OUT_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP6_OUT_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP6_OUT_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP6_OUT_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP6_OUT_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP6_OUT_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP6_OUT_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP6_OUT_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP7_IN_CONTROL Configuration

#define	USB_DPRAM_EP7_IN_CONTROL_BUFFER_ADDRESS								(0xFFFFu<<0)
#define	USB_DPRAM_EP7_IN_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP7_IN_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP7_IN_CONTROL_INTERRUPT_ON_STALL							(0x1u<<17)
#define	USB_DPRAM_EP7_IN_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP7_IN_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP7_IN_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP7_IN_CONTROL_INTERRUPT_PER_BUFF							(0x1u<<29)
#define	USB_DPRAM_EP7_IN_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP7_IN_CONTROL_ENABLE										(0x1u<<31)
#define	USB_DPRAM_EP7_IN_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP7_IN_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP7_IN_CONTROL_ENDPOINT_TYPE_BULK							(0x2u<<26)
#define	USB_DPRAM_EP7_IN_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP7_OUT_CONTROL Configuration

#define	USB_DPRAM_EP7_OUT_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP7_OUT_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP7_OUT_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP7_OUT_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP7_OUT_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP7_OUT_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP7_OUT_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP7_OUT_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP7_OUT_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP7_OUT_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP7_OUT_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP7_OUT_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP7_OUT_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP7_OUT_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP8_IN_CONTROL Configuration

#define	USB_DPRAM_EP8_IN_CONTROL_BUFFER_ADDRESS								(0xFFFFu<<0)
#define	USB_DPRAM_EP8_IN_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP8_IN_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP8_IN_CONTROL_INTERRUPT_ON_STALL							(0x1u<<17)
#define	USB_DPRAM_EP8_IN_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP8_IN_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP8_IN_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP8_IN_CONTROL_INTERRUPT_PER_BUFF							(0x1u<<29)
#define	USB_DPRAM_EP8_IN_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP8_IN_CONTROL_ENABLE										(0x1u<<31)
#define	USB_DPRAM_EP8_IN_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP8_IN_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP8_IN_CONTROL_ENDPOINT_TYPE_BULK							(0x2u<<26)
#define	USB_DPRAM_EP8_IN_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP8_OUT_CONTROL Configuration

#define	USB_DPRAM_EP8_OUT_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP8_OUT_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP8_OUT_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP8_OUT_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP8_OUT_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP8_OUT_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP8_OUT_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP8_OUT_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP8_OUT_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP8_OUT_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP8_OUT_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP8_OUT_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP8_OUT_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP8_OUT_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP9_IN_CONTROL Configuration

#define	USB_DPRAM_EP9_IN_CONTROL_BUFFER_ADDRESS								(0xFFFFu<<0)
#define	USB_DPRAM_EP9_IN_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP9_IN_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP9_IN_CONTROL_INTERRUPT_ON_STALL							(0x1u<<17)
#define	USB_DPRAM_EP9_IN_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP9_IN_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP9_IN_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP9_IN_CONTROL_INTERRUPT_PER_BUFF							(0x1u<<29)
#define	USB_DPRAM_EP9_IN_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP9_IN_CONTROL_ENABLE										(0x1u<<31)
#define	USB_DPRAM_EP9_IN_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP9_IN_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP9_IN_CONTROL_ENDPOINT_TYPE_BULK							(0x2u<<26)
#define	USB_DPRAM_EP9_IN_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP9_OUT_CONTROL Configuration

#define	USB_DPRAM_EP9_OUT_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP9_OUT_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP9_OUT_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP9_OUT_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP9_OUT_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP9_OUT_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP9_OUT_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP9_OUT_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP9_OUT_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP9_OUT_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP9_OUT_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP9_OUT_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP9_OUT_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP9_OUT_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP10_IN_CONTROL Configuration

#define	USB_DPRAM_EP10_IN_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP10_IN_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP10_IN_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP10_IN_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP10_IN_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP10_IN_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP10_IN_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP10_IN_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP10_IN_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP10_IN_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP10_IN_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP10_IN_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP10_IN_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP10_IN_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP10_OUT_CONTROL Configuration

#define	USB_DPRAM_EP10_OUT_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP10_OUT_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP10_OUT_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP10_OUT_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP10_OUT_CONTROL_ENDPOINT_TYPE							(0x3u<<26)
#define	USB_DPRAM_EP10_OUT_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP10_OUT_CONTROL_INTERRUPT_PER_DOUBLE_BUFF				(0x1u<<28)
#define	USB_DPRAM_EP10_OUT_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP10_OUT_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP10_OUT_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP10_OUT_CONTROL_ENDPOINT_TYPE_CONTROL					(0x0u<<26)
#define	USB_DPRAM_EP10_OUT_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS				(0x1u<<26)
#define	USB_DPRAM_EP10_OUT_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP10_OUT_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP11_IN_CONTROL Configuration

#define	USB_DPRAM_EP11_IN_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP11_IN_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP11_IN_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP11_IN_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP11_IN_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP11_IN_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP11_IN_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP11_IN_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP11_IN_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP11_IN_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP11_IN_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP11_IN_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP11_IN_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP11_IN_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP11_OUT_CONTROL Configuration

#define	USB_DPRAM_EP11_OUT_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP11_OUT_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP11_OUT_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP11_OUT_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP11_OUT_CONTROL_ENDPOINT_TYPE							(0x3u<<26)
#define	USB_DPRAM_EP11_OUT_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP11_OUT_CONTROL_INTERRUPT_PER_DOUBLE_BUFF				(0x1u<<28)
#define	USB_DPRAM_EP11_OUT_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP11_OUT_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP11_OUT_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP11_OUT_CONTROL_ENDPOINT_TYPE_CONTROL					(0x0u<<26)
#define	USB_DPRAM_EP11_OUT_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS				(0x1u<<26)
#define	USB_DPRAM_EP11_OUT_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP11_OUT_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP12_IN_CONTROL Configuration

#define	USB_DPRAM_EP12_IN_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP12_IN_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP12_IN_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP12_IN_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP12_IN_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP12_IN_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP12_IN_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP12_IN_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP12_IN_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP12_IN_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP12_IN_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP12_IN_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP12_IN_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP12_IN_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP12_OUT_CONTROL Configuration

#define	USB_DPRAM_EP12_OUT_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP12_OUT_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP12_OUT_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP12_OUT_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP12_OUT_CONTROL_ENDPOINT_TYPE							(0x3u<<26)
#define	USB_DPRAM_EP12_OUT_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP12_OUT_CONTROL_INTERRUPT_PER_DOUBLE_BUFF				(0x1u<<28)
#define	USB_DPRAM_EP12_OUT_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP12_OUT_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP12_OUT_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP12_OUT_CONTROL_ENDPOINT_TYPE_CONTROL					(0x0u<<26)
#define	USB_DPRAM_EP12_OUT_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS				(0x1u<<26)
#define	USB_DPRAM_EP12_OUT_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP12_OUT_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP13_IN_CONTROL Configuration

#define	USB_DPRAM_EP13_IN_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP13_IN_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP13_IN_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP13_IN_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP13_IN_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP13_IN_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP13_IN_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP13_IN_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP13_IN_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP13_IN_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP13_IN_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP13_IN_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP13_IN_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP13_IN_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP13_OUT_CONTROL Configuration

#define	USB_DPRAM_EP13_OUT_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP13_OUT_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP13_OUT_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP13_OUT_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP13_OUT_CONTROL_ENDPOINT_TYPE							(0x3u<<26)
#define	USB_DPRAM_EP13_OUT_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP13_OUT_CONTROL_INTERRUPT_PER_DOUBLE_BUFF				(0x1u<<28)
#define	USB_DPRAM_EP13_OUT_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP13_OUT_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP13_OUT_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP13_OUT_CONTROL_ENDPOINT_TYPE_CONTROL					(0x0u<<26)
#define	USB_DPRAM_EP13_OUT_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS				(0x1u<<26)
#define	USB_DPRAM_EP13_OUT_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP13_OUT_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP14_IN_CONTROL Configuration

#define	USB_DPRAM_EP14_IN_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP14_IN_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP14_IN_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP14_IN_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP14_IN_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP14_IN_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP14_IN_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP14_IN_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP14_IN_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP14_IN_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP14_IN_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP14_IN_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP14_IN_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP14_IN_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP14_OUT_CONTROL Configuration

#define	USB_DPRAM_EP14_OUT_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP14_OUT_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP14_OUT_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP14_OUT_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP14_OUT_CONTROL_ENDPOINT_TYPE							(0x3u<<26)
#define	USB_DPRAM_EP14_OUT_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP14_OUT_CONTROL_INTERRUPT_PER_DOUBLE_BUFF				(0x1u<<28)
#define	USB_DPRAM_EP14_OUT_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP14_OUT_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP14_OUT_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP14_OUT_CONTROL_ENDPOINT_TYPE_CONTROL					(0x0u<<26)
#define	USB_DPRAM_EP14_OUT_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS				(0x1u<<26)
#define	USB_DPRAM_EP14_OUT_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP14_OUT_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP15_IN_CONTROL Configuration

#define	USB_DPRAM_EP15_IN_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP15_IN_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP15_IN_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP15_IN_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP15_IN_CONTROL_ENDPOINT_TYPE								(0x3u<<26)
#define	USB_DPRAM_EP15_IN_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP15_IN_CONTROL_INTERRUPT_PER_DOUBLE_BUFF					(0x1u<<28)
#define	USB_DPRAM_EP15_IN_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP15_IN_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP15_IN_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP15_IN_CONTROL_ENDPOINT_TYPE_CONTROL						(0x0u<<26)
#define	USB_DPRAM_EP15_IN_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS					(0x1u<<26)
#define	USB_DPRAM_EP15_IN_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP15_IN_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP15_OUT_CONTROL Configuration

#define	USB_DPRAM_EP15_OUT_CONTROL_BUFFER_ADDRESS							(0xFFFFu<<0)
#define	USB_DPRAM_EP15_OUT_CONTROL_BUFFER_ADDRESS_0							(0x1u<<0)
#define	USB_DPRAM_EP15_OUT_CONTROL_INTERRUPT_ON_NAK							(0x1u<<16)
#define	USB_DPRAM_EP15_OUT_CONTROL_INTERRUPT_ON_STALL						(0x1u<<17)
#define	USB_DPRAM_EP15_OUT_CONTROL_ENDPOINT_TYPE							(0x3u<<26)
#define	USB_DPRAM_EP15_OUT_CONTROL_ENDPOINT_TYPE_0							(0x1u<<26)
#define	USB_DPRAM_EP15_OUT_CONTROL_INTERRUPT_PER_DOUBLE_BUFF				(0x1u<<28)
#define	USB_DPRAM_EP15_OUT_CONTROL_INTERRUPT_PER_BUFF						(0x1u<<29)
#define	USB_DPRAM_EP15_OUT_CONTROL_DOUBLE_BUFFERED							(0x1u<<30)
#define	USB_DPRAM_EP15_OUT_CONTROL_ENABLE									(0x1u<<31)
#define	USB_DPRAM_EP15_OUT_CONTROL_ENDPOINT_TYPE_CONTROL					(0x0u<<26)
#define	USB_DPRAM_EP15_OUT_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS				(0x1u<<26)
#define	USB_DPRAM_EP15_OUT_CONTROL_ENDPOINT_TYPE_BULK						(0x2u<<26)
#define	USB_DPRAM_EP15_OUT_CONTROL_ENDPOINT_TYPE_INTERRUPT					(0x3u<<26)

// EP0_IN_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_AVAILABLE_0							(0x1u<<10)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_AVAILABLE_1							(0x1u<<26)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP0_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP0_OUT_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP0_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP1_IN_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_AVAILABLE_0							(0x1u<<10)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_AVAILABLE_1							(0x1u<<26)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP1_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP1_OUT_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP1_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP2_IN_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_AVAILABLE_0							(0x1u<<10)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_AVAILABLE_1							(0x1u<<26)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP2_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP2_OUT_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP2_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP3_IN_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_AVAILABLE_0							(0x1u<<10)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_AVAILABLE_1							(0x1u<<26)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP3_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP3_OUT_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP3_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP4_IN_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_AVAILABLE_0							(0x1u<<10)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_AVAILABLE_1							(0x1u<<26)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP4_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP4_OUT_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP4_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP5_IN_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_AVAILABLE_0							(0x1u<<10)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_AVAILABLE_1							(0x1u<<26)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP5_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP5_OUT_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP5_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP6_IN_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_AVAILABLE_0							(0x1u<<10)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_AVAILABLE_1							(0x1u<<26)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP6_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP6_OUT_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP6_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP7_IN_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_AVAILABLE_0							(0x1u<<10)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_AVAILABLE_1							(0x1u<<26)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP7_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP7_OUT_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP7_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP8_IN_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_AVAILABLE_0							(0x1u<<10)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_AVAILABLE_1							(0x1u<<26)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP8_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP8_OUT_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP8_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP9_IN_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_AVAILABLE_0							(0x1u<<10)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_AVAILABLE_1							(0x1u<<26)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP9_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP9_OUT_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP9_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP10_IN_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP10_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP10_OUT_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_LENGTH_0_0						(0x1u<<0)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_LAST_0							(0x1u<<14)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_FULL_0							(0x1u<<15)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_LENGTH_1_0						(0x1u<<16)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0		(0x1u<<27)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_LAST_1							(0x1u<<30)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_FULL_1							(0x1u<<31)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP10_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP11_IN_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP11_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP11_OUT_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_LENGTH_0_0						(0x1u<<0)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_LAST_0							(0x1u<<14)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_FULL_0							(0x1u<<15)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_LENGTH_1_0						(0x1u<<16)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0		(0x1u<<27)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_LAST_1							(0x1u<<30)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_FULL_1							(0x1u<<31)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP11_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP12_IN_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP12_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP12_OUT_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_LENGTH_0_0						(0x1u<<0)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_LAST_0							(0x1u<<14)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_FULL_0							(0x1u<<15)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_LENGTH_1_0						(0x1u<<16)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0		(0x1u<<27)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_LAST_1							(0x1u<<30)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_FULL_1							(0x1u<<31)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP12_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP13_IN_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP13_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP13_OUT_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_LENGTH_0_0						(0x1u<<0)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_LAST_0							(0x1u<<14)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_FULL_0							(0x1u<<15)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_LENGTH_1_0						(0x1u<<16)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0		(0x1u<<27)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_LAST_1							(0x1u<<30)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_FULL_1							(0x1u<<31)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP13_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP14_IN_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP14_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP14_OUT_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_LENGTH_0_0						(0x1u<<0)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_LAST_0							(0x1u<<14)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_FULL_0							(0x1u<<15)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_LENGTH_1_0						(0x1u<<16)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0		(0x1u<<27)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_LAST_1							(0x1u<<30)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_FULL_1							(0x1u<<31)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP14_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP15_IN_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_LENGTH_0_0							(0x1u<<0)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_LAST_0								(0x1u<<14)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_FULL_0								(0x1u<<15)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_LENGTH_1_0							(0x1u<<16)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0			(0x1u<<27)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_LAST_1								(0x1u<<30)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_FULL_1								(0x1u<<31)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP15_IN_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)

// EP15_OUT_BUFFER_CONTROL Configuration

#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_LENGTH_0							(0x3FFu<<0)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_LENGTH_0_0						(0x1u<<0)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_AVAILABLE_0						(0x1u<<10)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_STALL								(0x1u<<11)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_RESET								(0x1u<<12)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_PID_0								(0x1u<<13)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_LAST_0							(0x1u<<14)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_FULL_0							(0x1u<<15)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_LENGTH_1							(0x3FFu<<16)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_LENGTH_1_0						(0x1u<<16)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_AVAILABLE_1						(0x1u<<26)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET			(0x3u<<27)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_0		(0x1u<<27)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_PID_1								(0x1u<<29)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_LAST_1							(0x1u<<30)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_FULL_1							(0x1u<<31)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128		(0x0u<<27)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256		(0x1u<<27)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512		(0x2u<<27)
#define	USB_DPRAM_EP15_OUT_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024		(0x3u<<27)
