/*
; cluster_Py.
; ===========

; SPDX-License-Identifier: MIT

;------------------------------------------------------------------------
; Author:	Edo. Franzi
; Modifs:	Laurent von Allmen
;
; Project:	uKOS-X
; Goal:		Demo of a C application.
;			This application shows how to operate with the uKOS-X uKernel.
;
;			Launch 1 processes in C++:
;
;			- P0: Every 1000-ms
;				  Compute the inference
;				  Display the classes
;
;   (c) 2025-2026, Edo. Franzi
;   --------------------------
;                                              __ ______  _____
;   Edo. Franzi                         __  __/ //_/ __ \/ ___/
;   5-Route de Cheseaux                / / / / ,< / / / /\__ \
;   CH 1400 Cheseaux-Noréaz           / /_/ / /| / /_/ /___/ /
;                                     \__,_/_/ |_\____//____/
;   edo.franzi@ukos.ch
;
;   Description: Lightweight, real-time multitasking operating
;   system for embedded microcontroller and DSP-based systems.
;
;   Permission is hereby granted, free of charge, to any person
;   obtaining a copy of this software and associated documentation
;   files (the "Software"), to deal in the Software without restriction,
;   including without limitation the rights to use, copy, modify,
;   merge, publish, distribute, sublicense, and/or sell copies of the
;   Software, and to permit persons to whom the Software is furnished
;   to do so, subject to the following conditions:
;
;   The above copyright notice and this permission notice shall be
;   included in all copies or substantial portions of the Software.
;
;   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
;   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
;   BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
;   ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
;   CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
;   SOFTWARE.
;
;------------------------------------------------------------------------
*/

/*!
 * \file
 * \ingroup app_mlp
 * \brief This application shows how to operate with the uKOS uKernel.
 *
 *			Launch 1 processes:
 *
 *			- P0: Configure the mlp
 *				  Every 1000-ms
 *					- Simple 3 layer MLP (1 hidden layers)
 *
 */

#include	<inttypes.h>
#include	<stdio.h>
#include	<stdlib.h>

#include	"crt0.h"
#include	"serial/serial.h"
#include	"kern/kern.h"
#include	"macros.h"
#include	"macros_core.h"
#include	"macros_core_stackFrame.h"
#include	"memo/memo.h"
#include	"mlpn/mlpn.h"
#include	"modules.h"
#include	"os_errors.h"
#include	"random/random.h"
#include	"record/record.h"
#include	"types.h"

// MLP model generated by Py

#include	"./_Training/network.c_inc"

// uKOS-X specific (see the module.h)
// ==================================

// ----------------------------------I------------I-----------------------------------------I--------------I

STRG_LOC_CONST(aStrApplication[]) =	"cluster_Py   Py 3 layer MLP test.                      (c) EFr-2026";
STRG_LOC_CONST(aStrHelp[])		  = "This is a romable C application\n"
									"===============================\n\n"

									"This user function module is a C written application.\n\n"

									"Input format:  cluster_Py\n"
									"Output format: [result]\n\n"

									"Module built on "__DATE__"  "__TIME__" (c) EFr-2026\n\n";

#ifdef ROMABLE_S

// Prototypes

static	int32_t		prgm(uint32_t argc, const char_t *argv[]);

MODULE(
	Cluster_Py,							// Module name (the first letter has to be upper case)
	KID_FAM_CLI,						// Family (defined in the module.h)
	KNUM_ROMABLE_0,						// Module identifier (defined in the module.h)
	NULL,								// Address of the initialisation code (early pre-init)
	prgm,								// Address of the code (prgm for tools, aStart for applications, NULL for libraries)
	NULL,								// Address of the clean code (clean the module)
	" 1.0",								// Revision string (major . minor)
	((1U<<BSHOW) | (1U<<BEXE_CONSOLE)),	// Flags (BSHOW = visible with "man", BEXE_CONSOLE = executable, BCONFIDENTIAL = hidden)
	0									// Execution cores
);

#else
MODULE(
	UserAppl,							// Module name (the first letter has to be upper case)
	KID_FAM_APPLICATIONS,				// Family (defined in the module.h)
	KNUM_APPLICATION,					// Module identifier (defined in the module.h)
	NULL,								// Address of the initialisation code (early pre-init)
	aStart,								// Address of the code (prgm for tools, aStart for applications, NULL for libraries)
	NULL,								// Address of the clean code (clean the module)
	" 1.0",								// Revision string (major . minor)
	((1U<<BSHOW) | (1U<<BEXE_CONSOLE)),	// Flags (BSHOW = visible with "man", BEXE_CONSOLE = executable, BCONFIDENTIAL = hidden)
	0									// Execution cores
);
#endif

/*
 * \brief aProcess 0
 *
 * - P0:  Configure the mlp
 *		  Every 1000-ms
 *			- Simple 4 layer MLP (2 hidden layers)
 *			- Display the result
 *
 */
static	void	__attribute__ ((noreturn)) aProcess_0(const void *argument) {
	UNUSED(argument);

			float32_t	x, y, gain = 2.0f;
			uint64_t	time[2];
			uint32_t	random[2], delta = 0U;
	const	char_t		*result;

//	mlpn_configure(&aNetwork);

	while (true) {
		kern_suspendProcess(1000U);

// Prepare the inputs

		random_read(KRANDOM_SOFT, &random[0], 2U);
		x = (((float32_t)random[0] / (float32_t)(KRAND_MAX)) - 0.5f) * gain;
		y = (((float32_t)random[1] / (float32_t)(KRAND_MAX)) - 0.5f) * gain;

		vInput_L1[0] = x;
		vInput_L1[1] = y;

		kern_readTickCount(&time[0]);
		mlpn_compute(&aNetwork);
		kern_readTickCount(&time[1]);
		delta = (uint32_t)(time[1] - time[0]);

// Display the results

		result = "Inter-class area";
		result = ((vOutput_L3[0] >  0.2f) && (vOutput_L3[1] < -0.2f) && (vOutput_L3[2] < -0.2f) && (vOutput_L3[3] < -0.2f) && (vOutput_L3[4] < -0.2f)) ? ("Class A         ") : (result);
		result = ((vOutput_L3[1] >  0.2f) && (vOutput_L3[0] < -0.2f) && (vOutput_L3[2] < -0.2f) && (vOutput_L3[3] < -0.2f) && (vOutput_L3[4] < -0.2f)) ? ("Class B         ") : (result);
		result = ((vOutput_L3[2] >  0.2f) && (vOutput_L3[0] < -0.2f) && (vOutput_L3[1] < -0.2f) && (vOutput_L3[3] < -0.2f) && (vOutput_L3[4] < -0.2f)) ? ("Class C         ") : (result);
		result = ((vOutput_L3[3] >  0.2f) && (vOutput_L3[0] < -0.2f) && (vOutput_L3[1] < -0.2f) && (vOutput_L3[2] < -0.2f) && (vOutput_L3[4] < -0.2f)) ? ("Class D         ") : (result);

		(void)dprintf(KSYST, "In-0 %6.3f, In-1 %6.3f, "
							 "result: Out-0 %6.3f, Out-1 %6.3f, Out-2 %6.3f, Out-3 %6.3f, Out-4 %6.3f "
							 "    %s "
							 "Exec time %"PRIu32" [us]\n", x,
							 							   y,
							 							   vOutput_L3[0],
							 							   vOutput_L3[1],
							 							   vOutput_L3[2],
							 							   vOutput_L3[3],
							 							   vOutput_L3[4],
							 							   result,
							 							   delta);
	}
}

/*
 * \brief main
 *
 * - Initialise the used libraries
 * - Launch all the processes
 * - Kill the "main". At this moment only the launched processes are executed
 *
 */
MAIN_ENTRY(argc, argv[]) {
	UNUSED(argc);
	UNUSED(argv);

	proc_t	*process_0;

// ---------------------------------I-----------------------------------------I--------------I

	STRG_LOC_CONST(aStrIden_0[]) = "Process_User_0";
	STRG_LOC_CONST(aStrText_0[]) = "Process user 0.                           (c) EFr-2026";

// Specifications for the processes

	PROCESS_STACKMALLOC(
		0,									// Index
		specification_0,					// Specifications (just use specification_x)
		aStrText_0,							// Info string (NULL if anonymous)
		KKERN_SZ_STACK_XLIB,				// KKERN_SZ_STACK_xx Stack size (number of words (machine size). _XL Extra large, _LL Large, _MM Medium, _SS Small)
		aProcess_0,							// Code of the process
		aStrIden_0,							// Identifier (NULL if anonymous)
		KSYST,								// Default Serial Communication Manager (KDEF0, KURTx, KSYST, ...)
		KKERN_PRIORITY_HIGH_01				// KKERN_PRIORITY_HIGH < Priority < KKERN_PRIORITY_LOW_14. KKERN_PRIORITY_LOW_15 is reserved for the idle process
	);

// Create the user processes

	if (kern_createProcess(&specification_0, NULL, &process_0) != KERR_KERN_NOERR) { LOG(KFATAL_USER, "Create proc"); return (EXIT_OS_FAILURE); }

	LOG(KINFO_USER, "Application launched, kill the console");
	return (EXIT_OS_SUCCESS);
}
